package tool

import (
	"context"
	"errors"
	"maps"
	"slices"

	"github.com/Tangerg/lynx/core/model/chat"
)

// interruptsToolLoop reports whether a tool error is a human-in-the-loop
// INTERRUPT — the loop must exit immediately and propagate it unchanged
// (no feedback to the model, no abort-masking) so the caller can park the
// run and gather input. A tool signals it by returning an error
// implementing ToolLoopInterrupt() bool returning true
// (agent/hitl.InterruptError does). Duck-typed so this package never
// imports agent — the one-way dependency holds.
//
// This is the Go-ecosystem interrupt model (LangGraph / eino /
// trpc-agent-go): the interrupt is an ordinary error carrying its payload;
// it bubbles to where it is handled, the payload is extracted, HITL is
// triggered, and on resume the human's response is fed back at the original
// call site.
func interruptsToolLoop(err error) bool {
	var i interface{ ToolLoopInterrupt() bool }
	return errors.As(err, &i) && i.ToolLoopInterrupt()
}

// LoopInterrupted is the error the tool loop returns when a tool
// interrupts the run for human input. It carries the Conversation
// checkpoint the loop had at the interrupt — the assistant message that
// requested this round's tools, and (when some of the round's calls
// already ran) a tool message holding their results — i.e. everything
// needed to RESUME the turn by executing the still-pending tool calls,
// without re-invoking the model.
//
// The checkpoint is intentionally thin: the prior conversation lives in
// the memory store (the memory middleware persisted the assistant reply
// before the interrupt), so it does not need to travel here. On resume the
// caller re-applies the system prompt and feeds this checkpoint back as the
// request messages; the loop detects the trailing unanswered tool calls and
// resumes execution, while the memory middleware splices the stored history
// back in.
//
// The caller (the agent action) saves Conversation, parks the run on the
// underlying interrupt (Unwrap → the tool's interrupt error, which carries
// the user-facing payload + the resume awaitable).
type LoopInterrupted struct {
	// Conversation is the resume checkpoint to feed back on resume. Its tail
	// is the assistant tool-call message, optionally followed by a tool
	// message with the results already produced this round.
	Conversation []chat.Message

	// cause is the tool's interrupt error (carries the HITL payload). It is
	// reachable via errors.As through Unwrap.
	cause error
}

func (e *LoopInterrupted) Error() string {
	return "tool: loop interrupted for human input: " + e.cause.Error()
}

// Unwrap exposes the underlying interrupt error so callers extract the
// payload / awaitable with errors.As.
func (e *LoopInterrupted) Unwrap() error { return e.cause }

// roundInterrupt is the partial result of a tool round that
// interrupted: the results already produced this invocation (done) and the
// interrupt error to propagate. The still-pending calls are derived from
// the assistant message at resume time (its tool calls minus the answered
// ones), so they are not carried here.
type roundInterrupt struct {
	done  []*chat.ToolReturn
	cause error
}

// systemMessages returns the system messages of msgs (zero or one in
// practice). The tool loop forwards them on every downstream request so the
// model always sees the turn's system header first; the memory middleware
// never stores system messages, so they must ride along with each round.
func systemMessages(msgs []chat.Message) []chat.Message {
	return chat.FilterMessagesByMessageTypes(msgs, chat.MessageTypeSystem)
}

// interruptedConversation assembles the resume checkpoint for a round that
// interrupted: the assistant tool-call message, and — when some calls
// already ran — a tool message with their results. On resume
// [trailingPendingToolCalls] reads this shape to find the calls still to
// run.
//
// It is deliberately thin: the prior conversation lives in the memory store
// and the system header is regenerated by the caller on resume, so the
// checkpoint carries only what the store does NOT yet have — the pending
// assistant turn and any partial results.
func interruptedConversation(assistant *chat.AssistantMessage, done []*chat.ToolReturn) []chat.Message {
	out := []chat.Message{assistant}
	if len(done) > 0 {
		if tm, err := chat.NewToolMessage(done); err == nil {
			out = append(out, tm)
		}
	}
	return out
}

// trailingPendingToolCalls inspects the conversation tail for a resume
// point: an assistant message whose tool calls are not yet fully answered
// by a following tool message. It returns that assistant message, the
// results already produced (partial, in call order), and the calls still
// pending (in the assistant's order). When the tail is not a resumable
// point — no trailing assistant tool calls, or every call already answered
// — it returns (nil, nil, nil) and the loop starts a normal model round.
//
// This is what makes resume conversation-driven: a turn parked mid-round
// is fed its saved conversation back; the shape alone tells the loop to
// execute the remaining calls rather than ask the model again.
func trailingPendingToolCalls(msgs []chat.Message) (assistant *chat.AssistantMessage, done []*chat.ToolReturn, pending []*chat.ToolCallPart) {
	if len(msgs) == 0 {
		return nil, nil, nil
	}

	var partial *chat.ToolMessage
	switch last := msgs[len(msgs)-1].(type) {
	case *chat.ToolMessage:
		partial = last
		if len(msgs) < 2 {
			return nil, nil, nil
		}
		am, ok := msgs[len(msgs)-2].(*chat.AssistantMessage)
		if !ok || !am.HasToolCalls() {
			return nil, nil, nil
		}
		assistant = am
	case *chat.AssistantMessage:
		if !last.HasToolCalls() {
			return nil, nil, nil
		}
		assistant = last
	default:
		return nil, nil, nil
	}

	answered := make(map[string]*chat.ToolReturn)
	if partial != nil {
		for _, ret := range partial.ToolReturns {
			answered[ret.ID] = ret
		}
	}

	for _, call := range assistant.CollectToolCalls() {
		if ret, ok := answered[call.ID]; ok {
			done = append(done, ret)
			continue
		}
		pending = append(pending, call)
	}
	if len(pending) == 0 {
		return nil, nil, nil // fully answered → not a resume point
	}
	return assistant, done, pending
}

// mergeRoundReturns orders the round's tool returns to match the
// assistant's tool-call order, drawing each from the already-done set or
// the freshly-produced set. Keeps tool_call_id ↔ result correlation intact
// for the next model round.
func mergeRoundReturns(calls []*chat.ToolCallPart, done, fresh []*chat.ToolReturn) []*chat.ToolReturn {
	byID := make(map[string]*chat.ToolReturn, len(done)+len(fresh))
	for _, r := range done {
		byID[r.ID] = r
	}
	for _, r := range fresh {
		byID[r.ID] = r
	}
	out := make([]*chat.ToolReturn, 0, len(calls))
	for _, call := range calls {
		if r, ok := byID[call.ID]; ok {
			out = append(out, r)
		}
	}
	return out
}

// allReturnDirect reports whether every tool referenced in returns is
// registered AND return-direct — the resume-path analog of the
// allReturnDirect bit [callInvoker.invokeToolCalls] computes inline.
func (support *Support) allReturnDirect(returns []*chat.ToolReturn) bool {
	for _, ret := range returns {
		t, exists := support.registry.Find(ret.Name)
		if !exists || !t.Metadata().ReturnDirect {
			return false
		}
	}
	return true
}

// priorModelRounds counts the assistant messages in a resumed conversation
// — the model rounds already spent — so the resumed loop keeps counting
// toward the iteration cap instead of restarting at 1.
func priorModelRounds(msgs []chat.Message) int {
	n := 0
	for _, msg := range msgs {
		if _, ok := msg.(*chat.AssistantMessage); ok {
			n++
		}
	}
	if n == 0 {
		return 1
	}
	return n
}

// wrapInterrupt builds the *LoopInterrupted carrying the resume
// checkpoint (the assistant tool-call message + the results already
// produced this round) around the tool's interrupt cause.
func (m *Middleware) wrapInterrupt(assistant *chat.AssistantMessage, done []*chat.ToolReturn, cause error) error {
	return &LoopInterrupted{
		Conversation: interruptedConversation(assistant, done),
		cause:        cause,
	}
}

// resumeCallRound runs the pending tool calls of a resumed round on the
// synchronous path, then re-interrupts, returns direct, or continues the
// loop at the next model round.
func (m *Middleware) resumeCallRound(ctx context.Context, req *chat.Request, assistant *chat.AssistantMessage, done []*chat.ToolReturn, pending []*chat.ToolCallPart, next chat.CallHandler, support *Support, state loopState) (*chat.Response, error) {
	res, err := support.invoker.invokeToolCalls(ctx, pending)
	if err != nil {
		return nil, err
	}
	if res.interrupt != nil {
		// Another call in the same round interrupted: fold the results so
		// far into the round's done-set and re-wrap; the assistant turn is
		// unchanged.
		merged := append(slices.Clone(done), res.interrupt.done...)
		return nil, m.wrapInterrupt(assistant, merged, res.interrupt.cause)
	}

	full := mergeRoundReturns(assistant.CollectToolCalls(), done, res.toolMessage.ToolReturns)
	toolMsg, err := chat.NewToolMessage(full)
	if err != nil {
		return nil, err
	}
	if support.allReturnDirect(full) {
		return buildResumedReturnResponse(assistant, toolMsg)
	}
	nextReq, err := buildResumedContinueRequest(req, assistant, toolMsg)
	if err != nil {
		return nil, err
	}
	return m.executeCallRecursively(ctx, nextReq, next, support, state.next())
}

// resumeStreamRound is the streaming analog of [resumeCallRound]. It
// surfaces the resumed round's tool message to the stream (so the wire
// timeline + caller's per-round budget boundary see it) before continuing.
func (m *Middleware) resumeStreamRound(ctx context.Context, req *chat.Request, assistant *chat.AssistantMessage, done []*chat.ToolReturn, pending []*chat.ToolCallPart, next chat.StreamHandler, support *Support, yield func(*chat.Response, error) bool, state loopState) {
	res, err := support.invoker.invokeToolCalls(ctx, pending)
	if err != nil {
		yield(nil, err)
		return
	}
	if res.interrupt != nil {
		merged := append(slices.Clone(done), res.interrupt.done...)
		yield(nil, m.wrapInterrupt(assistant, merged, res.interrupt.cause))
		return
	}

	full := mergeRoundReturns(assistant.CollectToolCalls(), done, res.toolMessage.ToolReturns)
	toolMsg, err := chat.NewToolMessage(full)
	if err != nil {
		yield(nil, err)
		return
	}
	if toolResp, e := newToolMessageResponse(toolMsg); e == nil && !yield(toolResp, nil) {
		return
	}
	if support.allReturnDirect(full) {
		yield(buildResumedReturnResponse(assistant, toolMsg))
		return
	}
	nextReq, err := buildResumedContinueRequest(req, assistant, toolMsg)
	if err != nil {
		yield(nil, err)
		return
	}
	m.executeStreamRecursively(ctx, nextReq, next, support, yield, state.next())
}

// buildResumedContinueRequest assembles the next model request after a
// resumed round completes: the turn's system header, the assistant tool-call
// message, and the assembled tool results, carrying the live request's
// options / tools / params. As with
// [InvocationResult.BuildContinueRequest], the prior conversation is NOT
// re-sent (the memory middleware splices stored history back in), but the
// assistant + tool results travel together so the memory layer persists the
// exchange atomically — the interrupting round's assistant was deliberately
// never persisted, so this is where the (assistant, tool) pair lands.
func buildResumedContinueRequest(req *chat.Request, assistant *chat.AssistantMessage, toolMsg *chat.ToolMessage) (*chat.Request, error) {
	msgs := append(systemMessages(req.Messages), chat.Message(assistant), chat.Message(toolMsg))
	next, err := chat.NewRequest(msgs)
	if err != nil {
		return nil, err
	}
	next.Options = req.Options.Clone()
	next.Tools = slices.Clone(req.Tools)
	next.Params = maps.Clone(req.Params)
	return next, nil
}

// buildResumedReturnResponse wraps a resumed round's tool message as the
// final response when every tool in the round is return-direct.
func buildResumedReturnResponse(assistant *chat.AssistantMessage, toolMsg *chat.ToolMessage) (*chat.Response, error) {
	result, err := chat.NewResult(assistant, &chat.ResultMetadata{FinishReason: chat.FinishReasonReturnDirect})
	if err != nil {
		return nil, err
	}
	result.ToolMessage = toolMsg
	return chat.NewResponse(result, &chat.ResponseMetadata{})
}
