import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeAll, describe, expect, it, vi } from "vitest";
import { getHighlighter } from "@/lib/highlight/shiki";
import { MarkdownMessage } from "./MarkdownMessage";

// MarkdownMessage now renders through react-markdown + remark-gfm with our
// rehype-fade-in plugin and a Shiki/Mermaid component map. These tests
// cover the high-value invariants:
//
//   1. Streaming partials never throw or hang.
//   2. Unmatched markers (`` ` ``, `**`, ` ``` `) get auto-closed by
//      closeOpenMarkers so the model's mid-flight tokens already look
//      "right" while the closer streams in.
//   3. Block-level constructs (fenced code, lists, headings) render via
//      react-markdown rather than as raw backticks / hashes.
//   4. Each non-code text node gets per-word `<span class="fade-in">`
//      wrappers from rehypeFadeIn.
//   5. With `instant`, no `.fade-in` wrappers are produced.

describe("markdownMessage", () => {
  beforeAll(async () => {
    // The highlighter is an application-lifetime lazy singleton. Resolve its
    // module/grammar load before mounting effects so this test file does not
    // abandon that shared initialization when its synchronous assertions end.
    await getHighlighter();
  });

  it("renders an empty string without throwing", () => {
    const { container } = render(<MarkdownMessage text="" reveal="smooth" />);
    // react-markdown adds a wrapper div; the body is just empty.
    expect(container.querySelector(".md")).toBeTruthy();
  });

  it("wraps plain words in .fade-in spans", () => {
    const { container } = render(<MarkdownMessage text="Hello world" reveal="smooth" />);
    const spans = container.querySelectorAll("span.fade-in");
    expect(spans.length).toBeGreaterThanOrEqual(2);
    const text = Array.from(spans)
      .map((s) => s.textContent)
      .join("|");
    expect(text).toContain("Hello");
    expect(text).toContain("world");
  });

  it("auto-closes an unmatched inline backtick so it renders as code", () => {
    const { container } = render(<MarkdownMessage text="use `code" reveal="smooth" />);
    // closeOpenMarkers appends the missing backtick → react-markdown
    // emits an inline <code> element.
    expect(container.querySelector("code")).toBeTruthy();
    expect(container.textContent ?? "").toContain("code");
  });

  it("auto-closes an unmatched `**` so it renders as strong", () => {
    const { container } = render(<MarkdownMessage text="that **really" reveal="smooth" />);
    expect(container.querySelector("strong")).toBeTruthy();
    expect(container.textContent ?? "").toContain("really");
  });

  it("renders a complete fenced code block as a Shiki block", () => {
    const src = "before\n```js\nconst x = 1;\n```\nafter";
    const { container } = render(<MarkdownMessage text={src} reveal="smooth" />);
    expect(container.querySelector(".shiki-block")).toBeTruthy();
    expect(container.textContent ?? "").toContain("const x = 1;");
  });

  it("keeps a fenced block without a language in the code-block surface", async () => {
    const src = "before\n```\ncommand --flag\n```\nafter";
    const { container } = render(<MarkdownMessage text={src} reveal="smooth" />);
    await act(async () => Promise.resolve());

    expect(container.querySelector(".shiki-block")).toBeTruthy();
    expect(container.querySelector(".shiki-block pre")?.textContent).toBe("command --flag");
    expect(container.querySelector('.shiki-block button[aria-label="Copy code"]')).toBeTruthy();
  });

  it("renders a streaming-partial code block (no closer yet)", () => {
    // closeOpenMarkers should synthesise the closing fence so this
    // already shows up as a code block.
    const src = "```js\nconst x";
    const { container } = render(<MarkdownMessage text={src} reveal="smooth" />);
    expect(container.querySelector(".shiki-block")).toBeTruthy();
    expect(container.textContent ?? "").toContain("const x");
  });

  it("renders an SVG fence as an isolated image preview while keeping code copy", async () => {
    const src =
      '```svg\n<svg xmlns="http://www.w3.org/2000/svg"><circle cx="8" cy="8" r="6" /></svg>\n```';
    const { container } = render(<MarkdownMessage text={src} reveal="instant" />);
    await act(async () => Promise.resolve());

    const image = container.querySelector('img[alt="Image generated by the assistant"]');
    expect(image).toBeTruthy();
    expect(image!.getAttribute("src")).toMatch(/^data:image\/svg\+xml/);
    expect(container.querySelector("script")).toBeNull();
    expect(container.querySelector('.shiki-block button[aria-label="Copy code"]')).toBeTruthy();
    expect(container.querySelector(".shiki-body code")).toBeNull();
    expect(container.querySelector('.shiki-block[data-variant="preview"]')).toBeTruthy();
    expect(container.querySelector('.shiki-preview-body[tabindex="0"]')).toBeTruthy();
  });

  it("keeps HTML fences as inert, copyable source code", async () => {
    const src =
      '```html\n<!doctype html><html><body><script>parent.postMessage("ran", "*")</script></body></html>\n```';
    const { container } = render(<MarkdownMessage text={src} reveal="instant" />);
    await act(async () => Promise.resolve());

    expect(container.querySelector("iframe")).toBeNull();
    expect(container.querySelector(".shiki-block")?.textContent).toContain("parent.postMessage");
    expect(container.querySelector('.shiki-block button[aria-label="Copy code"]')).toBeTruthy();
  });

  it("does not fetch remote Markdown images in the restricted desktop surface", () => {
    const src = "![Tracking pixel](https://tracker.example/pixel.png)";
    const { container } = render(<MarkdownMessage text={src} reveal="instant" />);

    expect(container.querySelector('img[src^="https://tracker.example/"]')).toBeNull();
    const unavailable = container.querySelector<HTMLButtonElement>(
      'button[aria-label="Tracking pixel"]',
    );
    expect(unavailable).toBeTruthy();
    expect(unavailable?.disabled).toBe(true);
  });

  it("opens safe inline Markdown images through an accessible preview trigger", () => {
    const tinyPng =
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=";
    const { container } = render(
      <MarkdownMessage text={`![Build graph](${tinyPng})`} reveal="instant" />,
    );

    const trigger = container.querySelector<HTMLButtonElement>('button[aria-label="Build graph"]');
    expect(trigger).toBeTruthy();
    expect(trigger?.querySelector("img")?.getAttribute("loading")).toBe("lazy");
  });

  it("promotes image-only paragraphs into Codex wide and gallery media blocks", () => {
    const first =
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=";
    const second = "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==";
    const { container } = render(
      <MarkdownMessage
        text={`![Architecture](${first})\n\n![Before](${first}) ![After](${second})`}
        reveal="instant"
      />,
    );

    const wide = container.querySelector<HTMLParagraphElement>(
      'p[data-wide-markdown-block="true"]',
    );
    expect(wide?.querySelector('button[aria-label="Architecture"]')).toBeTruthy();

    const gallery = container.querySelector<HTMLParagraphElement>(
      'p[data-markdown-image-grid="true"]',
    );
    expect(gallery).toBeTruthy();
    expect(gallery?.querySelectorAll(":scope > button")).toHaveLength(2);
  });

  it("navigates between Markdown images inside one Codex preview gallery", () => {
    const first =
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=";
    const second = "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==";
    render(<MarkdownMessage text={`![Before](${first}) ![After](${second})`} reveal="instant" />);

    fireEvent.click(screen.getByRole("button", { name: "Before" }));
    expect(screen.getByRole("dialog", { name: "Before" })).toBeTruthy();
    fireEvent.click(screen.getByRole("button", { name: "Next image" }));
    expect(screen.getByRole("dialog", { name: "After" })).toBeTruthy();
  });

  it("keeps GFM tables semantic and exposes the Codex copy action", async () => {
    const src = "| Name | Count |\n|---|---:|\n| alpha | 12 |";
    const writeText = vi.fn().mockResolvedValue(undefined);
    const clipboardDescriptor = Object.getOwnPropertyDescriptor(navigator, "clipboard");
    Object.defineProperty(navigator, "clipboard", {
      configurable: true,
      value: { writeText },
    });
    try {
      const { container } = render(<MarkdownMessage text={src} reveal="smooth" />);
      const table = container.querySelector("table");
      expect(table).toBeTruthy();
      expect(container.querySelectorAll("td").length).toBe(2);

      const copy = container.querySelector<HTMLButtonElement>('button[aria-label="Copy table"]');
      expect(copy).toBeTruthy();
      fireEvent.click(copy!);
      await waitFor(() => expect(writeText).toHaveBeenCalledWith(src));
    } finally {
      if (clipboardDescriptor) {
        Object.defineProperty(navigator, "clipboard", clipboardDescriptor);
      } else {
        Reflect.deleteProperty(navigator, "clipboard");
      }
    }
  });

  it("marks directional and numeric table material like Codex", () => {
    const src = "| Name | Count |\n|---|---:|\n| alpha | 12 |";
    const { container } = render(<MarkdownMessage text={src} reveal="smooth" />);

    expect(container.querySelector("table")?.getAttribute("dir")).toBe("auto");
    expect(container.querySelector("td.md-table-cell-numeric")?.textContent).toBe("12");
  });

  it("renders markdown lists", () => {
    const src = "- one\n- two\n- three";
    const { container } = render(<MarkdownMessage text={src} reveal="smooth" />);
    expect(container.querySelector("ul")).toBeTruthy();
    expect(container.querySelectorAll("li").length).toBe(3);
  });

  it("marks directional prose and Han paragraphs like Codex", () => {
    const src = [
      "# عنوان",
      "",
      "中文第一段。",
      "",
      "中文第二段。",
      "",
      "- عنصر",
      "",
      "1. خطوة",
      "",
      "> اقتباس",
    ].join("\n");
    const { container } = render(<MarkdownMessage text={src} reveal="instant" />);

    expect(container.querySelector('h1[dir="auto"]')).toBeTruthy();
    expect(container.querySelectorAll('p[data-markdown-han-text="true"]')).toHaveLength(2);
    expect(container.querySelector('ul[dir="auto"]')).toBeTruthy();
    expect(container.querySelector('ol[dir="auto"]')).toBeTruthy();
    expect(container.querySelector('blockquote[dir="auto"]')).toBeTruthy();
  });

  it("isolates inline and fenced code as left-to-right inside bidirectional prose", async () => {
    const src =
      "تشغيل `npm run check -- --watch=false`\n\n```sh\nnpm run check -- --watch=false\n```";
    const { container } = render(<MarkdownMessage text={src} reveal="instant" />);
    await act(async () => Promise.resolve());

    expect.soft(container.querySelector("p > code")?.getAttribute("dir")).toBe("ltr");
    expect.soft(container.querySelector(".shiki-block")?.getAttribute("dir")).toBe("ltr");
  });

  it("drops fade-in wrappers for the instant reveal mode", () => {
    const { container } = render(<MarkdownMessage text="Hello world" reveal="instant" />);
    expect(container.querySelectorAll("span.fade-in").length).toBe(0);
    expect(container.textContent ?? "").toContain("Hello world");
  });

  it("uses the typewriter pipeline without layering word fades over it", () => {
    const { container } = render(<MarkdownMessage text="Hello world" reveal="typewriter" />);
    expect(container.querySelectorAll("span.fade-in")).toHaveLength(0);
    expect(container.textContent ?? "").toContain("Hello world");
  });

  it("renders model placeholders as literal text instead of unknown React elements", () => {
    const { container } = render(<MarkdownMessage text="ANGLE=<chosen>" reveal="instant" />);
    expect(container.textContent).toContain("ANGLE=<chosen>");
    expect(container.querySelector("chosen")).toBeNull();
  });

  it("keeps supported semantic raw HTML while rendering dangerous tags literally", () => {
    const { container } = render(
      <MarkdownMessage text={'value<sup>2</sup> <script>alert("x")</script>'} reveal="instant" />,
    );
    expect(container.querySelector("sup")?.textContent).toBe("2");
    expect(container.querySelector("script")).toBeNull();
    expect(container.textContent).toContain('<script>alert("x")</script>');
  });
});
