package model

import "time"

// Usage records the token consumption a single LLM request reported back.
// Every field is denominated in tokens; durations live on [RateLimit].
//
// The breakdown fields ([Usage.ReasoningTokens], [Usage.CacheReadInputTokens],
// [Usage.CacheWriteInputTokens]) are pointer-typed so callers can tell
// "provider reported zero" from "provider did not surface this dimension".
// Each breakdown field is a subset of [Usage.PromptTokens] or
// [Usage.CompletionTokens] — they are intentionally NOT added to
// [Usage.TotalTokens] to avoid double counting.
type Usage struct {
	// PromptTokens are tokens consumed by the input messages, including any
	// portions counted in CacheReadInputTokens and CacheWriteInputTokens.
	PromptTokens int64 `json:"prompt_tokens"`

	// CompletionTokens are tokens generated by the model. For reasoning
	// models (OpenAI o-series, DeepSeek-R1, Claude extended thinking) this
	// already includes any chain-of-thought tokens; ReasoningTokens carries
	// the breakdown subset.
	CompletionTokens int64 `json:"completion_tokens"`

	// ReasoningTokens is the chain-of-thought subset of CompletionTokens
	// when the provider exposes a breakdown (mirrors OpenAI's
	// completion_tokens_details.reasoning_tokens). nil means the provider
	// did not report this dimension — it does NOT imply zero reasoning.
	ReasoningTokens *int64 `json:"reasoning_tokens,omitempty"`

	// CacheReadInputTokens is the prompt-cache hit subset of PromptTokens
	// (Anthropic ephemeral cache, OpenAI cached inputs, ...). Billed at a
	// reduced rate. nil means the provider does not support prompt
	// caching or no cache hit occurred for this request.
	CacheReadInputTokens *int64 `json:"cache_read_input_tokens,omitempty"`

	// CacheWriteInputTokens is the prompt-cache miss subset that populated
	// the cache for future requests. Typically billed at a premium over
	// standard prompt tokens. nil means caching is unsupported or did not
	// fire for this request.
	CacheWriteInputTokens *int64 `json:"cache_write_input_tokens,omitempty"`

	// OriginalUsage is the raw provider-specific usage payload, kept so
	// callers can extract fields the framework does not surface yet.
	OriginalUsage any `json:"original_usage,omitempty"`
}

// TotalTokens reports prompt + completion tokens. Use it for cost
// calculations and quota tracking. Breakdown fields are excluded — they
// already overlap with prompt or completion counts.
func (u *Usage) TotalTokens() int64 {
	if u == nil {
		return 0
	}
	return u.PromptTokens + u.CompletionTokens
}

// HasReasoningTokens reports whether the provider surfaced a chain-of-
// thought breakdown for this request.
func (u *Usage) HasReasoningTokens() bool {
	return u != nil && u.ReasoningTokens != nil
}

// HasCacheReadInputTokens reports whether the provider surfaced a
// prompt-cache hit count for this request.
func (u *Usage) HasCacheReadInputTokens() bool {
	return u != nil && u.CacheReadInputTokens != nil
}

// HasCacheWriteInputTokens reports whether the provider surfaced a
// prompt-cache write count for this request.
func (u *Usage) HasCacheWriteInputTokens() bool {
	return u != nil && u.CacheWriteInputTokens != nil
}

// RateLimit holds the API-quota state a provider attached to the response,
// covering both per-request and per-token windows. All fields are
// best-effort: providers vary in which they populate, so callers should
// treat zero values as "unknown" rather than "exhausted".
type RateLimit struct {
	// RequestsLimit is the maximum requests allowed in the current window.
	RequestsLimit int64 `json:"requests_limit"`

	// RequestsRemaining is the request count still available in the window.
	RequestsRemaining int64 `json:"requests_remaining"`

	// RequestsReset is the time until the request quota resets.
	RequestsReset time.Duration `json:"requests_reset"`

	// TokensLimit is the maximum tokens allowed in the current window.
	TokensLimit int64 `json:"tokens_limit"`

	// TokensRemaining is the token count still available in the window.
	TokensRemaining int64 `json:"tokens_remaining"`

	// TokensReset is the time until the token quota resets.
	TokensReset time.Duration `json:"tokens_reset"`
}
