package sessionflow

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"slices"
	"strings"
	"time"

	"github.com/Tangerg/lynx/core/chat"

	conversationdomain "github.com/Tangerg/lynx/app2/runtime/domain/conversation"
	rundomain "github.com/Tangerg/lynx/app2/runtime/domain/run"
	"github.com/Tangerg/lynx/app2/runtime/domain/session"
	"github.com/Tangerg/lynx/app2/runtime/domain/transcript"
	"github.com/Tangerg/lynx/app2/runtime/domain/toolresult"
	"github.com/Tangerg/lynx/app2/runtime/protocol"
)

type materialRunFacts struct {
	Metrics protocol.RunMetrics `json:"metrics"`
	ContextTokens int64 `json:"contextTokens,omitempty"`
	Limits *protocol.RunLimits `json:"limits,omitempty"`
	Profile protocol.RunProtocolProfile `json:"profile"`
	EventOrdinal int `json:"eventOrdinal"`
}

func (service *Service) Snapshot(ctx context.Context, request protocol.GetSessionSnapshotRequest) (*protocol.SessionSnapshot,error) {
	material,err:=service.store.ReadSessionMaterial(ctx,session.ID(request.SessionID));if err!=nil{return nil,projectLookup(err)}
	runs:=make([]protocol.RunRef,0,len(material.Runs));included:=map[string]bool{}
	for _,record:=range material.Runs{if !request.IncludeDescendants&&record.Run.ParentRunID()!=""{continue};view,err:=presentMaterialRun(record);if err!=nil{return nil,err};runs=append(runs,*view);included[record.Run.ID()]=true}
	items:=make([]protocol.Item,0,len(material.Items));for _,record:=range material.Items{if !included[record.RunID]{continue};var item protocol.Item;if err:=json.Unmarshal(record.Body,&item);err!=nil{return nil,err};items=append(items,item)}
	interrupts:=make([]protocol.PendingInterruptSet,0,len(material.Interrupts));for _,set:=range material.Interrupts{if request.IncludeDescendants||included[set.RootRunID]{interrupts=append(interrupts,set)}}
	plan:=material.Plan
	return &protocol.SessionSnapshot{Items:items,Runs:runs,Interrupts:interrupts,Plan:&plan,Goal:material.Goal},nil
}

func (service *Service) Fork(ctx context.Context, request protocol.ForkSessionRequest) (*protocol.Session,error) {
	material,err:=service.store.ReadSessionMaterial(ctx,session.ID(request.SessionID));if err!=nil{return nil,projectLookup(err)}
	kept,err:=forkBoundary(material.Runs,request.FromRunID);if err!=nil{return nil,err}
	newSessionID,err:=service.ids.New("ses_");if err!=nil{return nil,err};now:=service.now().UTC();title:=request.Title;if strings.TrimSpace(title)==""{title=material.Session.Title()+" (fork)"}
	child,err:=session.New(session.Create{ID:session.ID(newSessionID),Title:title,Workspace:material.Session.Workspace(),Model:material.Session.Model(),Now:now});if err!=nil{return nil,err}
	runIDs,itemIDs:=map[string]string{},map[string]string{}
	for _,record:=range kept{id,err:=service.ids.New("run_");if err!=nil{return nil,err};runIDs[record.Run.ID()]=id}
	for _,record:=range material.Items{if runIDs[record.RunID]==""{continue};id,err:=service.ids.New("itm_");if err!=nil{return nil,err};itemIDs[record.ID]=id}
	runs:=make([]rundomain.Record,0,len(kept));for _,record:=range kept{value:=record.Run;restored,err:=rundomain.Rehydrate(rundomain.Restore{ID:runIDs[value.ID()],SessionID:newSessionID,ParentRunID:runIDs[value.ParentRunID()],RootRunID:runIDs[value.RootRunID()],SpawnedByItemID:itemIDs[value.SpawnedByItemID()],Status:value.Status(),Provider:value.Provider(),Model:value.Model(),Outcome:value.Outcome(),Detail:value.Detail(),CreatedAt:value.CreatedAt(),UpdatedAt:value.UpdatedAt(),FinishedAt:value.FinishedAt()});if err!=nil{return nil,err};runs=append(runs,rundomain.Record{Run:restored,Body:slices.Clone(record.Body)})}
	items:=make([]transcript.Record,0,len(itemIDs));for _,record:=range material.Items{newID:=itemIDs[record.ID];if newID==""{continue};var item protocol.Item;if err:=json.Unmarshal(record.Body,&item);err!=nil{return nil,err};item.ID=newID;item.RunID=runIDs[item.RunID];body,err:=json.Marshal(item);if err!=nil{return nil,err};items=append(items,transcript.Record{ID:newID,SessionID:newSessionID,RunID:item.RunID,Ordinal:record.Ordinal,Body:body,CreatedAt:record.CreatedAt})}
	messages:=make([]conversationdomain.Record,0,len(material.Messages));for _,source:=range material.Messages{newRunID:=runIDs[source.RunID];if newRunID==""{continue};messages=append(messages,conversationdomain.Record{SessionID:newSessionID,RunID:newRunID,Ordinal:len(messages),Body:slices.Clone(source.Body)})}
	var plan *protocol.Plan;if material.Plan.Revision>0||len(material.Plan.Steps)>0{value:=material.Plan;value.SessionID=newSessionID;value.Revision=1;value.UpdatedAt=now;value.Steps=slices.Clone(value.Steps);plan=&value}
	toolResults:=make([]toolresult.Record,0);for _,source:=range material.ToolResults{newItemID:=itemIDs[source.ItemID];if newItemID==""{continue};source.SessionID=newSessionID;source.ItemID=newItemID;if err:=source.Validate();err!=nil{return nil,err};toolResults=append(toolResults,source)}
	if err:=service.store.CreateSessionFork(ctx,ForkWrite{Session:child,Runs:runs,Items:items,Messages:messages,Plan:plan,ToolResults:toolResults});err!=nil{return nil,err}
	resolved,err:=service.workspaces.Resolve(ctx,child.Workspace().Path());if err!=nil{return nil,err};return present(child,resolved,protocol.SessionStatusIdle),nil
}

func forkBoundary(records []rundomain.Record,from string)([]rundomain.Record,error){roots:=make([]rundomain.Record,0);byRoot:=map[string][]rundomain.Record{};for _,record:=range records{if record.Run.Status()!=rundomain.Finished{continue};if record.Run.ParentRunID()==""{roots=append(roots,record);byRoot[record.Run.ID()]=append(byRoot[record.Run.ID()],record)}else{byRoot[record.Run.RootRunID()]=append(byRoot[record.Run.RootRunID()],record)}};slices.SortFunc(roots,func(a,b rundomain.Record)int{return a.Run.CreatedAt().Compare(b.Run.CreatedAt())});if from==""&&len(roots)>0{from=roots[len(roots)-1].Run.ID()};result:=make([]rundomain.Record,0);found:=from=="";for _,root:=range roots{group:=byRoot[root.Run.ID()];slices.SortFunc(group,func(a,b rundomain.Record)int{return a.Run.CreatedAt().Compare(b.Run.CreatedAt())});result=append(result,group...);if root.Run.ID()==from{found=true;break}};if !found{return nil,protocol.ErrRunNotFound};return result,nil}

func (service *Service) Rollback(ctx context.Context, request protocol.RollbackSessionRequest) (*protocol.RollbackSessionResponse,error) {
	material,err:=service.store.ReadSessionMaterial(ctx,session.ID(request.SessionID));if err!=nil{return nil,projectLookup(err)}
	for _,record:=range material.Runs{if record.Run.Status()!=rundomain.Finished{return nil,protocol.ErrSessionBusy}}
	roots:=make([]rundomain.Record,0);for _,record:=range material.Runs{if record.Run.ParentRunID()==""{roots=append(roots,record)}};slices.SortFunc(roots,func(a,b rundomain.Record)int{return a.Run.CreatedAt().Compare(b.Run.CreatedAt())});keep:=-1;if request.ToRunID!=""{keep=slices.IndexFunc(roots,func(record rundomain.Record)bool{return record.Run.ID()==request.ToRunID});if keep<0{return nil,protocol.ErrRunNotFound}}
	restore:=request.RestoreType;if restore==""{restore=protocol.RestoreHistory};if restore!=protocol.RestoreHistory&&restore!=protocol.RestoreFiles&&restore!=protocol.RestoreBoth{return nil,fmt.Errorf("%w: invalid restoreType",protocol.ErrInvalidParams)};if (restore==protocol.RestoreFiles||restore==protocol.RestoreBoth)&&request.ToRunID==""{return nil,fmt.Errorf("%w: file restore requires toRunId",protocol.ErrInvalidParams)}
	if restore==protocol.RestoreFiles||restore==protocol.RestoreBoth{if err:=service.checkpoints.Restore(ctx,request.SessionID,material.Session.Workspace().Path(),request.ToRunID);err!=nil{return nil,fmt.Errorf("%w: %v",protocol.ErrCheckpointUnavailable,err)}}
	dropRoots:=roots[keep+1:];dropped:=make([]protocol.DroppedRun,0);dropIDs:=make([]string,0,len(dropRoots));byRunItems:=map[string][]protocol.Item{};for _,record:=range material.Items{var item protocol.Item;if json.Unmarshal(record.Body,&item)==nil{byRunItems[record.RunID]=append(byRunItems[record.RunID],item)}}
	for _,root:=range dropRoots{dropIDs=append(dropIDs,root.Run.ID());for _,record:=range material.Runs{if record.Run.ID()!=root.Run.ID()&&record.Run.RootRunID()!=root.Run.ID(){continue};view,err:=presentMaterialRun(record);if err!=nil{return nil,err};value:=protocol.DroppedRun{Run:view.RunSummary};for _,item:=range byRunItems[record.Run.ID()]{if item.Type==protocol.ItemTypeUserMessage{value.UserInput=slices.Clone(item.Content);break}};dropped=append(dropped,value)}}
	if restore==protocol.RestoreFiles{resolved,resolveErr:=service.workspaces.Resolve(ctx,material.Session.Workspace().Path());if resolveErr!=nil{return nil,resolveErr};return &protocol.RollbackSessionResponse{Session:present(material.Session,resolved,protocol.SessionStatusIdle),DroppedRuns:[]protocol.DroppedRun{}},nil}
	plan:=material.Plan;if keep<0{plan=protocol.Plan{SessionID:request.SessionID,Revision:material.Plan.Revision+1,Steps:[]protocol.PlanStep{},UpdatedAt:service.now().UTC()}}
	updated,err:=service.store.RollbackSessionHistory(ctx,RollbackWrite{SessionID:session.ID(request.SessionID),DropRootRunIDs:dropIDs,Plan:&plan,Now:service.now().UTC()});if err!=nil{return nil,err};resolved,err:=service.workspaces.Resolve(ctx,updated.Workspace().Path());if err!=nil{return nil,err};return &protocol.RollbackSessionResponse{Session:present(updated,resolved,protocol.SessionStatusIdle),DroppedRuns:dropped},nil
}

func (service *Service) Export(ctx context.Context, request protocol.ExportSessionRequest) (*protocol.ExportSessionResponse,error) {
	material,err:=service.store.ReadSessionMaterial(ctx,session.ID(request.SessionID));if err!=nil{return nil,projectLookup(err)};for _,run:=range material.Runs{if run.Run.Status()!=rundomain.Finished{return nil,protocol.ErrSessionBusy}};if len(material.Interrupts)>0{return nil,protocol.ErrSessionBusy}
	format:=request.Format;if format==""{format=protocol.ExportFormatJSON};if format==protocol.ExportFormatMarkdown{return &protocol.ExportSessionResponse{Format:format,Markdown:renderMarkdown(material)},nil};if format!=protocol.ExportFormatJSON{return nil,fmt.Errorf("%w: unsupported export format",protocol.ErrInvalidParams)}
	artifact:=protocol.SessionArtifact{Version:protocol.SessionArtifactVersion,Session:protocol.ArtifactSession{ID:material.Session.ID().String(),Title:material.Session.Title(),Workspace:protocol.WorkspaceRef{Path:material.Session.Workspace().Path()},Model:material.Session.Model(),CreatedAt:material.Session.CreatedAt(),UpdatedAt:material.Session.UpdatedAt(),Favorite:material.Session.Favorite()},Messages:make([]json.RawMessage,0,len(material.Messages)),ToolResults:make([]protocol.ArtifactToolResult,0,len(material.ToolResults)),Plan:slices.Clone(material.Plan.Steps)}
	for _,message:=range material.Messages{artifact.Messages=append(artifact.Messages,json.RawMessage(slices.Clone(message.Body)))}
	for _,result:=range material.ToolResults{artifact.ToolResults=append(artifact.ToolResults,protocol.ArtifactToolResult{ID:result.ID,ItemID:result.ItemID,ToolName:result.ToolName,Preview:result.Preview,Body:result.Body,CreatedAt:result.CreatedAt})}
	for _,record:=range material.Runs{view,err:=presentMaterialRun(record);if err!=nil{return nil,err};facts,err:=decodeMaterialFacts(record.Body);if err!=nil{return nil,err};metrics:=protocol.ArtifactRunMetrics{Steps:facts.Metrics.Steps,ActiveDurationMillis:facts.Metrics.ActiveDurationMillis};if facts.Metrics.Usage!=nil{var usage protocol.ArtifactUsage;if err:=convertJSON(facts.Metrics.Usage,&usage);err!=nil{return nil,err};metrics.Usage=&usage};var limits *protocol.ArtifactRunLimits;if facts.Limits!=nil{limits=&protocol.ArtifactRunLimits{MaxTotalTokens:facts.Limits.MaxTotalTokens,MaxSteps:facts.Limits.MaxSteps,MaxBudgetUSD:facts.Limits.MaxBudgetUSD}};var runProfile *protocol.RunProtocolProfile;if record.Run.ParentRunID()==""{profile:=facts.Profile;runProfile=&profile};artifact.Runs=append(artifact.Runs,protocol.ArtifactRun{ID:view.ID,SessionID:view.SessionID,SpawnedByItemID:view.SpawnedByItemID,ParentRunID:view.ParentRunID,RootRunID:view.RootRunID,Provider:view.Provider,Model:view.Model,Limits:limits,Metrics:metrics,ContextTokens:facts.ContextTokens,ProtocolProfile:runProfile,Outcome:artifactOutcome(view),CreatedAt:view.CreatedAt,FinishedAt:view.FinishedAt,UpdatedAt:record.Run.UpdatedAt()})}
	for _,record:=range material.Items{var item protocol.Item;if err:=json.Unmarshal(record.Body,&item);err!=nil{return nil,err};var portable protocol.ArtifactItem;if err:=convertJSON(item,&portable);err!=nil{return nil,err};artifact.Items=append(artifact.Items,portable)}
	return &protocol.ExportSessionResponse{Format:format,Artifact:&artifact},nil
}

func (service *Service) Import(ctx context.Context, request protocol.ImportSessionRequest) (*protocol.ImportSessionResponse,error) {
	artifact:=request.Artifact;if artifact.Version!=protocol.SessionArtifactVersion{return nil,fmt.Errorf("%w: unsupported artifact version %d",protocol.ErrInvalidParams,artifact.Version)};if err:=artifact.ValidateWire();err!=nil{return nil,fmt.Errorf("%w: %v",protocol.ErrInvalidParams,err)}
	resolved,err:=service.workspaces.Resolve(ctx,artifact.Session.Workspace.Path);if err!=nil||!resolved.Available{return nil,protocol.ErrWorkspaceUnavailable};workspace,err:=session.NewWorkspace(resolved.Workspace.Path());if err!=nil{return nil,err};now:=service.now().UTC();created:=artifact.Session.CreatedAt;if created.IsZero(){created=now};updated:=artifact.Session.UpdatedAt;if updated.Before(created){updated=created};value,err:=session.Rehydrate(session.Restore{ID:session.ID(artifact.Session.ID),Title:artifact.Session.Title,Workspace:workspace,Model:artifact.Session.Model,Favorite:artifact.Session.Favorite,Revision:1,CreatedAt:created,UpdatedAt:updated});if err!=nil{return nil,fmt.Errorf("%w: %v",protocol.ErrInvalidParams,err)}
	material:=Material{Session:value,Plan:protocol.Plan{SessionID:value.ID().String(),Steps:slices.Clone(artifact.Plan)}};if len(artifact.Plan)>0{material.Plan.Revision=1;material.Plan.UpdatedAt=now}
	seenRuns:=map[string]bool{};for _,portable:=range artifact.Runs{if portable.SessionID!=artifact.Session.ID||seenRuns[portable.ID]{return nil,fmt.Errorf("%w: run identity closure is invalid",protocol.ErrInvalidParams)};seenRuns[portable.ID]=true;outcome:=rundomain.Outcome(portable.Outcome.Type);detail:=portable.Outcome.Detail;if portable.Outcome.Error!=nil{detail=portable.Outcome.Error.Detail};run,err:=rundomain.Rehydrate(rundomain.Restore{ID:portable.ID,SessionID:artifact.Session.ID,ParentRunID:portable.ParentRunID,RootRunID:portable.RootRunID,SpawnedByItemID:portable.SpawnedByItemID,Status:rundomain.Finished,Provider:portable.Provider,Model:portable.Model,Outcome:outcome,Detail:detail,CreatedAt:portable.CreatedAt,UpdatedAt:portable.UpdatedAt,FinishedAt:portable.FinishedAt});if err!=nil{return nil,fmt.Errorf("%w: %v",protocol.ErrInvalidParams,err)};facts:=materialRunFacts{Metrics:protocol.RunMetrics{Steps:portable.Metrics.Steps,ActiveDurationMillis:portable.Metrics.ActiveDurationMillis},ContextTokens:portable.ContextTokens};if portable.Metrics.Usage!=nil{var usage protocol.Usage;if err:=convertJSON(portable.Metrics.Usage,&usage);err!=nil{return nil,err};facts.Metrics.Usage=&usage};if portable.Limits!=nil{facts.Limits=&protocol.RunLimits{MaxTotalTokens:portable.Limits.MaxTotalTokens,MaxSteps:portable.Limits.MaxSteps,MaxBudgetUSD:portable.Limits.MaxBudgetUSD}};if portable.ProtocolProfile!=nil{facts.Profile=*portable.ProtocolProfile};body,_:=json.Marshal(facts);material.Runs=append(material.Runs,rundomain.Record{Run:run,Body:body})}
	ordinals:=map[string]int{};seenItems:=map[string]bool{};userRunIDs:=make([]string,0);for _,portable:=range artifact.Items{if !seenRuns[portable.RunID]||seenItems[portable.ID]{return nil,fmt.Errorf("%w: item identity closure is invalid",protocol.ErrInvalidParams)};seenItems[portable.ID]=true;var item protocol.Item;if err:=convertJSON(portable,&item);err!=nil{return nil,err};body,_:=json.Marshal(item);material.Items=append(material.Items,transcript.Record{ID:item.ID,SessionID:artifact.Session.ID,RunID:item.RunID,Ordinal:ordinals[item.RunID],Body:body,CreatedAt:itemOccurrence(item)});ordinals[item.RunID]++;if item.Type==protocol.ItemTypeUserMessage{userRunIDs=append(userRunIDs,item.RunID)}}
	material.Messages,err=importConversationMessages(artifact.Session.ID,artifact.Messages,userRunIDs);if err!=nil{return nil,err}
	seenResults:=map[string]bool{};for _,portable:=range artifact.ToolResults{if !seenItems[portable.ItemID]||seenResults[portable.ID]{return nil,fmt.Errorf("%w: tool result identity closure is invalid",protocol.ErrInvalidParams)};record:=toolresult.Record{ID:portable.ID,SessionID:artifact.Session.ID,ItemID:portable.ItemID,ToolName:portable.ToolName,Preview:portable.Preview,Body:portable.Body,CreatedAt:portable.CreatedAt};if err:=record.Validate();err!=nil{return nil,fmt.Errorf("%w: %v",protocol.ErrInvalidParams,err)};seenResults[record.ID]=true;material.ToolResults=append(material.ToolResults,record)}
	if err:=service.store.ReplaceSessionMaterial(ctx,ImportWrite{Material:material});err!=nil{return nil,err};presented:=present(value,resolved,protocol.SessionStatusIdle);return &protocol.ImportSessionResponse{Session:presented},nil
}

func presentMaterialRun(record rundomain.Record)(*protocol.RunRef,error){facts,err:=decodeMaterialFacts(record.Body);if err!=nil{return nil,err};value:=record.Run;summary:=protocol.RunSummary{ID:value.ID(),SessionID:value.SessionID(),SpawnedByItemID:value.SpawnedByItemID(),ParentRunID:value.ParentRunID(),RootRunID:value.RootRunID(),Model:value.Model(),Provider:value.Provider(),Status:protocol.RunStatus(value.Status()),CreatedAt:value.CreatedAt(),FinishedAt:value.FinishedAt()};if value.Status()==rundomain.Finished{summary.Outcome=&protocol.RunOutcome{Type:protocol.RunOutcomeType(value.Outcome())};if value.Outcome()==rundomain.Failed{summary.Outcome.Error=&protocol.ProblemData{Type:protocol.ProblemInternalError,Detail:value.Detail()}}else{summary.Outcome.Detail=value.Detail()}};return &protocol.RunRef{RunSummary:summary,ActiveSegmentID:value.ActiveSegmentID(),Metrics:facts.Metrics,ContextTokens:facts.ContextTokens,Limits:facts.Limits,ProtocolProfile:facts.Profile},nil}
func decodeMaterialFacts(body []byte)(materialRunFacts,error){var facts materialRunFacts;if err:=json.Unmarshal(body,&facts);err!=nil{return facts,fmt.Errorf("sessionflow: decode run facts: %w",err)};return facts,nil}
func artifactOutcome(value *protocol.RunRef)protocol.ArtifactOutcome{if value.Outcome==nil{return protocol.ArtifactOutcome{}};out:=protocol.ArtifactOutcome{Type:protocol.ArtifactOutcomeType(value.Outcome.Type),Detail:value.Outcome.Detail};if value.Outcome.Error!=nil{out.Error=&protocol.ArtifactProblem{Type:protocol.ArtifactProblemType(value.Outcome.Error.Type),Detail:value.Outcome.Error.Detail,DocURL:value.Outcome.Error.DocURL,RetryAfterSeconds:value.Outcome.Error.RetryAfterSeconds}};return out}
func convertJSON(source,target any)error{data,err:=json.Marshal(source);if err!=nil{return err};return json.Unmarshal(data,target)}
func importConversationMessages(sessionID string,raw []json.RawMessage,userRunIDs []string)([]conversationdomain.Record,error){
	messages:=make([]conversationdomain.Record,0,len(raw));userIndex:=0;currentRunID:="";if len(userRunIDs)>0{currentRunID=userRunIDs[0]}
	for ordinal,body:=range raw{var message chat.Message;if err:=json.Unmarshal(body,&message);err!=nil{return nil,fmt.Errorf("%w: conversation message %d: %v",protocol.ErrInvalidParams,ordinal,err)};if message.Role==chat.RoleUser{if userIndex>=len(userRunIDs){return nil,fmt.Errorf("%w: conversation has more user messages than transcript",protocol.ErrInvalidParams)};currentRunID=userRunIDs[userIndex];userIndex++}else if currentRunID==""{return nil,fmt.Errorf("%w: conversation starts without a user run",protocol.ErrInvalidParams)};messages=append(messages,conversationdomain.Record{SessionID:sessionID,RunID:currentRunID,Ordinal:ordinal,Body:slices.Clone(body)})}
	if userIndex!=len(userRunIDs){return nil,fmt.Errorf("%w: conversation and transcript user messages disagree",protocol.ErrInvalidParams)}
	return messages,nil
}
func itemOccurrence(item protocol.Item)time.Time{if !item.CreatedAt.IsZero(){return item.CreatedAt};return item.StartedAt}
func renderMarkdown(material Material)string{var builder strings.Builder;fmt.Fprintf(&builder,"# %s\n\n- workspace: `%s`\n\n",material.Session.Title(),material.Session.Workspace().Path());for _,record:=range material.Items{var item protocol.Item;if json.Unmarshal(record.Body,&item)!=nil{continue};switch item.Type{case protocol.ItemTypeUserMessage:builder.WriteString("## User\n\n");builder.WriteString(contentText(item));builder.WriteString("\n\n");case protocol.ItemTypeAgentMessage:builder.WriteString("## Assistant\n\n");builder.WriteString(contentText(item));builder.WriteString("\n\n");case protocol.ItemTypeToolCall:if item.Tool!=nil{fmt.Fprintf(&builder,"→ **tool** `%s`\n\n",item.Tool.Name)}}};return strings.TrimRight(builder.String(),"\n")+"\n"}
func contentText(item protocol.Item)string{parts:=make([]string,0,len(item.Content));for _,block:=range item.Content{if block.Type==protocol.ContentBlockText{parts=append(parts,block.Text)}else{parts=append(parts,"[image]")}};if item.Text!=""{parts=append(parts,item.Text)};return strings.Join(parts,"\n")}
