/* Code generated by contractgen. DO NOT EDIT. */

import {
  assertDiscoverResponse,
  isDiscoverResponse,
  protocolVersion,
  type DiscoverResponse,
  type RequestMeta,
  type RuntimeMethods,
} from "./wire.generated.js";

export interface RuntimeConnection {
  endpoint: string;
  localToken: string;
  instanceId: string;
  protocolVersion: typeof protocolVersion;
  idempotencyNamespace: string;
  generation: number;
}

export class LyraRPCError extends Error {
  readonly code: number;
  readonly data: unknown;

  constructor(code: number, message: string, data: unknown) {
    super(message);
    this.name = "LyraRPCError";
    this.code = code;
    this.data = data;
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

const responseValidators: {
  [Name in keyof RuntimeMethods]: (value: unknown) => value is RuntimeMethods[Name]["result"];
} = {
  "runtime.discover": isDiscoverResponse,
};

export class LyraClient {
  readonly #connection: RuntimeConnection;
  readonly #rpcURL: URL;

  constructor(connection: RuntimeConnection) {
    if (connection.protocolVersion !== protocolVersion) {
      throw new TypeError("Unsupported Runtime protocol " + connection.protocolVersion);
    }
    const endpoint = new URL(connection.endpoint);
    if (endpoint.protocol !== "http:" || endpoint.username !== "" || endpoint.password !== "") {
      throw new TypeError("Local Runtime endpoint must be an uncredentialed HTTP URL");
    }
    if (!["127.0.0.1", "[::1]"].includes(endpoint.hostname) || endpoint.pathname !== "/" || endpoint.search !== "" || endpoint.hash !== "") {
      throw new TypeError("Local Runtime endpoint must be an origin-only loopback URL");
    }
    this.#connection = { ...connection };
    this.#rpcURL = new URL("/v2/rpc", endpoint);
  }

  async discover(meta: RequestMeta = {}, signal?: AbortSignal): Promise<DiscoverResponse> {
    const response = await this.call("runtime.discover", {}, meta, signal);
    assertDiscoverResponse(response);
    return response;
  }

  async call<Name extends keyof RuntimeMethods>(
    method: Name,
    params: RuntimeMethods[Name]["params"],
    meta: RequestMeta = {},
    signal?: AbortSignal,
  ): Promise<RuntimeMethods[Name]["result"]> {
    const id = crypto.randomUUID();
    const requestParams = Object.keys(meta).length === 0 ? params : { ...params, _meta: meta };
    const response = await fetch(this.#rpcURL, {
      method: "POST",
      headers: {
        Authorization: "Bearer " + this.#connection.localToken,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ jsonrpc: "2.0", id, method, params: requestParams }),
      signal,
    });
    if (!response.ok || !response.headers.get("Content-Type")?.startsWith("application/json")) {
      throw new Error("Runtime transport failed with HTTP " + response.status);
    }
    const envelope: unknown = await response.json();
    if (!isRecord(envelope) || envelope.jsonrpc !== "2.0" || envelope.id !== id) {
      throw new TypeError("Runtime returned an invalid JSON-RPC envelope");
    }
    const keys = Object.keys(envelope);
    const hasResult = "result" in envelope;
    const hasError = "error" in envelope;
    if (hasResult === hasError || keys.some((key) => !["jsonrpc", "id", "result", "error"].includes(key))) {
      throw new TypeError("Runtime returned an ambiguous JSON-RPC envelope");
    }
    if (hasError) {
      const failure = envelope.error;
      if (!isRecord(failure) || !Number.isInteger(failure.code) || typeof failure.message !== "string") {
        throw new TypeError("Runtime returned an invalid JSON-RPC error");
      }
      throw new LyraRPCError(failure.code as number, failure.message, failure.data);
    }
    const validator = responseValidators[method];
    if (!validator(envelope.result)) {
      throw new TypeError("Runtime returned an invalid " + String(method) + " result");
    }
    return envelope.result;
  }
}
