package main

import (
	"fmt"
	"strings"
)

// reference renders the human-readable API reference (contract §11.3).
//
// It is generated from the same registry the dispatcher routes off, which is the
// only way a reference stays true: a hand-written method table is a second
// source, and the six lies A1 had to fix in the protocol docs were exactly that.
// This file therefore documents nothing a reader must trust — it restates what
// the code does, and the drift gate proves it still does.
func reference(m manifest) string {
	var b strings.Builder
	b.WriteString("# Lyra Runtime — generated API reference\n\n")
	b.WriteString("> **Generated by `go generate ./...` — do not edit.** Every row is read from the\n")
	b.WriteString("> Contract Registry the dispatcher routes off, so this file cannot describe a\n")
	b.WriteString("> method the runtime does not serve. Prose, rationale and wire examples live in\n")
	b.WriteString("> `app/runtime/doc/{API,TRANSPORT,AUX_API}.md`; this is the mechanical index.\n\n")
	fmt.Fprintf(&b, "Protocol `%s` · %d methods\n\n", m.ProtocolVersion, len(m.Methods))

	b.WriteString("## Methods\n\n")
	b.WriteString("| method | operation | response | retry | pagination | materializes | features | documented errors |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- | --- | --- |\n")
	for _, method := range m.Methods {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s | %s | %s |\n",
			method.Name, method.Operation, method.Kind, method.Idempotency,
			method.Pagination, code(method.Materializes), code(method.Features), code(method.Errors))
	}

	b.WriteString("\n## HTTP endpoints\n\n")
	b.WriteString("| name | kind | method | path | authentication | response statuses | response |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- | --- |\n")
	for _, endpoint := range m.HTTPEndpoints {
		response := "—"
		if endpoint.Response != nil {
			response = "`" + endpoint.Response.Ref + "`"
		}
		statuses := make([]string, 0, len(endpoint.ResponseStatuses))
		for _, status := range endpoint.ResponseStatuses {
			statuses = append(statuses, fmt.Sprint(status))
		}
		fmt.Fprintf(&b, "| `%s` | %s | `%s` | `%s` | %s | %s | %s |\n",
			endpoint.Name, endpoint.Kind, endpoint.Method, endpoint.Path,
			endpoint.Authentication, strings.Join(statuses, ", "), response)
	}

	b.WriteString("\n## Streaming methods\n\n")
	b.WriteString("A client reads this set instead of hardcoding names: these calls answer with\n")
	b.WriteString("their own event stream (doc/TRANSPORT.md §6.4).\n\n")
	for _, name := range m.StreamingMethods {
		fmt.Fprintf(&b, "- `%s`\n", name)
	}

	b.WriteString("\n## Run event reliability\n\n")
	b.WriteString("Authoritativeness and replayability are protocol facts of the event type, not\n")
	b.WriteString("sender-controlled flags. Discard every non-authoritative event and the final\n")
	b.WriteString("state is still correct (doc/API.md §5.2).\n\n")
	b.WriteString("| event | authoritative | replayed on reconnect |\n| --- | --- | --- |\n")
	for _, event := range m.RunEventPolicy {
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", event.Type, yes(event.Authoritative), yes(event.Replayable))
	}

	b.WriteString("\n## Discriminated unions\n\n")
	b.WriteString("Discriminated by `type` with no exceptions (doc/API.md §2.1). A field belongs to at\n")
	b.WriteString("least one variant; the registry refuses a union where one does not. A union may\n")
	b.WriteString("publish one namespaced pattern branch without weakening first-party tags.\n\n")
	for _, union := range m.Unions {
		fmt.Fprintf(&b, "### `%s`\n\n", union.Type)
		if len(union.Forbidden) > 0 {
			fmt.Fprintf(&b, "Forbidden on every variant: %s.\n\n", code(union.Forbidden))
		}
		b.WriteString("| tag | required | optional |\n| --- | --- | --- |\n")
		for _, variant := range union.Variants {
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", variant.Tag, code(variant.Required), code(variant.Optional))
		}
		if pattern := union.PatternVariant; pattern != nil {
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", pattern.TagPattern, code(pattern.Required), code(pattern.Optional))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Value constraints\n\n")
	b.WriteString("These rules are generated into the Go boundary validator, JSON Schema and\n")
	b.WriteString("TypeScript validator from this single registry projection.\n\n")
	b.WriteString("| shape | field | constraint |\n| --- | --- | --- |\n")
	for _, entry := range m.ValueConstraints {
		for _, rule := range entry.Rules {
			fmt.Fprintf(&b, "| `%s` | `%s` | `%s` |\n", entry.Type, rule.Field, rule.Constraint)
		}
	}

	b.WriteString("\n## Capability gating\n\n")
	b.WriteString("A rule with a condition gates one OPTION of a method; the method itself stays\n")
	b.WriteString("available. Refusal is `capability_not_negotiated` — never a silent downgrade.\n\n")
	b.WriteString("| method | when | requires |\n| --- | --- | --- |\n")
	for _, entry := range m.CapabilityPolicy {
		for _, rule := range entry.Rules {
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", entry.Method, when(rule.When), code(rule.Requires))
		}
	}

	b.WriteString("\n## System invariants\n\n")
	b.WriteString("Cross-resource facts and the transactions responsible for them. Named, not\n")
	b.WriteString("enforced by a validator — a frame-local check cannot see the whole system.\n\n")
	for _, invariant := range m.SystemInvariants {
		fmt.Fprintf(&b, "- **`%s`** — %s\n  - maintained by: %s\n", invariant.Key, invariant.Why, code(invariant.Boundaries))
	}
	return b.String()
}

func code(values []string) string {
	if len(values) == 0 {
		return "—"
	}
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, "`"+value+"`")
	}
	return strings.Join(quoted, ", ")
}

func when(conditions []conditionRow) string {
	if len(conditions) == 0 {
		return "always"
	}
	parts := make([]string, 0, len(conditions))
	for _, condition := range conditions {
		if condition.Operator == "equals" {
			parts = append(parts, fmt.Sprintf("`%s` == `%s`", condition.Field, condition.Value))
			continue
		}
		parts = append(parts, fmt.Sprintf("`%s` present", condition.Field))
	}
	return strings.Join(parts, " and ")
}

func yes(v bool) string {
	if v {
		return "yes"
	}
	return "no"
}
