package main

import (
	"fmt"
	"maps"
	"reflect"
	"slices"
	"strconv"
	"strings"

	"github.com/Tangerg/lynx/app/runtime/internal/delivery/dispatch"
	"github.com/Tangerg/lynx/app/runtime/internal/delivery/protocol"
)

// The method surface, as TypeScript reads it: which methods exist, what each one
// carries, and what has to be negotiated before one will run.
//
// This is the half of contract §11.3's fifth artifact class that has a reader. Go
// needs no generated method constants — `server` and `dispatch` are the same ring
// and the Registry itself is their shared source, so a second table of
// `MethodRunsStart = "runs.start"` that dispatch does not consume would BE the
// second author it was meant to remove. TypeScript cannot read the Registry at all,
// and before this it restated every one of those facts by hand: 83 method-name
// literals, dozens of result types, and a parallel union of the nineteen capability
// keys.
//
// What is NOT generated is how this client calls. §12 keeps the wire narrow and
// gives the SDK the friendly handles, so the frame TYPES land here and `methods.ts`
// composes them with its own transport concerns (abort signal, idempotency key). A
// generated wrapper per method would be a third layer that only forwards.
const tsMethodsFileName = "wire.methods.generated.ts"

type methodsEmitter struct {
	tsTypes
	out strings.Builder

	// imported collects the published shapes the module names, so its import list is
	// exactly those — the frontend compiles with noUnusedLocals.
	imported map[string]bool
}

func newWireMethods(registry *dispatch.Registry, set *schemaSet) string {
	emitter := &methodsEmitter{tsTypes: tsTypes{set: set}, imported: make(map[string]bool)}
	metas := registry.Metas()

	// Rendered first: the shapes it names decide the import list.
	shapes := emitter.shapes(metas)

	emitter.header()
	emitter.imports()
	emitter.features()
	emitter.names(metas)
	emitter.policy(metas)
	emitter.out.WriteString(shapes)
	emitter.helpers()
	return emitter.out.String()
}

// policy emits the capability rules the SDK preflights against what the server
// advertised. Contract §11.1 names three consumers of these rules — the dispatcher,
// discovery and the SDK — and forbids any of them keeping a second switch. Typing
// the table with WireFeature also makes a rule naming an unpublished key a compile
// error on this side, not only in Go.
func (e *methodsEmitter) policy(metas []dispatch.MethodMeta) {
	e.line("/** One condition on the request that decides whether a rule applies. */")
	e.line("export interface WireCapabilityCondition {")
	e.line("  field: string;")
	e.line("  operator: \"present\" | \"equals\";")
	e.line("  value?: string;")
	e.line("}")
	e.line("")
	e.line("/**")
	e.line(" * What a method needs negotiated. An absent `when` gates the whole method; a")
	e.line(" * condition gates only the requests that match it.")
	e.line(" */")
	e.line("export interface WireCapabilityRule {")
	e.line("  when?: readonly WireCapabilityCondition[];")
	e.line("  requires: readonly WireFeature[];")
	e.line("}")
	e.line("")
	e.line("export const WIRE_CAPABILITY_POLICY: {")
	e.line("  readonly [M in WireMethodName]?: readonly WireCapabilityRule[];")
	e.line("} = {")
	for _, meta := range metas {
		if len(meta.CapabilityRules) == 0 {
			continue
		}
		e.line("  %s: [", strconv.Quote(meta.Name))
		for _, rule := range meta.CapabilityRules {
			e.line("    { %s },", renderRule(rule))
		}
		e.line("  ],")
	}
	e.line("};")
	e.line("")
}

// renderRule writes one capability rule's members.
func renderRule(rule dispatch.CapabilityRule) string {
	var members []string
	if len(rule.When) != 0 {
		conditions := make([]string, 0, len(rule.When))
		for _, condition := range rule.When {
			parts := []string{
				"field: " + strconv.Quote(condition.Field),
				"operator: " + strconv.Quote(condition.Operator.String()),
			}
			if condition.Value != "" {
				parts = append(parts, "value: "+strconv.Quote(condition.Value))
			}
			conditions = append(conditions, "{ "+strings.Join(parts, ", ")+" }")
		}
		members = append(members, "when: ["+strings.Join(conditions, ", ")+"]")
	}
	members = append(members, "requires: ["+strings.Join(quoteAll(rule.Requires), ", ")+"]")
	return strings.Join(members, ", ")
}

func (e *methodsEmitter) header() {
	e.line("// Code generated by cmd/contractgen. DO NOT EDIT.")
	e.line("//")
	e.line("// The method surface of the Lyra Runtime Protocol: which methods exist, what each")
	e.line("// one carries, and what has to be negotiated before one will run.")
	e.line("//")
	e.line("// The SDK in methods.ts composes these with its own transport concerns. This file")
	e.line("// holds no policy of its own — every fact in it is read from the Contract Registry.")
	e.line("")
}

func (e *methodsEmitter) imports() {
	names := slices.Sorted(maps.Keys(e.imported))
	if len(names) == 0 {
		return
	}
	e.line("import type {")
	for _, name := range names {
		e.line("  %s,", name)
	}
	e.line("} from \"./wire.generated\";")
	e.line("")
}

func (e *methodsEmitter) features() {
	e.line("// Every capability key discovery may advertise (API.md §9). Private: it exists to")
	e.line("// derive the union, and a published array with no reader would be a second table.")
	e.line("const FEATURES = [")
	for _, feature := range protocol.Features {
		e.line("  %s,", strconv.Quote(feature))
	}
	e.line("] as const;")
	e.line("")
	e.line("/** One capability key discovery may advertise. */")
	e.line("export type WireFeature = (typeof FEATURES)[number];")
	e.line("")
}

func (e *methodsEmitter) names(metas []dispatch.MethodMeta) {
	e.line("// Every method the runtime routes, in registration order.")
	e.line("const METHOD_NAMES = [")
	for _, meta := range metas {
		e.line("  %s,", strconv.Quote(meta.Name))
	}
	e.line("] as const;")
	e.line("")
	e.line("/** One method the runtime routes. */")
	e.line("export type WireMethodName = (typeof METHOD_NAMES)[number];")
	e.line("")
}

// shapes renders the frames each method carries. A method with no result has no
// `result` member rather than carrying `void`: an ack-only method answers with an
// empty success, and WireResult reads that absence.
//
// A stream's events are absent for the same reason its ack is present: the SDK names
// RunEvent and WorkspaceEvent directly, which are already this contract's types, so
// a per-method event alias would only add a second way to spell one of two answers.
func (e *methodsEmitter) shapes(metas []dispatch.MethodMeta) string {
	var out strings.Builder
	fmt.Fprintln(&out, "/** The frames each method carries. */")
	fmt.Fprintln(&out, "export interface WireShapes {")
	for _, meta := range metas {
		members := []string{"params: " + e.shape(meta.Params)}
		if meta.Result != nil {
			result := e.shape(meta.Result)
			if meta.ResultNullable {
				result += " | null"
			}
			members = append(members, "result: "+result)
		}
		fmt.Fprintf(&out, "  %s: { %s };\n", strconv.Quote(meta.Name), strings.Join(members, "; "))
	}
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out, "")
	return out.String()
}

func (e *methodsEmitter) helpers() {
	e.line("export type WireParams<M extends WireMethodName> = WireShapes[M][\"params\"];")
	e.line("")
	e.line("/** A method with no result answers with an empty success. */")
	e.line("export type WireResult<M extends WireMethodName> =")
	e.line("  WireShapes[M] extends { result: infer R } ? R : void;")
}

// shape names a Go frame type as TypeScript spells it, recording a published shape
// so the import list can name it. A frame with no published definition renders
// inline instead — the empty request struct as `Record<string, never>`, an opaque
// tool result as `unknown` — and there is nothing to import.
func (e *methodsEmitter) shape(t reflect.Type) string {
	name := e.typeName(t)
	if _, published := e.set.defs[name]; published {
		e.imported[name] = true
	}
	return name
}

func (e *methodsEmitter) line(format string, arguments ...any) {
	fmt.Fprintf(&e.out, format+"\n", arguments...)
}
