package main

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/Tangerg/lynx/app/runtime/internal/delivery/protocol"
)

// The canonical sample index, projected for the side that cannot read Go.
//
// Contract §11.3 asks that the Go round-trip, the TypeScript validator and the JSON
// Schema each check the same batch of hand-written fixtures. "The same batch" needs
// one statement of which file is which shape, and the binding is that statement —
// projected here rather than restated, which is what the TypeScript side used to do
// with a parallel list of `wire<T>(sample)` pins.
//
// The samples themselves stay hand-written. §11.3 forbids generating a fixture and
// then proving it with a schema from the same source, and it is right to: a fixture
// derived from the shape can only ever agree with it.
const tsSamplesFileName = "wire.samples.generated.ts"

func newWireSamples() string {
	var out strings.Builder
	out.WriteString(`// Code generated by cmd/contractgen. DO NOT EDIT.
//
// Which canonical sample is which shape. The samples in ./samples are hand-written;
// only this index is generated, from the same binding the Go round-trip reads.

import type { WireTypeName } from "./wire.validate.generated";

/** One hand-written sample and the published shape it must satisfy. */
export interface WireSample {
  file: string;
  shape: WireTypeName;
}

export const WIRE_SAMPLES: readonly WireSample[] = [
`)
	for _, sample := range protocol.CanonicalSamples {
		fmt.Fprintf(&out, "  { file: %s, shape: %s },\n", strconv.Quote(sample.File), strconv.Quote(defName(sample.Type)))
	}
	out.WriteString("];\n")
	return out.String()
}

// sampleEntry is the manifest's projection of the same binding, so a reader who has
// only the artifacts can still tell which fixture proves which shape.
type sampleEntry struct {
	File  string `json:"file"`
	Shape string `json:"shape"`
}

func canonicalSamples() []sampleEntry {
	out := make([]sampleEntry, 0, len(protocol.CanonicalSamples))
	for _, sample := range protocol.CanonicalSamples {
		out = append(out, sampleEntry{File: sample.File, Shape: defName(sample.Type)})
	}
	return out
}
