package main

import (
	"fmt"
	"maps"
	"reflect"
	"slices"
	"strconv"
	"strings"

	"github.com/Tangerg/lynx/app/runtime/internal/delivery/dispatch"
	"github.com/Tangerg/lynx/app/runtime/internal/delivery/protocol"
)

// The method surface, as TypeScript reads it: which methods exist and what each one
// carries.
//
// This is the half of contract §11.3's fifth artifact class that has a reader. Go
// needs no generated method constants — `server` and `dispatch` are the same ring
// and the Registry itself is their shared source, so a second table of
// `MethodRunsStart = "runs.start"` that dispatch does not consume would BE the
// second author it was meant to remove. TypeScript cannot read the Registry at all,
// and before this it restated every one of those facts by hand: 83 method-name
// literals, dozens of result types, and a parallel union of the nineteen capability
// keys.
//
// What is NOT generated is how this client calls. §12 keeps the wire narrow and
// gives the SDK the friendly handles, so the frame TYPES land here and `methods.ts`
// composes them with its own transport concerns (abort signal, idempotency key). A
// generated wrapper per method would be a third layer that only forwards.
const tsMethodsFileName = "wire.methods.generated.ts"

type methodsEmitter struct {
	tsTypes
	out strings.Builder

	// imported collects the published shapes the module names, so its import list is
	// exactly those — the frontend compiles with noUnusedLocals.
	imported map[string]bool
}

func newWireMethods(registry *dispatch.Registry, set *schemaSet) string {
	emitter := &methodsEmitter{tsTypes: tsTypes{set: set}, imported: make(map[string]bool)}
	metas := registry.Metas()

	// Rendered first: the shapes it names decide the import list.
	shapes := emitter.shapes(metas)

	emitter.header()
	emitter.imports()
	emitter.features()
	emitter.names(metas)
	emitter.out.WriteString(shapes)
	emitter.helpers()
	return emitter.out.String()
}

func (e *methodsEmitter) header() {
	e.line("// Code generated by cmd/contractgen. DO NOT EDIT.")
	e.line("//")
	e.line("// The method surface of the Lyra Runtime Protocol: which methods exist and what")
	e.line("// each one carries.")
	e.line("//")
	e.line("// The SDK in methods.ts composes these with its own transport concerns. This file")
	e.line("// holds no policy of its own — every fact in it is read from the Contract Registry.")
	e.line("")
}

func (e *methodsEmitter) imports() {
	names := slices.Sorted(maps.Keys(e.imported))
	if len(names) == 0 {
		return
	}
	e.line("import type {")
	for _, name := range names {
		e.line("  %s,", name)
	}
	e.line("} from \"./wire.generated\";")
	e.line("")
}

func (e *methodsEmitter) features() {
	e.line("// Every capability key discovery may advertise (API.md §9). Private: it exists to")
	e.line("// derive the union, and a published array with no reader would be a second table.")
	e.line("const FEATURES = [")
	for _, feature := range protocol.Features {
		e.line("  %s,", strconv.Quote(feature))
	}
	e.line("] as const;")
	e.line("")
	e.line("/** One capability key discovery may advertise. */")
	e.line("export type WireFeature = (typeof FEATURES)[number];")
	e.line("")
}

func (e *methodsEmitter) names(metas []dispatch.MethodMeta) {
	e.line("// Every method the runtime routes, in registration order.")
	e.line("const METHOD_NAMES = [")
	for _, meta := range metas {
		e.line("  %s,", strconv.Quote(meta.Name))
	}
	e.line("] as const;")
	e.line("")
	e.line("/** One method the runtime routes. */")
	e.line("export type WireMethodName = (typeof METHOD_NAMES)[number];")
	e.line("")
}

// shapes renders the frames each method carries. A method with no result has no
// `result` member rather than carrying `void`: an ack-only method answers with an
// empty success, and WireResult reads that absence.
//
// A stream's events are absent for the same reason its ack is present: the SDK names
// RunEvent and WorkspaceEvent directly, which are already this contract's types, so
// a per-method event alias would only add a second way to spell one of two answers.
func (e *methodsEmitter) shapes(metas []dispatch.MethodMeta) string {
	var out strings.Builder
	fmt.Fprintln(&out, "/** The frames each method carries. */")
	fmt.Fprintln(&out, "export interface WireShapes {")
	for _, meta := range metas {
		members := []string{"params: " + e.shape(meta.Params)}
		if meta.Result != nil {
			result := e.shape(meta.Result)
			if meta.ResultNullable {
				result += " | null"
			}
			members = append(members, "result: "+result)
		}
		fmt.Fprintf(&out, "  %s: { %s };\n", strconv.Quote(meta.Name), strings.Join(members, "; "))
	}
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out, "")
	return out.String()
}

func (e *methodsEmitter) helpers() {
	e.line("export type WireParams<M extends WireMethodName> = WireShapes[M][\"params\"];")
	e.line("")
	e.line("/** A method with no result answers with an empty success. */")
	e.line("export type WireResult<M extends WireMethodName> =")
	e.line("  WireShapes[M] extends { result: infer R } ? R : void;")
}

// shape names a Go frame type as TypeScript spells it, recording a published shape
// so the import list can name it. A frame with no published definition renders
// inline instead — the empty request struct as `Record<string, never>`, an opaque
// tool result as `unknown` — and there is nothing to import.
func (e *methodsEmitter) shape(t reflect.Type) string {
	name := e.typeName(t)
	if _, published := e.set.defs[name]; published {
		e.imported[name] = true
	}
	return name
}

func (e *methodsEmitter) line(format string, arguments ...any) {
	fmt.Fprintf(&e.out, format+"\n", arguments...)
}
