package main

import (
	"fmt"
	"reflect"
	"slices"
	"strconv"
	"strings"

	"github.com/Tangerg/lynx/app/runtime/internal/delivery/dispatch"
	"github.com/Tangerg/lynx/app/runtime/internal/delivery/protocol"
)

// The authoritative Go wire validator: the Go half of contract §11.3's
// "authoritative/terminal runtime validators".
//
// It replaces hand-written request checks and also guards typed output boundaries.
// Generating Go, schema and TypeScript checks from the same registry is what makes
// §11.4 gate 6's three-way equivalence structural rather than aspirational.
//
// Four rule sources, and none restates another's job:
//
//   - the declared value constraints (a string that may not be empty, a number
//     that may not be zero) — reflection cannot see these;
//   - closed-enum membership, DERIVED from the enum's own declared value set. Go's
//     decoder puts any string into a named string type, so without this check a
//     bogus tag reaches a use case or client;
//   - registered union variants;
//   - registered conditional presence rules.

// validatorFile is written into the protocol package, beside the shapes it checks.
const validatorFile = "wire_constraints.generated.go"

func newValidators(registry *dispatch.Registry, shapes *dispatch.Shapes) string {
	var out strings.Builder
	out.WriteString("// Code generated by cmd/contractgen. DO NOT EDIT.\n\n")
	out.WriteString("package protocol\n")

	declared := make(map[reflect.Type][]dispatch.FieldConstraint)
	for _, spec := range shapes.ValueConstraints() {
		declared[spec.GoType] = append(declared[spec.GoType], spec.Constraints...)
	}
	unions := make(map[reflect.Type]dispatch.UnionSpec)
	for _, spec := range shapes.Unions() {
		unions[spec.GoType] = spec
	}
	objects := make(map[reflect.Type][]dispatch.PresenceRule)
	for _, spec := range shapes.Constraints() {
		objects[spec.GoType] = append(objects[spec.GoType], spec.Rules...)
	}

	// Request roots come first in method-registration order. Registered unions,
	// conditional objects and value-constrained roots follow in declaration order.
	// This makes every Registry-authored shape rule reachable by the Go generator,
	// including DTOs that only travel from server to client.
	var targets []reflect.Type
	written := make(map[reflect.Type]bool)
	for _, meta := range registry.Metas() {
		if meta.Params == nil || written[meta.Params] || meta.Params.Name() == "" {
			continue
		}
		written[meta.Params] = true
		targets = append(targets, meta.Params)
	}
	for _, spec := range shapes.Unions() {
		if written[spec.GoType] || spec.GoType.Name() == "" {
			continue
		}
		written[spec.GoType] = true
		targets = append(targets, spec.GoType)
	}
	for _, spec := range shapes.Constraints() {
		if written[spec.GoType] || spec.GoType.Name() == "" {
			continue
		}
		written[spec.GoType] = true
		targets = append(targets, spec.GoType)
	}
	for _, spec := range shapes.ValueConstraints() {
		if written[spec.GoType] || spec.GoType.Name() == "" {
			continue
		}
		written[spec.GoType] = true
		targets = append(targets, spec.GoType)
	}

	for _, target := range targets {
		checks := validatorChecks(target, declared[target], unions[target], objects[target])
		if len(checks) == 0 {
			continue
		}
		fmt.Fprintf(&out, "\nfunc (value %s) ValidateWire() error {\n", target.Name())
		fmt.Fprintf(&out, "\treturn collectWireViolations(%q,\n", target.Name())
		for _, check := range checks {
			fmt.Fprintf(&out, "\t\t%s,\n", check)
		}
		out.WriteString("\t)\n}\n")
	}
	return out.String()
}

// validatorChecks builds every frame-local check registered for one wire shape.
func validatorChecks(
	shape reflect.Type,
	constraints []dispatch.FieldConstraint,
	union dispatch.UnionSpec,
	rules []dispatch.PresenceRule,
) []string {
	var checks []string
	for _, constraint := range constraints {
		selector, leaf, ok := protocol.GoPath(shape, constraint.Field)
		if !ok {
			panic(fmt.Sprintf("contractgen: %s has no field %q", shape.Name(), constraint.Field))
		}
		field := strconv.Quote(constraint.Field)
		switch constraint.Kind {
		case dispatch.ConstraintNonEmpty:
			validatorName := "requiredText"
			if leaf.Optional && leaf.Type.Kind() == reflect.Pointer {
				validatorName = "optionalText"
			}
			checks = append(checks, fmt.Sprintf("%s(%s, %s)", validatorName, field, stringExpr(selector, leaf.Type)))
		case dispatch.ConstraintPositive:
			validatorName := "positiveNumber"
			if leaf.Optional {
				validatorName = "optionalPositiveNumber"
			}
			checks = append(checks, fmt.Sprintf("%s(%s, value.%s)", validatorName, field, selector))
		case dispatch.ConstraintNonNegative:
			checks = append(checks, fmt.Sprintf("nonNegativeNumber(%s, value.%s)", field, selector))
		case dispatch.ConstraintNonEmptyItems:
			validatorName := "requiredItems"
			if leaf.Optional {
				validatorName = "nonEmptyItems"
			}
			checks = append(checks, fmt.Sprintf("%s(%s, value.%s)", validatorName, field, selector))
		case dispatch.ConstraintUniqueItems:
			checks = append(checks, fmt.Sprintf("uniqueItems(%s, value.%s)", field, selector))
		default:
			panic(fmt.Sprintf(
				"contractgen: %s.%s uses unsupported constraint %s",
				shape.Name(),
				constraint.Field,
				constraint.Kind,
			))
		}
	}
	for _, field := range protocol.WireFields(shape) {
		if values, ok := protocol.WireEnum(field.Type); ok {
			checks = append(checks, fmt.Sprintf("closedEnum(%s, string(value.%s), %s, %t)",
				strconv.Quote(field.Name), field.GoName, valueList(values), field.Optional))
			continue
		}
		if field.Type.Kind() == reflect.Slice {
			if values, ok := protocol.WireEnum(field.Type.Elem()); ok {
				checks = append(checks, fmt.Sprintf("closedEnumItems(%s, value.%s, %s)",
					strconv.Quote(field.Name), field.GoName, valueList(values)))
			}
		}
	}
	checks = append(checks, unionChecks(union)...)
	checks = append(checks, objectChecks(rules)...)
	return checks
}

func unionChecks(union dispatch.UnionSpec) []string {
	if union.GoType == nil {
		return nil
	}
	paths := unionPaths(union)
	var checks []string
	if pattern := union.PatternVariant; pattern != nil {
		field, ok := protocol.LookupWireField(union.GoType, union.Discriminator)
		if !ok {
			panic(fmt.Sprintf("contractgen: %s has no discriminator %q", union.GoType.Name(), union.Discriminator))
		}
		tags := make([]string, 0, len(union.Variants))
		for _, variant := range union.Variants {
			tags = append(tags, variant.Tag)
		}
		checks = append(checks, fmt.Sprintf(
			"unionTag(%q, string(value.%s), %s, %q)",
			union.Discriminator, field.GoName, valueList(tags), pattern.TagPattern,
		))
	}
	for _, variant := range union.Variants {
		applies := fmt.Sprintf("wireFieldEquals(value, %q, %q)", union.Discriminator, variant.Tag)
		allowed := append(slices.Clone(variant.Required), variant.Optional...)
		for _, field := range variant.Required {
			checks = append(checks, fmt.Sprintf("requiredWhen(%s, %q, value)", applies, field))
		}
		for _, field := range paths {
			if slices.Contains(allowed, field) {
				continue
			}
			checks = append(checks, fmt.Sprintf("forbiddenWhen(%s, %q, value)", applies, field))
		}
	}
	if pattern := union.PatternVariant; pattern != nil {
		applies := fmt.Sprintf("wireFieldMatches(value, %q, %q)", union.Discriminator, pattern.TagPattern)
		allowed := append(slices.Clone(pattern.Required), pattern.Optional...)
		for _, field := range pattern.Required {
			checks = append(checks, fmt.Sprintf("requiredWhen(%s, %q, value)", applies, field))
		}
		for _, field := range paths {
			if slices.Contains(allowed, field) {
				continue
			}
			checks = append(checks, fmt.Sprintf("forbiddenWhen(%s, %q, value)", applies, field))
		}
	}
	return checks
}

func unionPaths(union dispatch.UnionSpec) []string {
	var paths []string
	for _, variant := range union.Variants {
		for _, field := range append(slices.Clone(variant.Required), variant.Optional...) {
			if field != union.Discriminator && !slices.Contains(paths, field) {
				paths = append(paths, field)
			}
		}
	}
	if pattern := union.PatternVariant; pattern != nil {
		for _, field := range append(slices.Clone(pattern.Required), pattern.Optional...) {
			if field != union.Discriminator && !slices.Contains(paths, field) {
				paths = append(paths, field)
			}
		}
	}
	return paths
}

func objectChecks(rules []dispatch.PresenceRule) []string {
	var checks []string
	for _, rule := range rules {
		applies := conditionExpression(rule.When)
		for _, field := range rule.Required {
			checks = append(checks, fmt.Sprintf("requiredWhen(%s, %q, value)", applies, field))
		}
		for _, field := range rule.Forbidden {
			checks = append(checks, fmt.Sprintf("forbiddenWhen(%s, %q, value)", applies, field))
		}
	}
	return checks
}

func conditionExpression(conditions []dispatch.FieldCondition) string {
	if len(conditions) == 0 {
		return "true"
	}
	parts := make([]string, 0, len(conditions))
	for _, condition := range conditions {
		switch condition.Operator.String() {
		case "equals":
			parts = append(parts, fmt.Sprintf(
				"wireFieldEquals(value, %q, %q)", condition.Field, condition.Value,
			))
		case "present":
			parts = append(parts, fmt.Sprintf("wireFieldPresent(value, %q)", condition.Field))
		default:
			panic(fmt.Sprintf("contractgen: unsupported presence operator %q", condition.Operator))
		}
	}
	return strings.Join(parts, " && ")
}

// stringExpr reads a field as a string. A named string type — a closed enum, an id —
// needs the conversion, and a plain string must not have one: an identity conversion
// is what the linter deletes, so emitting one everywhere would make the generated
// file fail the check it is generated to pass.
func stringExpr(selector string, leaf reflect.Type) string {
	const builtinStringTypeName = "string"

	value := "value." + selector
	if leaf.Kind() == reflect.Pointer {
		return value
	}
	if leaf.Kind() == reflect.String && leaf.Name() != builtinStringTypeName {
		return fmt.Sprintf("string(value.%s)", selector)
	}
	return value
}

func valueList(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, strconv.Quote(value))
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

// valueConstraintsFor returns the declared constraints on one field of a shape, so
// the schema walk can state the same rule as minLength / minimum.
func (s *schemaSet) valueConstraintsFor(owner reflect.Type, field string) []dispatch.ConstraintKind {
	var out []dispatch.ConstraintKind
	for _, constraint := range s.values[owner] {
		if constraint.Field == field && !slices.Contains(out, constraint.Kind) {
			out = append(out, constraint.Kind)
		}
	}
	return out
}
