import type { VisualStyleSpec } from "@/plugins/sdk";
import { SYNARA_MOTION, visualStyleTokens } from "./tokens";

export const herouiStyle: VisualStyleSpec = {
  id: "heroui",
  label: "HeroUI",
  description: "Generous soft geometry, pill actions and layered floating surfaces.",
  order: 50,
  traits: { regions: "floating-card", controls: "elevated" },
  motion: {
    ...SYNARA_MOTION,
    mediumMs: 250,
    disclosureMs: 250,
    slowMs: 400,
    drawerMs: 350,
  },
  preview: {
    canvas: "#fafafa",
    sidebar: "#f0f0f3",
    dock: "#ffffff",
    edge: "rgb(24 24 27 / 0.07)",
    accent: "#006fee",
  },
  tokens: visualStyleTokens({
    "style-shape-2xs": "6px",
    "style-shape-xs": "8px",
    "style-shape-sm": "10px",
    "style-shape-md": "12px",
    "style-shape-lg": "16px",
    "style-shape-xl": "24px",
    "style-shape-content": "20px",
    "style-shape-composer": "24px",
    "style-shape-bubble": "16px",
    "button-radius": "var(--shape-pill)",
    "field-radius": "var(--shape-md)",
    "segmented-radius": "var(--shape-pill)",
    "segment-radius": "var(--shape-pill)",
    "surface-card-radius": "var(--shape-lg)",
    "floating-panel-radius": "var(--shape-xl)",
    "floating-tip-radius": "var(--shape-md)",
    "dock-tab-radius": "var(--shape-pill)",
    "control-height-xs": "26px",
    "control-height-sm": "30px",
    "control-height-md": "34px",
    "control-height-lg": "40px",
    "field-height-sm": "28px",
    "field-height-md": "34px",
    "field-height-lg": "38px",
    "menu-row-height": "30px",
    "dock-tab-height": "30px",
    "surface-header-height": "48px",
    "control-edge-width": "0.5px",
    "composer-edge-width": "0.5px",
    "app-drawer-surface": "color-mix(in srgb, var(--color-surface) 90%, transparent)",
    "app-drawer-backdrop": "blur(18px) saturate(145%)",
    "app-drawer-shadow": "none",
    "app-drawer-sheen-opacity": "0.65",
    "app-content-shadow":
      "-10px 0 34px -22px color-mix(in srgb, var(--color-text) 28%, transparent)",
    "app-content-ring": "inset 0 0 0 0.5px color-mix(in srgb, var(--color-text) 7%, transparent)",
    "app-content-ring-opacity": "1",
    "app-header-surface": "color-mix(in srgb, var(--color-bg) 84%, transparent)",
    "app-dock-surface": "color-mix(in srgb, var(--color-surface) 68%, var(--color-bg))",
    "app-card-surface": "var(--color-bg)",
    "app-surface-divider": "color-mix(in srgb, var(--color-border) 36%, transparent)",
    "seam-line": "color-mix(in srgb, var(--color-text) 7%, transparent)",
    "seam-shadow-color": "color-mix(in srgb, var(--color-text) 16%, transparent)",
    "shadow-control": "0 3px 9px -4px color-mix(in srgb, var(--color-text) 18%, transparent)",
    "shadow-composer-depth":
      "0 14px 42px -22px color-mix(in srgb, var(--color-text) 28%, transparent)",
    "shadow-popover":
      "0 0 0 0.5px color-mix(in srgb, var(--color-text) 7%, transparent), 0 24px 60px -24px color-mix(in srgb, var(--color-text) 32%, transparent)",
    "shadow-well": "inset 0 1px 2px color-mix(in srgb, var(--color-text) 5%, transparent)",
    "shadow-raised-chip":
      "0 3px 10px -5px color-mix(in srgb, var(--color-text) 20%, transparent), inset 0 1px 0 color-mix(in srgb, white 60%, transparent)",
    "shadow-surface-card":
      "0 0 0 0.5px color-mix(in srgb, var(--color-text) 5%, transparent), 0 12px 36px -20px color-mix(in srgb, var(--color-text) 20%, transparent)",
  }),
};
