import type { VisualStyleSpec } from "@/plugins/sdk";
import { SYNARA_MOTION, visualStyleTokens } from "./tokens";

export const jetbrainsClassicStyle: VisualStyleSpec = {
  id: "jetbrains-classic",
  label: "JetBrains Classic",
  description: "Compact tool windows, firm hairlines and practical square controls.",
  order: 30,
  traits: { regions: "tool-windows", controls: "outlined" },
  motion: {
    ...SYNARA_MOTION,
    fastMs: 100,
    mediumMs: 150,
    disclosureMs: 180,
    slowMs: 250,
    drawerMs: 220,
    pressScale: 0.98,
  },
  preview: {
    canvas: "#f2f2f2",
    sidebar: "#e7e7e7",
    dock: "#ededed",
    edge: "#b9b9b9",
    accent: "#3574f0",
  },
  tokens: visualStyleTokens({
    "style-shape-2xs": "2px",
    "style-shape-xs": "3px",
    "style-shape-sm": "4px",
    "style-shape-md": "5px",
    "style-shape-lg": "6px",
    "style-shape-xl": "8px",
    "style-shape-content": "0px",
    "style-shape-composer": "8px",
    "style-shape-bubble": "6px",
    "button-radius": "var(--shape-sm)",
    "field-radius": "var(--shape-sm)",
    "segmented-radius": "var(--shape-sm)",
    "segment-radius": "var(--shape-xs)",
    "surface-card-radius": "var(--shape-sm)",
    "floating-panel-radius": "var(--shape-md)",
    "floating-tip-radius": "var(--shape-sm)",
    "dock-tab-radius": "var(--shape-xs)",
    "control-height-xs": "22px",
    "control-height-sm": "26px",
    "control-height-md": "30px",
    "field-height-sm": "24px",
    "field-height-md": "28px",
    "field-height-lg": "32px",
    "menu-row-height": "24px",
    "dock-tab-height": "26px",
    "surface-header-height": "40px",
    "control-edge-width": "1px",
    "app-drawer-surface": "var(--color-surface-2)",
    "app-drawer-backdrop": "none",
    "app-drawer-shadow": "none",
    "app-drawer-sheen-opacity": "0",
    "app-content-shadow": "none",
    "app-content-ring": "none",
    "app-content-ring-opacity": "0",
    "app-header-surface": "var(--color-surface-3)",
    "app-dock-surface": "var(--color-surface-2)",
    "app-card-surface": "var(--color-bg)",
    "app-surface-divider": "var(--color-border-soft)",
    "seam-line": "var(--color-border-soft)",
    "seam-shadow-color": "transparent",
    "shadow-control": "none",
    "shadow-composer-depth": "none",
    "shadow-popover": "0 0 0 1px var(--color-border-soft), 0 8px 18px rgb(0 0 0 / 0.22)",
    "shadow-well": "inset 0 1px 1px color-mix(in srgb, var(--color-text) 8%, transparent)",
    "shadow-raised-chip": "none",
    "shadow-surface-card": "none",
  }),
};
