import type { VisualStyleSpec } from "@/plugins/sdk";
import { SYNARA_MOTION, visualStyleTokens } from "./tokens";

export const jetbrainsHeroStyle: VisualStyleSpec = {
  id: "jetbrains-heroui",
  label: "JetBrains · HeroUI",
  description: "JetBrains tool-window structure with soft, elevated component surfaces.",
  order: 40,
  traits: { regions: "tool-windows", controls: "elevated" },
  motion: SYNARA_MOTION,
  preview: {
    canvas: "#ffffff",
    sidebar: "#f4f4f6",
    dock: "#f8f8fa",
    edge: "rgb(15 23 42 / 0.08)",
    accent: "#6d5dfc",
  },
  tokens: visualStyleTokens({
    "style-shape-2xs": "5px",
    "style-shape-xs": "7px",
    "style-shape-sm": "9px",
    "style-shape-md": "11px",
    "style-shape-lg": "14px",
    "style-shape-xl": "18px",
    "style-shape-content": "0px",
    "style-shape-composer": "18px",
    "style-shape-bubble": "13px",
    "button-radius": "var(--shape-md)",
    "field-radius": "var(--shape-md)",
    "segmented-radius": "var(--shape-md)",
    "segment-radius": "var(--shape-sm)",
    "surface-card-radius": "var(--shape-lg)",
    "floating-panel-radius": "var(--shape-xl)",
    "floating-tip-radius": "var(--shape-md)",
    "dock-tab-radius": "var(--shape-md)",
    "surface-header-height": "44px",
    "control-edge-width": "0.5px",
    "composer-edge-width": "0.5px",
    "app-drawer-surface": "var(--color-surface)",
    "app-drawer-backdrop": "none",
    "app-drawer-shadow": "none",
    "app-drawer-sheen-opacity": "0",
    "app-content-shadow": "none",
    "app-content-ring": "none",
    "app-content-ring-opacity": "0",
    "app-header-surface": "color-mix(in srgb, var(--color-surface) 72%, var(--color-bg))",
    "app-dock-surface": "color-mix(in srgb, var(--color-surface) 78%, var(--color-bg))",
    "app-card-surface": "var(--color-bg)",
    "app-surface-divider": "color-mix(in srgb, var(--color-border) 58%, transparent)",
    "seam-line": "var(--app-surface-divider)",
    "seam-shadow-color": "transparent",
    "shadow-control": "0 2px 6px -2px color-mix(in srgb, var(--color-text) 14%, transparent)",
    "shadow-popover":
      "0 0 0 0.5px color-mix(in srgb, var(--color-text) 8%, transparent), 0 16px 40px -14px color-mix(in srgb, var(--color-text) 22%, transparent)",
    "shadow-well": "inset 0 1px 2px color-mix(in srgb, var(--color-text) 5%, transparent)",
    "shadow-raised-chip":
      "0 2px 7px -3px color-mix(in srgb, var(--color-text) 18%, transparent), inset 0 1px 0 color-mix(in srgb, white 55%, transparent)",
    "shadow-surface-card":
      "0 0 0 0.5px color-mix(in srgb, var(--color-text) 6%, transparent), 0 10px 28px -16px color-mix(in srgb, var(--color-text) 18%, transparent)",
  }),
};
