import type { VisualStyleSpec } from "@/plugins/sdk";
import { SYNARA_MOTION, visualStyleTokens } from "./tokens";

export const novaStyle: VisualStyleSpec = {
  id: "nova",
  label: "Nova",
  description: "Tonal columns, restrained depth and clear rounded selection states.",
  order: 10,
  traits: { regions: "tonal-columns", controls: "tonal" },
  motion: SYNARA_MOTION,
  preview: {
    canvas: "#ffffff",
    sidebar: "#edf2f8",
    dock: "#f3f6fa",
    edge: "#dce3ec",
    accent: "#3976f6",
  },
  tokens: visualStyleTokens({
    "style-shape-2xs": "3px",
    "style-shape-xs": "5px",
    "style-shape-sm": "7px",
    "style-shape-md": "8px",
    "style-shape-lg": "10px",
    "style-shape-xl": "12px",
    "style-shape-content": "0px",
    "style-shape-composer": "14px",
    "style-shape-bubble": "10px",
    "button-radius": "var(--shape-sm)",
    "field-radius": "var(--shape-sm)",
    "segmented-radius": "var(--shape-md)",
    "segment-radius": "var(--shape-sm)",
    "surface-card-radius": "var(--shape-lg)",
    "floating-panel-radius": "var(--shape-lg)",
    "floating-tip-radius": "var(--shape-sm)",
    "dock-tab-radius": "var(--shape-pill)",
    "app-drawer-surface": "color-mix(in srgb, var(--color-surface) 84%, var(--color-bg))",
    "app-drawer-backdrop": "none",
    "app-drawer-shadow": "none",
    "app-drawer-sheen-opacity": "0",
    "app-content-shadow": "none",
    "app-content-ring": "none",
    "app-content-ring-opacity": "0",
    "app-header-surface": "color-mix(in srgb, var(--color-surface) 62%, var(--color-bg))",
    "app-dock-surface": "color-mix(in srgb, var(--color-surface) 76%, var(--color-bg))",
    "app-card-surface": "var(--color-bg)",
    "app-surface-divider": "color-mix(in srgb, var(--color-border) 74%, transparent)",
    "seam-line": "var(--app-surface-divider)",
    "seam-shadow-color": "transparent",
    "shadow-control": "none",
    "shadow-well": "none",
    "shadow-raised-chip": "none",
    "shadow-surface-card": "none",
    "control-edge-width": "1px",
  }),
};
