import type { VisualStyleSpec } from "@/plugins/sdk";
import { SYNARA_MOTION, visualStyleTokens } from "./tokens";

export const zedStyle: VisualStyleSpec = {
  id: "zed",
  label: "Zed",
  description: "Dense flush panes, crisp separators and near-zero decorative depth.",
  order: 20,
  traits: { regions: "flush-panes", controls: "quiet" },
  motion: {
    ...SYNARA_MOTION,
    fastMs: 100,
    mediumMs: 150,
    disclosureMs: 180,
    slowMs: 250,
    drawerMs: 220,
    pressScale: 0.98,
  },
  preview: {
    canvas: "#111315",
    sidebar: "#16191c",
    dock: "#111315",
    edge: "#2c3136",
    accent: "#58a6ff",
  },
  tokens: visualStyleTokens({
    "style-shape-2xs": "2px",
    "style-shape-xs": "3px",
    "style-shape-sm": "4px",
    "style-shape-md": "5px",
    "style-shape-lg": "6px",
    "style-shape-xl": "8px",
    "style-shape-content": "0px",
    "style-shape-composer": "8px",
    "style-shape-bubble": "6px",
    "button-radius": "var(--shape-sm)",
    "field-radius": "var(--shape-sm)",
    "segmented-radius": "var(--shape-sm)",
    "segment-radius": "var(--shape-xs)",
    "surface-card-radius": "var(--shape-md)",
    "floating-panel-radius": "var(--shape-lg)",
    "floating-tip-radius": "var(--shape-sm)",
    "dock-tab-radius": "var(--shape-xs)",
    "control-height-xs": "22px",
    "control-height-sm": "26px",
    "control-height-md": "30px",
    "field-height-sm": "24px",
    "field-height-md": "28px",
    "field-height-lg": "32px",
    "menu-row-height": "24px",
    "dock-tab-height": "26px",
    "surface-header-height": "40px",
    "app-drawer-surface": "var(--color-surface)",
    "app-drawer-backdrop": "none",
    "app-drawer-shadow": "none",
    "app-drawer-sheen-opacity": "0",
    "app-content-shadow": "none",
    "app-content-ring": "none",
    "app-content-ring-opacity": "0",
    "app-header-surface": "var(--color-surface)",
    "app-dock-surface": "var(--color-bg)",
    "app-card-surface": "var(--color-bg)",
    "app-surface-divider": "var(--color-border-soft)",
    "seam-line": "var(--color-border-soft)",
    "seam-shadow-color": "transparent",
    "control-edge-width": "1px",
    "shadow-control": "none",
    "shadow-composer-depth": "none",
    "shadow-popover": "0 0 0 1px var(--color-border-soft), 0 8px 24px rgb(0 0 0 / 0.28)",
    "shadow-well": "none",
    "shadow-raised-chip": "none",
    "shadow-surface-card": "none",
  }),
};
