export {
  activateWorkspaceSessionScope,
  closeActiveWorkspaceView,
  closeWorkspaceDockView,
  closeWorkspaceView,
  clearWorkspaceSettingsPaneTarget,
  forgetWorkspaceSessionScopes,
  getWorkspaceDockViewId,
  getWorkspaceSettingsPaneTarget,
  openWorkspaceDiffForFile,
  openWorkspaceFile,
  openWorkspaceSettingsPane,
  openWorkspaceView,
  openWorkspaceViewInDock,
  promoteWorkspaceDockViewToFull,
  selectInitialWorkspaceTool,
  selectWorkspaceChat,
  useActiveWorkspaceFile,
  useActiveWorkspaceViewId,
  useDockWorkspaceViewId,
  useExpandedWorkspaceToolIds,
  useSelectWorkspaceTool,
  useToggleWorkspaceTool,
  useWorkspaceFileViewer,
  useWorkspaceSettingsPaneTarget,
} from "../application/navigation";
export {
  openContextDockDestination,
  openContextDockLauncher,
  toggleContextDock,
} from "../application/contextDock";
