export {
  closeActiveWorkspaceView,
  closeWorkspaceSplit,
  closeWorkspaceView,
  clearWorkspaceSettingsPaneTarget,
  getWorkspaceSettingsPaneTarget,
  openWorkspaceDiffForFile,
  openWorkspaceFile,
  openWorkspaceSettingsPane,
  openWorkspaceView,
  openWorkspaceViewBeside,
  promoteWorkspaceSplitToView,
  selectInitialWorkspaceTool,
  selectWorkspaceChat,
  useActiveWorkspaceFile,
  useActiveWorkspaceViewId,
  useExpandedWorkspaceToolIds,
  useSelectWorkspaceTool,
  useSplitWorkspaceViewId,
  useToggleWorkspaceTool,
  useWorkspaceFileViewer,
  useWorkspaceSettingsPaneTarget,
} from "../application/navigation";
export {
  closeContextDockView,
  openContextDockView,
  useActiveContextDockViewId,
} from "../application/contextDock";
