package sqlite

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"

	conversationdomain "github.com/Tangerg/lynx/app2/runtime/domain/conversation"
	goaldomain "github.com/Tangerg/lynx/app2/runtime/domain/goal"
	"github.com/Tangerg/lynx/app2/runtime/domain/session"
	"github.com/Tangerg/lynx/app2/runtime/domain/transcript"
	"github.com/Tangerg/lynx/app2/runtime/domain/toolresult"
	"github.com/Tangerg/lynx/app2/runtime/protocol"
	"github.com/Tangerg/lynx/app2/runtime/sessionflow"
)

const runSelect = `SELECT id, session_id, coalesce(parent_run_id, ''), coalesce(root_run_id, ''), coalesce(spawned_by_item_id, ''), status, coalesce(active_segment_id, ''), provider, model, coalesce(outcome, ''), detail, body, created_at, updated_at, coalesce(finished_at, '') FROM runs`

func (database *Database) ReadSessionMaterial(ctx context.Context, id session.ID) (sessionflow.Material,error){
	transaction,err:=database.database.BeginTx(ctx,&sql.TxOptions{ReadOnly:true});if err!=nil{return sessionflow.Material{},err};defer transaction.Rollback()
	value,err:=scanSession(transaction.QueryRowContext(ctx,`SELECT id,title,workspace_path,model,favorite,revision,created_at,updated_at FROM sessions WHERE id=?`,id.String()));if err!=nil{return sessionflow.Material{},err}
	material:=sessionflow.Material{Session:value,Interrupts:[]protocol.PendingInterruptSet{},Plan:protocol.Plan{SessionID:id.String(),Steps:[]protocol.PlanStep{}}}
	runRows,err:=transaction.QueryContext(ctx,runSelect+` WHERE session_id=? ORDER BY created_at,id`,id.String());if err!=nil{return sessionflow.Material{},err};for runRows.Next(){record,err:=scanRun(runRows);if err!=nil{runRows.Close();return sessionflow.Material{},err};material.Runs=append(material.Runs,record)};if err:=errors.Join(runRows.Err(),runRows.Close());err!=nil{return sessionflow.Material{},err}
	itemRows,err:=transaction.QueryContext(ctx,`SELECT id,session_id,run_id,ordinal,body,created_at FROM items WHERE session_id=? ORDER BY created_at,run_id,ordinal`,id.String());if err!=nil{return sessionflow.Material{},err};for itemRows.Next(){var item transcript.Record;var created string;if err:=itemRows.Scan(&item.ID,&item.SessionID,&item.RunID,&item.Ordinal,&item.Body,&created);err!=nil{itemRows.Close();return sessionflow.Material{},err};item.CreatedAt,err=decodeTime(created);if err!=nil{itemRows.Close();return sessionflow.Material{},err};material.Items=append(material.Items,item)};if err:=errors.Join(itemRows.Err(),itemRows.Close());err!=nil{return sessionflow.Material{},err}
	messageRows,err:=transaction.QueryContext(ctx,`SELECT session_id,run_id,ordinal,body FROM conversation_messages WHERE session_id=? ORDER BY ordinal`,id.String());if err!=nil{return sessionflow.Material{},err};for messageRows.Next(){var message conversationdomain.Record;if err:=messageRows.Scan(&message.SessionID,&message.RunID,&message.Ordinal,&message.Body);err!=nil{messageRows.Close();return sessionflow.Material{},err};material.Messages=append(material.Messages,message)};if err:=errors.Join(messageRows.Err(),messageRows.Close());err!=nil{return sessionflow.Material{},err}
	interruptRows,err:=transaction.QueryContext(ctx,`SELECT body FROM interrupt_sets WHERE session_id=? ORDER BY created_at,run_id`,id.String());if err!=nil{return sessionflow.Material{},err};for interruptRows.Next(){var body string;if err:=interruptRows.Scan(&body);err!=nil{interruptRows.Close();return sessionflow.Material{},err};var value protocol.PendingInterruptSet;if err:=json.Unmarshal([]byte(body),&value);err!=nil{interruptRows.Close();return sessionflow.Material{},err};material.Interrupts=append(material.Interrupts,value)};if err:=errors.Join(interruptRows.Err(),interruptRows.Close());err!=nil{return sessionflow.Material{},err}
	var planBody string;if err:=transaction.QueryRowContext(ctx,`SELECT body FROM plans WHERE session_id=?`,id.String()).Scan(&planBody);err==nil{if err:=json.Unmarshal([]byte(planBody),&material.Plan);err!=nil{return sessionflow.Material{},err}}else if !errors.Is(err,sql.ErrNoRows){return sessionflow.Material{},err}
	if goal,goalErr:=scanGoal(transaction.QueryRowContext(ctx,`SELECT session_id,incarnation_id,revision,status,coalesce(active_run_id,''),body FROM goals WHERE session_id=?`,id.String()));goalErr==nil{material.Goal=&goal}else if !errors.Is(goalErr,goaldomain.ErrNotFound){return sessionflow.Material{},goalErr}
	toolRows,err:=transaction.QueryContext(ctx,`SELECT body FROM tool_results WHERE session_id=? ORDER BY created_at,id`,id.String());if err!=nil{return sessionflow.Material{},err};for toolRows.Next(){var body string;if err:=toolRows.Scan(&body);err!=nil{toolRows.Close();return sessionflow.Material{},err};var result toolresult.Record;if err:=json.Unmarshal([]byte(body),&result);err!=nil{toolRows.Close();return sessionflow.Material{},err};if err:=result.Validate();err!=nil{toolRows.Close();return sessionflow.Material{},err};material.ToolResults=append(material.ToolResults,result)};if err:=errors.Join(toolRows.Err(),toolRows.Close());err!=nil{return sessionflow.Material{},err}
	if err:=transaction.Commit();err!=nil{return sessionflow.Material{},err};return material,nil
}

func (database *Database) CreateSessionFork(ctx context.Context,write sessionflow.ForkWrite)error{transaction,err:=database.database.BeginTx(ctx,nil);if err!=nil{return err};defer transaction.Rollback();if err:=insertSessionTx(ctx,transaction,write.Session);err!=nil{return err};for _,record:=range write.Runs{if err:=insertRun(ctx,transaction,record);err!=nil{return err}};for _,item:=range write.Items{if err:=insertItem(ctx,transaction,item);err!=nil{return err}};for _,message:=range write.Messages{if err:=insertConversationMessage(ctx,transaction,message);err!=nil{return err}};for _,result:=range write.ToolResults{if err:=insertToolResult(ctx,transaction,result);err!=nil{return err}};if write.Plan!=nil{if err:=insertPlanTx(ctx,transaction,*write.Plan);err!=nil{return err}};return transaction.Commit()}

func (database *Database) RollbackSessionHistory(ctx context.Context,write sessionflow.RollbackWrite)(session.Session,error){transaction,err:=database.database.BeginTx(ctx,nil);if err!=nil{return session.Session{},err};defer transaction.Rollback();var open int;if err:=transaction.QueryRowContext(ctx,`SELECT count(*) FROM runs WHERE session_id=? AND status!='finished'`,write.SessionID.String()).Scan(&open);err!=nil{return session.Session{},err};if open>0{return session.Session{},protocol.ErrSessionBusy};for _,id:=range write.DropRootRunIDs{if _,err:=transaction.ExecContext(ctx,`DELETE FROM runs WHERE id=? AND session_id=? AND parent_run_id IS NULL`,id,write.SessionID.String());err!=nil{return session.Session{},err}};if _,err:=transaction.ExecContext(ctx,`DELETE FROM goals WHERE session_id=?`,write.SessionID.String());err!=nil{return session.Session{},err};if write.Plan!=nil{if _,err:=transaction.ExecContext(ctx,`DELETE FROM plans WHERE session_id=?`,write.SessionID.String());err!=nil{return session.Session{},err};if err:=insertPlanTx(ctx,transaction,*write.Plan);err!=nil{return session.Session{},err}};if _,err:=transaction.ExecContext(ctx,`UPDATE sessions SET revision=revision+1,updated_at=? WHERE id=?`,encodeTime(write.Now),write.SessionID.String());err!=nil{return session.Session{},err};value,err:=scanSession(transaction.QueryRowContext(ctx,`SELECT id,title,workspace_path,model,favorite,revision,created_at,updated_at FROM sessions WHERE id=?`,write.SessionID.String()));if err!=nil{return session.Session{},err};if err:=transaction.Commit();err!=nil{return session.Session{},err};return value,nil}

func (database *Database) ReplaceSessionMaterial(ctx context.Context,write sessionflow.ImportWrite)error{material:=write.Material;transaction,err:=database.database.BeginTx(ctx,nil);if err!=nil{return err};defer transaction.Rollback();var open int;if err:=transaction.QueryRowContext(ctx,`SELECT count(*) FROM runs WHERE session_id=? AND status!='finished'`,material.Session.ID().String()).Scan(&open);err!=nil{return err};if open>0{return protocol.ErrSessionBusy};if _,err:=transaction.ExecContext(ctx,`INSERT INTO sessions(id,title,workspace_path,model,favorite,revision,created_at,updated_at)VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id)DO UPDATE SET title=excluded.title,workspace_path=excluded.workspace_path,model=excluded.model,favorite=excluded.favorite,revision=excluded.revision,created_at=excluded.created_at,updated_at=excluded.updated_at`,material.Session.ID().String(),material.Session.Title(),material.Session.Workspace().Path(),material.Session.Model(),material.Session.Favorite(),material.Session.Revision(),encodeTime(material.Session.CreatedAt()),encodeTime(material.Session.UpdatedAt()));err!=nil{return err};if _,err:=transaction.ExecContext(ctx,`DELETE FROM runs WHERE session_id=?`,material.Session.ID().String());err!=nil{return err};if _,err:=transaction.ExecContext(ctx,`DELETE FROM plans WHERE session_id=?`,material.Session.ID().String());err!=nil{return err};if _,err:=transaction.ExecContext(ctx,`DELETE FROM goals WHERE session_id=?`,material.Session.ID().String());err!=nil{return err};for _,record:=range material.Runs{if err:=insertRun(ctx,transaction,record);err!=nil{return err}};for _,item:=range material.Items{if err:=insertItem(ctx,transaction,item);err!=nil{return err}};for _,message:=range material.Messages{if err:=insertConversationMessage(ctx,transaction,message);err!=nil{return err}};if material.Plan.Revision>0||len(material.Plan.Steps)>0{if err:=insertPlanTx(ctx,transaction,material.Plan);err!=nil{return err}};for _,result:=range material.ToolResults{if err:=insertToolResult(ctx,transaction,result);err!=nil{return err}};return transaction.Commit()}

func insertSessionTx(ctx context.Context,transaction *sql.Tx,value session.Session)error{_,err:=transaction.ExecContext(ctx,`INSERT INTO sessions(id,title,workspace_path,model,favorite,revision,created_at,updated_at)VALUES(?,?,?,?,?,?,?,?)`,value.ID().String(),value.Title(),value.Workspace().Path(),value.Model(),value.Favorite(),value.Revision(),encodeTime(value.CreatedAt()),encodeTime(value.UpdatedAt()));return err}
func insertPlanTx(ctx context.Context,transaction *sql.Tx,value protocol.Plan)error{body,err:=json.Marshal(value);if err!=nil{return err};var updated any;if !value.UpdatedAt.IsZero(){updated=encodeTime(value.UpdatedAt)};_,err=transaction.ExecContext(ctx,`INSERT INTO plans(session_id,revision,body,updated_at)VALUES(?,?,?,?)`,value.SessionID,value.Revision,string(body),updated);return err}
