// Code generated by cmd/contractgen. DO NOT EDIT.

package protocol

func (value PageQuery) ValidateWire() error {
	return collectWireViolations("PageQuery",
		nonNegativeNumber("limit", value.Limit),
	)
}

func (value GetSessionRequest) ValidateWire() error {
	return collectWireViolations("GetSessionRequest",
		requiredText("sessionId", value.SessionID),
	)
}

func (value UpdateSessionRequest) ValidateWire() error {
	return collectWireViolations("UpdateSessionRequest",
		requiredText("sessionId", value.SessionID),
		positiveNumber("expectedRevision", value.ExpectedRevision),
	)
}

func (value DeleteSessionRequest) ValidateWire() error {
	return collectWireViolations("DeleteSessionRequest",
		requiredText("sessionId", value.SessionID),
	)
}

func (value ForkSessionRequest) ValidateWire() error {
	return collectWireViolations("ForkSessionRequest",
		requiredText("sessionId", value.SessionID),
	)
}

func (value RollbackSessionRequest) ValidateWire() error {
	return collectWireViolations("RollbackSessionRequest",
		requiredText("sessionId", value.SessionID),
		closedEnum("restoreType", string(value.RestoreType), []string{"history", "files", "both"}, true),
	)
}

func (value ExportSessionRequest) ValidateWire() error {
	return collectWireViolations("ExportSessionRequest",
		requiredText("sessionId", value.SessionID),
		closedEnum("format", string(value.Format), []string{"md", "json"}, true),
	)
}

func (value ImportSessionRequest) ValidateWire() error {
	return collectWireViolations("ImportSessionRequest",
		requiredText("artifact.session.id", value.Artifact.Session.ID),
	)
}

func (value StartRunRequest) ValidateWire() error {
	return collectWireViolations("StartRunRequest",
		requiredText("sessionId", value.SessionID),
		requiredItems("input", value.Input),
		nonNegativeNumber("maxTotalTokens", value.MaxTotalTokens),
		nonNegativeNumber("maxSteps", value.MaxSteps),
		nonNegativeNumber("maxBudgetUsd", value.MaxBudgetUSD),
	)
}

func (value ResumeRunRequest) ValidateWire() error {
	return collectWireViolations("ResumeRunRequest",
		requiredText("runId", value.RunID),
		nonEmptyItems("input", value.Input),
	)
}

func (value SubscribeRunRequest) ValidateWire() error {
	return collectWireViolations("SubscribeRunRequest",
		requiredText("runId", value.RunID),
		requiredText("segmentId", value.SegmentID),
	)
}

func (value CancelRunRequest) ValidateWire() error {
	return collectWireViolations("CancelRunRequest",
		requiredText("runId", value.RunID),
	)
}

func (value SteerRunRequest) ValidateWire() error {
	return collectWireViolations("SteerRunRequest",
		requiredText("runId", value.RunID),
		requiredText("expectedSegmentId", value.ExpectedSegmentID),
		requiredItems("input", value.Input),
	)
}

func (value GetRunRequest) ValidateWire() error {
	return collectWireViolations("GetRunRequest",
		requiredText("runId", value.RunID),
	)
}

func (value ListRunsRequest) ValidateWire() error {
	return collectWireViolations("ListRunsRequest",
		nonEmptyItems("statuses", value.Statuses),
		uniqueItems("statuses", value.Statuses),
		closedEnumItems("statuses", value.Statuses, []string{"running", "waiting", "finished"}),
	)
}

func (value GetPlanRequest) ValidateWire() error {
	return collectWireViolations("GetPlanRequest",
		requiredText("sessionId", value.SessionID),
	)
}

func (value ListItemsRequest) ValidateWire() error {
	return collectWireViolations("ListItemsRequest",
		requiredText("scope.type", string(value.Scope.Type)),
		closedEnum("order", string(value.Order), []string{"asc", "desc"}, true),
	)
}

func (value GetDiffRequest) ValidateWire() error {
	return collectWireViolations("GetDiffRequest",
		nonNegativeNumber("limit", value.Limit),
		closedEnum("mode", string(value.Mode), []string{"worktree", "base"}, true),
		closedEnum("format", string(value.Format), []string{"rows", "raw"}, true),
	)
}

func (value GetFileHeadRequest) ValidateWire() error {
	return collectWireViolations("GetFileHeadRequest",
		requiredText("path", value.Path),
		nonNegativeNumber("lines", value.Lines),
	)
}

func (value GrepRequest) ValidateWire() error {
	return collectWireViolations("GrepRequest",
		requiredText("query", value.Query),
		nonNegativeNumber("limit", value.Limit),
	)
}

func (value ReadFileRequest) ValidateWire() error {
	return collectWireViolations("ReadFileRequest",
		requiredText("path", value.Path),
		nonNegativeNumber("startLine", value.StartLine),
		nonNegativeNumber("endLine", value.EndLine),
		nonNegativeNumber("maxBytes", value.MaxBytes),
	)
}

func (value RuntimeSubscribeRequest) ValidateWire() error {
	return collectWireViolations("RuntimeSubscribeRequest",
		requiredItems("topics", value.Topics),
		uniqueItems("topics", value.Topics),
		closedEnumItems("topics", value.Topics, []string{"files.changed", "skills.changed", "mcp.changed", "schedules.changed", "sessions.changed", "runs.changed", "state.changed", "goals.changed", "interrupts.changed"}),
	)
}

func (value SkillNameRequest) ValidateWire() error {
	return collectWireViolations("SkillNameRequest",
		requiredText("name", value.Name),
	)
}

func (value SkillProposalRef) ValidateWire() error {
	return collectWireViolations("SkillProposalRef",
		requiredText("name", value.Name),
		requiredText("revision", value.Revision),
		closedEnum("scope", string(value.Scope), []string{"project", "user"}, false),
	)
}

func (value MCPServerCandidate) ValidateWire() error {
	return collectWireViolations("MCPServerCandidate",
		requiredText("name", value.Name),
		nonNegativeNumber("timeoutSeconds", value.TimeoutSeconds),
		uniqueItems("disabledTools", value.DisabledTools),
		uniqueItems("autoApproveTools", value.AutoApproveTools),
	)
}

func (value UpdateMCPServerRequest) ValidateWire() error {
	return collectWireViolations("UpdateMCPServerRequest",
		requiredText("server", value.Server),
		optionalNonNegativeNumber("timeoutSeconds", value.TimeoutSeconds),
		optionalUniqueItems("disabledTools", value.DisabledTools),
		optionalUniqueItems("autoApproveTools", value.AutoApproveTools),
	)
}

func (value MCPServerRequest) ValidateWire() error {
	return collectWireViolations("MCPServerRequest",
		requiredText("server", value.Server),
	)
}

func (value CreateMCPAuthorizationAttemptRequest) ValidateWire() error {
	return collectWireViolations("CreateMCPAuthorizationAttemptRequest",
		requiredText("server", value.Server),
	)
}

func (value MCPAuthorizationAttemptRequest) ValidateWire() error {
	return collectWireViolations("MCPAuthorizationAttemptRequest",
		requiredText("attemptId", value.AttemptID),
	)
}

func (value SetHookTrustRequest) ValidateWire() error {
	return collectWireViolations("SetHookTrustRequest",
		requiredText("projectRoot", value.ProjectRoot),
	)
}

func (value SetApprovalModeRequest) ValidateWire() error {
	return collectWireViolations("SetApprovalModeRequest",
		closedEnum("mode", string(value.Mode), []string{"safe", "balanced", "yolo"}, false),
	)
}

func (value ListApprovalRulesRequest) ValidateWire() error {
	return collectWireViolations("ListApprovalRulesRequest",
		requiredText("sessionId", value.SessionID),
	)
}

func (value ForgetApprovalRuleRequest) ValidateWire() error {
	return collectWireViolations("ForgetApprovalRuleRequest",
		requiredText("id", value.ID),
	)
}

func (value CreateScheduleRequest) ValidateWire() error {
	return collectWireViolations("CreateScheduleRequest",
		requiredText("prompt", value.Prompt),
		requiredText("cron", value.Cron),
	)
}

func (value UpdateScheduleRequest) ValidateWire() error {
	return collectWireViolations("UpdateScheduleRequest",
		requiredText("id", value.ID),
		positiveNumber("expectedRevision", value.ExpectedRevision),
		optionalText("prompt", value.Prompt),
		optionalText("cron", value.Cron),
	)
}

func (value DeleteScheduleRequest) ValidateWire() error {
	return collectWireViolations("DeleteScheduleRequest",
		requiredText("id", value.ID),
	)
}

func (value RunScheduleNowRequest) ValidateWire() error {
	return collectWireViolations("RunScheduleNowRequest",
		requiredText("id", value.ID),
	)
}

func (value StartGoalRequest) ValidateWire() error {
	return collectWireViolations("StartGoalRequest",
		requiredText("sessionId", value.SessionID),
		requiredText("objective", value.Objective),
	)
}

func (value GoalRequest) ValidateWire() error {
	return collectWireViolations("GoalRequest",
		requiredText("sessionId", value.SessionID),
	)
}

func (value CodebaseSearchRequest) ValidateWire() error {
	return collectWireViolations("CodebaseSearchRequest",
		requiredText("query", value.Query),
		nonNegativeNumber("limit", value.Limit),
	)
}

func (value UpdateProviderRequest) ValidateWire() error {
	return collectWireViolations("UpdateProviderRequest",
		requiredText("provider", value.Provider),
	)
}

func (value TestProviderRequest) ValidateWire() error {
	return collectWireViolations("TestProviderRequest",
		requiredText("provider", value.Provider),
	)
}

func (value InvokeToolRequest) ValidateWire() error {
	return collectWireViolations("InvokeToolRequest",
		requiredText("name", value.Name),
	)
}

func (value SessionUsageRequest) ValidateWire() error {
	return collectWireViolations("SessionUsageRequest",
		requiredText("sessionId", value.SessionID),
	)
}

func (value UsageSummaryRequest) ValidateWire() error {
	return collectWireViolations("UsageSummaryRequest",
		nonNegativeNumber("sinceDays", value.SinceDays),
	)
}

func (value GetMemoryRequest) ValidateWire() error {
	return collectWireViolations("GetMemoryRequest",
		closedEnum("scope", string(value.Scope), []string{"cwd", "projectRoot", "home"}, false),
	)
}

func (value UpdateMemoryRequest) ValidateWire() error {
	return collectWireViolations("UpdateMemoryRequest",
		closedEnum("scope", string(value.Scope), []string{"cwd", "projectRoot", "home"}, false),
	)
}

func (value AgentMemoryListRequest) ValidateWire() error {
	return collectWireViolations("AgentMemoryListRequest",
		closedEnum("scope", string(value.Scope), []string{"project", "user"}, false),
		requiredWhen(wireFieldEquals(value, "scope", "project"), "workspace", value),
		forbiddenWhen(wireFieldEquals(value, "scope", "user"), "workspace", value),
	)
}

func (value AgentMemoryReviewRequest) ValidateWire() error {
	return collectWireViolations("AgentMemoryReviewRequest",
		requiredText("id", value.ID),
		closedEnum("decision", string(value.Decision), []string{"approve", "reject"}, false),
	)
}

func (value AgentMemoryUpdateRequest) ValidateWire() error {
	return collectWireViolations("AgentMemoryUpdateRequest",
		requiredText("id", value.ID),
	)
}

func (value AgentMemoryItemRequest) ValidateWire() error {
	return collectWireViolations("AgentMemoryItemRequest",
		requiredText("id", value.ID),
	)
}

func (value AgentMemoryAddRequest) ValidateWire() error {
	return collectWireViolations("AgentMemoryAddRequest",
		requiredText("content", value.Content),
		closedEnum("scope", string(value.Scope), []string{"project", "user"}, false),
		requiredWhen(wireFieldEquals(value, "scope", "project"), "workspace", value),
		forbiddenWhen(wireFieldEquals(value, "scope", "user"), "workspace", value),
	)
}

func (value FeedbackRequest) ValidateWire() error {
	return collectWireViolations("FeedbackRequest",
		closedEnum("rating", string(value.Rating), []string{"positive", "negative"}, true),
	)
}

func (value ProblemData) ValidateWire() error {
	return collectWireViolations("ProblemData",
		optionalPositiveScalarNumber("retryAfterSeconds", value.RetryAfterSeconds),
		nonEmptyItems("requiredCapabilities", value.RequiredCapabilities),
		uniqueItems("requiredCapabilities", value.RequiredCapabilities),
		unionTag("type", string(value.Type), []string{"agent_stuck", "capability_not_negotiated", "checkpoint_unavailable", "child_run_canceled", "denied_by_user", "idempotency_conflict", "idempotency_in_progress", "internal_error", "interrupt_not_open", "invalid_api_key", "invalid_params", "invalid_protocol_version", "invalid_request", "item_not_found", "mcp_authorization_attempt_not_found", "mcp_authorization_failed", "mcp_authorization_required", "mcp_dial_failed", "mcp_server_already_exists", "mcp_server_disabled", "mcp_server_not_found", "method_not_found", "path_outside_root", "provider_error", "provider_not_configured", "provider_rejected", "provider_test_failed", "provider_unavailable", "rate_limited", "replay_cursor_invalid", "replay_unavailable", "revision_conflict", "run_finished", "run_lost", "run_not_found", "run_not_root", "run_waiting", "session_busy", "session_has_active_run", "session_not_found", "stale_segment", "timeout", "tool_failed", "unsupported_mime", "vcs_unavailable", "workspace_unavailable"}, "^plugin:[a-z0-9][a-z0-9._-]*/[a-z0-9][a-z0-9._-]*$"),
		forbiddenWhen(wireFieldEquals(value, "type", "agent_stuck"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agent_stuck"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agent_stuck"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agent_stuck"), "activeRun", value),
		requiredWhen(wireFieldEquals(value, "type", "capability_not_negotiated"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "capability_not_negotiated"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "capability_not_negotiated"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "capability_not_negotiated"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "checkpoint_unavailable"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "checkpoint_unavailable"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "checkpoint_unavailable"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "checkpoint_unavailable"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "child_run_canceled"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "child_run_canceled"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "child_run_canceled"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "child_run_canceled"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "denied_by_user"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "denied_by_user"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "denied_by_user"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "denied_by_user"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "idempotency_conflict"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "idempotency_conflict"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "idempotency_conflict"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "idempotency_conflict"), "activeRun", value),
		requiredWhen(wireFieldEquals(value, "type", "idempotency_in_progress"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "idempotency_in_progress"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "idempotency_in_progress"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "idempotency_in_progress"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "internal_error"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "internal_error"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "internal_error"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "internal_error"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "interrupt_not_open"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "interrupt_not_open"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "interrupt_not_open"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "interrupt_not_open"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "invalid_api_key"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "invalid_api_key"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "invalid_api_key"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "invalid_api_key"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "invalid_params"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "invalid_params"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "invalid_params"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "invalid_protocol_version"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "invalid_protocol_version"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "invalid_protocol_version"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "invalid_protocol_version"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "invalid_request"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "invalid_request"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "invalid_request"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "invalid_request"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item_not_found"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item_not_found"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item_not_found"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item_not_found"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_authorization_attempt_not_found"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_authorization_attempt_not_found"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_authorization_attempt_not_found"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_authorization_attempt_not_found"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_authorization_failed"), "detail", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_authorization_failed"), "docUrl", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_authorization_failed"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_authorization_failed"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_authorization_failed"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_authorization_failed"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_authorization_required"), "detail", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_authorization_required"), "docUrl", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_authorization_required"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_authorization_required"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_authorization_required"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_authorization_required"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_dial_failed"), "detail", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_dial_failed"), "docUrl", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_dial_failed"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_dial_failed"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_dial_failed"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_dial_failed"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_server_already_exists"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_server_already_exists"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_server_already_exists"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_server_already_exists"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_server_disabled"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_server_disabled"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_server_disabled"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_server_disabled"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_server_not_found"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_server_not_found"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_server_not_found"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp_server_not_found"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "method_not_found"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "method_not_found"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "method_not_found"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "method_not_found"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "path_outside_root"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "path_outside_root"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "path_outside_root"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "path_outside_root"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_error"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_error"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_error"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_error"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_not_configured"), "detail", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_not_configured"), "docUrl", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_not_configured"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_not_configured"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_not_configured"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_not_configured"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_rejected"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_rejected"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_rejected"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_rejected"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_test_failed"), "detail", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_test_failed"), "docUrl", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_test_failed"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_test_failed"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_test_failed"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_test_failed"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_unavailable"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_unavailable"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "provider_unavailable"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "rate_limited"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "rate_limited"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "rate_limited"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "replay_cursor_invalid"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "replay_cursor_invalid"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "replay_cursor_invalid"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "replay_cursor_invalid"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "replay_unavailable"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "replay_unavailable"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "replay_unavailable"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "replay_unavailable"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "revision_conflict"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "revision_conflict"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "revision_conflict"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "revision_conflict"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run_finished"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run_finished"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run_finished"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run_finished"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run_lost"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run_lost"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run_lost"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run_lost"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run_not_found"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run_not_found"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run_not_found"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run_not_found"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run_not_root"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run_not_root"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run_not_root"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run_not_root"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run_waiting"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run_waiting"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run_waiting"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run_waiting"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "session_busy"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "session_busy"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "session_busy"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "session_busy"), "activeRun", value),
		requiredWhen(wireFieldEquals(value, "type", "session_has_active_run"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "session_has_active_run"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "session_has_active_run"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "session_has_active_run"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "session_not_found"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "session_not_found"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "session_not_found"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "session_not_found"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "stale_segment"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "stale_segment"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "stale_segment"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "stale_segment"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "timeout"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "timeout"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "timeout"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "tool_failed"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "tool_failed"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "tool_failed"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "tool_failed"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "unsupported_mime"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "unsupported_mime"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "unsupported_mime"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "unsupported_mime"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "vcs_unavailable"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "vcs_unavailable"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "vcs_unavailable"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "vcs_unavailable"), "activeRun", value),
		forbiddenWhen(wireFieldEquals(value, "type", "workspace_unavailable"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldEquals(value, "type", "workspace_unavailable"), "retryAfterSeconds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "workspace_unavailable"), "errors", value),
		forbiddenWhen(wireFieldEquals(value, "type", "workspace_unavailable"), "activeRun", value),
		forbiddenWhen(wireFieldMatches(value, "type", "^plugin:[a-z0-9][a-z0-9._-]*/[a-z0-9][a-z0-9._-]*$"), "requiredCapabilities", value),
		forbiddenWhen(wireFieldMatches(value, "type", "^plugin:[a-z0-9][a-z0-9._-]*/[a-z0-9][a-z0-9._-]*$"), "errors", value),
		forbiddenWhen(wireFieldMatches(value, "type", "^plugin:[a-z0-9][a-z0-9._-]*/[a-z0-9][a-z0-9._-]*$"), "activeRun", value),
	)
}

func (value CancelRunResponse) ValidateWire() error {
	return collectWireViolations("CancelRunResponse",
		closedEnum("type", string(value.Type), []string{"root", "child"}, false),
		requiredWhen(wireFieldEquals(value, "type", "root"), "run", value),
		forbiddenWhen(wireFieldEquals(value, "type", "root"), "rootRun", value),
		requiredWhen(wireFieldEquals(value, "type", "child"), "run", value),
		requiredWhen(wireFieldEquals(value, "type", "child"), "rootRun", value),
	)
}

func (value RunOutcome) ValidateWire() error {
	return collectWireViolations("RunOutcome",
		closedEnum("type", string(value.Type), []string{"completed", "error", "maxSteps", "maxBudget", "canceled"}, false),
		forbiddenWhen(wireFieldEquals(value, "type", "completed"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "completed"), "detail", value),
		requiredWhen(wireFieldEquals(value, "type", "error"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "error"), "detail", value),
		forbiddenWhen(wireFieldEquals(value, "type", "maxSteps"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "maxBudget"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "canceled"), "error", value),
		requiredWhen(wireFieldEquals(value, "type", "error"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "error"), "detail", value),
	)
}

func (value SegmentOutcome) ValidateWire() error {
	return collectWireViolations("SegmentOutcome",
		closedEnum("type", string(value.Type), []string{"interrupt", "suspended", "completed", "error", "maxSteps", "maxBudget", "canceled"}, false),
		requiredWhen(wireFieldEquals(value, "type", "interrupt"), "interrupts", value),
		forbiddenWhen(wireFieldEquals(value, "type", "interrupt"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "interrupt"), "detail", value),
		forbiddenWhen(wireFieldEquals(value, "type", "suspended"), "interrupts", value),
		forbiddenWhen(wireFieldEquals(value, "type", "suspended"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "suspended"), "detail", value),
		forbiddenWhen(wireFieldEquals(value, "type", "completed"), "interrupts", value),
		forbiddenWhen(wireFieldEquals(value, "type", "completed"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "completed"), "detail", value),
		requiredWhen(wireFieldEquals(value, "type", "error"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "error"), "interrupts", value),
		forbiddenWhen(wireFieldEquals(value, "type", "error"), "detail", value),
		forbiddenWhen(wireFieldEquals(value, "type", "maxSteps"), "interrupts", value),
		forbiddenWhen(wireFieldEquals(value, "type", "maxSteps"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "maxBudget"), "interrupts", value),
		forbiddenWhen(wireFieldEquals(value, "type", "maxBudget"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "canceled"), "interrupts", value),
		forbiddenWhen(wireFieldEquals(value, "type", "canceled"), "error", value),
		requiredWhen(wireFieldEquals(value, "type", "error"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "error"), "detail", value),
		requiredWhen(wireFieldEquals(value, "type", "interrupt"), "interrupts", value),
		forbiddenWhen(wireFieldEquals(value, "type", "interrupt"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "interrupt"), "detail", value),
		forbiddenWhen(wireFieldEquals(value, "type", "suspended"), "interrupts", value),
		forbiddenWhen(wireFieldEquals(value, "type", "suspended"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "suspended"), "detail", value),
	)
}

func (value ArtifactState) ValidateWire() error {
	return collectWireViolations("ArtifactState",
		closedEnum("type", string(value.Type), []string{"plan"}, false),
		requiredWhen(wireFieldEquals(value, "type", "plan"), "plan", value),
	)
}

func (value Item) ValidateWire() error {
	return collectWireViolations("Item",
		optionalNonNegativeNumber("durationMs", value.DurationMs),
		closedEnum("status", string(value.Status), []string{"running", "completed", "incomplete"}, false),
		closedEnum("type", string(value.Type), []string{"userMessage", "agentMessage", "reasoning", "question", "toolCall", "compaction"}, false),
		closedEnum("safetyClass", string(value.SafetyClass), []string{"safe", "write", "exec", "network"}, true),
		requiredWhen(wireFieldEquals(value, "type", "userMessage"), "id", value),
		requiredWhen(wireFieldEquals(value, "type", "userMessage"), "runId", value),
		requiredWhen(wireFieldEquals(value, "type", "userMessage"), "status", value),
		requiredWhen(wireFieldEquals(value, "type", "userMessage"), "createdAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "text", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "redacted", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "question", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "startedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "finishedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "durationMs", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "tool", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "safetyClass", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "summary", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "droppedMessages", value),
		requiredWhen(wireFieldEquals(value, "type", "agentMessage"), "id", value),
		requiredWhen(wireFieldEquals(value, "type", "agentMessage"), "runId", value),
		requiredWhen(wireFieldEquals(value, "type", "agentMessage"), "status", value),
		requiredWhen(wireFieldEquals(value, "type", "agentMessage"), "createdAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "text", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "redacted", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "question", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "startedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "finishedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "durationMs", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "tool", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "safetyClass", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "summary", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "droppedMessages", value),
		requiredWhen(wireFieldEquals(value, "type", "reasoning"), "id", value),
		requiredWhen(wireFieldEquals(value, "type", "reasoning"), "runId", value),
		requiredWhen(wireFieldEquals(value, "type", "reasoning"), "status", value),
		requiredWhen(wireFieldEquals(value, "type", "reasoning"), "createdAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "content", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "question", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "startedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "finishedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "durationMs", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "tool", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "safetyClass", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "summary", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "droppedMessages", value),
		requiredWhen(wireFieldEquals(value, "type", "question"), "id", value),
		requiredWhen(wireFieldEquals(value, "type", "question"), "runId", value),
		requiredWhen(wireFieldEquals(value, "type", "question"), "status", value),
		requiredWhen(wireFieldEquals(value, "type", "question"), "createdAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "content", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "text", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "redacted", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "startedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "finishedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "durationMs", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "tool", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "safetyClass", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "summary", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "droppedMessages", value),
		requiredWhen(wireFieldEquals(value, "type", "toolCall"), "id", value),
		requiredWhen(wireFieldEquals(value, "type", "toolCall"), "runId", value),
		requiredWhen(wireFieldEquals(value, "type", "toolCall"), "status", value),
		requiredWhen(wireFieldEquals(value, "type", "toolCall"), "createdAt", value),
		requiredWhen(wireFieldEquals(value, "type", "toolCall"), "startedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolCall"), "content", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolCall"), "text", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolCall"), "redacted", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolCall"), "question", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolCall"), "summary", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolCall"), "droppedMessages", value),
		requiredWhen(wireFieldEquals(value, "type", "compaction"), "id", value),
		requiredWhen(wireFieldEquals(value, "type", "compaction"), "runId", value),
		requiredWhen(wireFieldEquals(value, "type", "compaction"), "status", value),
		requiredWhen(wireFieldEquals(value, "type", "compaction"), "createdAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "compaction"), "content", value),
		forbiddenWhen(wireFieldEquals(value, "type", "compaction"), "text", value),
		forbiddenWhen(wireFieldEquals(value, "type", "compaction"), "redacted", value),
		forbiddenWhen(wireFieldEquals(value, "type", "compaction"), "question", value),
		forbiddenWhen(wireFieldEquals(value, "type", "compaction"), "startedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "compaction"), "finishedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "compaction"), "durationMs", value),
		forbiddenWhen(wireFieldEquals(value, "type", "compaction"), "tool", value),
		forbiddenWhen(wireFieldEquals(value, "type", "compaction"), "safetyClass", value),
		forbiddenWhen(wireFieldEquals(value, "type", "compaction"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolCall") && wireFieldEquals(value, "status", "running"), "finishedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolCall") && wireFieldEquals(value, "status", "running"), "durationMs", value),
		requiredWhen(wireFieldEquals(value, "type", "toolCall") && wireFieldEquals(value, "status", "completed"), "finishedAt", value),
		requiredWhen(wireFieldEquals(value, "type", "toolCall") && wireFieldEquals(value, "status", "completed"), "durationMs", value),
		requiredWhen(wireFieldEquals(value, "type", "toolCall") && wireFieldEquals(value, "status", "incomplete"), "finishedAt", value),
		requiredWhen(wireFieldEquals(value, "type", "toolCall") && wireFieldEquals(value, "status", "incomplete"), "durationMs", value),
	)
}

func (value ItemDelta) ValidateWire() error {
	return collectWireViolations("ItemDelta",
		closedEnum("type", string(value.Type), []string{"content", "reasoning", "toolArguments", "toolOutput"}, false),
		requiredWhen(wireFieldEquals(value, "type", "content"), "text", value),
		forbiddenWhen(wireFieldEquals(value, "type", "content"), "argumentsTextDelta", value),
		requiredWhen(wireFieldEquals(value, "type", "reasoning"), "text", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "index", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "argumentsTextDelta", value),
		requiredWhen(wireFieldEquals(value, "type", "toolArguments"), "argumentsTextDelta", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolArguments"), "text", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolArguments"), "index", value),
		requiredWhen(wireFieldEquals(value, "type", "toolOutput"), "text", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolOutput"), "index", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolOutput"), "argumentsTextDelta", value),
	)
}

func (value CapabilityRequirement) ValidateWire() error {
	return collectWireViolations("CapabilityRequirement",
		requiredText("name", value.Name),
		closedEnum("type", string(value.Type), []string{"feature", "interruptType", "runtimeTopic", "stateSnapshot"}, false),
		requiredWhen(wireFieldEquals(value, "type", "feature"), "name", value),
		requiredWhen(wireFieldEquals(value, "type", "interruptType"), "name", value),
		requiredWhen(wireFieldEquals(value, "type", "runtimeTopic"), "name", value),
		requiredWhen(wireFieldEquals(value, "type", "stateSnapshot"), "name", value),
	)
}

func (value StateSnapshot) ValidateWire() error {
	return collectWireViolations("StateSnapshot",
		closedEnum("type", string(value.Type), []string{"plan"}, false),
		requiredWhen(wireFieldEquals(value, "type", "plan"), "sessionId", value),
		requiredWhen(wireFieldEquals(value, "type", "plan"), "revision", value),
		requiredWhen(wireFieldEquals(value, "type", "plan"), "plan", value),
	)
}

func (value ItemListScope) ValidateWire() error {
	return collectWireViolations("ItemListScope",
		closedEnum("type", string(value.Type), []string{"session", "run"}, false),
		requiredWhen(wireFieldEquals(value, "type", "session"), "sessionId", value),
		forbiddenWhen(wireFieldEquals(value, "type", "session"), "runId", value),
		forbiddenWhen(wireFieldEquals(value, "type", "session"), "includeDescendants", value),
		requiredWhen(wireFieldEquals(value, "type", "run"), "runId", value),
		forbiddenWhen(wireFieldEquals(value, "type", "run"), "sessionId", value),
	)
}

func (value ContentBlock) ValidateWire() error {
	return collectWireViolations("ContentBlock",
		closedEnum("type", string(value.Type), []string{"text", "image"}, false),
		requiredWhen(wireFieldEquals(value, "type", "text"), "text", value),
		forbiddenWhen(wireFieldEquals(value, "type", "text"), "mime", value),
		forbiddenWhen(wireFieldEquals(value, "type", "text"), "data", value),
		requiredWhen(wireFieldEquals(value, "type", "image"), "mime", value),
		requiredWhen(wireFieldEquals(value, "type", "image"), "data", value),
		forbiddenWhen(wireFieldEquals(value, "type", "image"), "text", value),
	)
}

func (value QuestionField) ValidateWire() error {
	return collectWireViolations("QuestionField",
		requiredText("prompt", value.Prompt),
		maxLength("header", value.Header, 12),
		optionalMinItems("options", value.Options, 2),
		closedEnum("type", string(value.Type), []string{"text", "choice"}, false),
		requiredWhen(wireFieldEquals(value, "type", "text"), "prompt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "text"), "options", value),
		forbiddenWhen(wireFieldEquals(value, "type", "text"), "multiple", value),
		forbiddenWhen(wireFieldEquals(value, "type", "text"), "allowCustom", value),
		requiredWhen(wireFieldEquals(value, "type", "choice"), "prompt", value),
		requiredWhen(wireFieldEquals(value, "type", "choice"), "options", value),
	)
}

func (value ArtifactQuestionField) ValidateWire() error {
	return collectWireViolations("ArtifactQuestionField",
		requiredText("prompt", value.Prompt),
		maxLength("header", value.Header, 12),
		optionalMinItems("options", value.Options, 2),
		closedEnum("type", string(value.Type), []string{"text", "choice"}, false),
		requiredWhen(wireFieldEquals(value, "type", "text"), "prompt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "text"), "options", value),
		forbiddenWhen(wireFieldEquals(value, "type", "text"), "multiple", value),
		forbiddenWhen(wireFieldEquals(value, "type", "text"), "allowCustom", value),
		requiredWhen(wireFieldEquals(value, "type", "choice"), "prompt", value),
		requiredWhen(wireFieldEquals(value, "type", "choice"), "options", value),
	)
}

func (value ProviderConfigChange) ValidateWire() error {
	return collectWireViolations("ProviderConfigChange",
		optionalText("value", value.Value),
		closedEnum("type", string(value.Type), []string{"set", "clear"}, false),
		requiredWhen(wireFieldEquals(value, "type", "set"), "value", value),
		forbiddenWhen(wireFieldEquals(value, "type", "clear"), "value", value),
	)
}

func (value McpConnection) ValidateWire() error {
	return collectWireViolations("McpConnection",
		requiredText("url", value.URL),
		requiredText("command", value.Command),
		closedEnum("type", string(value.Type), []string{"stdio", "streamableHttp"}, false),
		requiredWhen(wireFieldEquals(value, "type", "streamableHttp"), "url", value),
		forbiddenWhen(wireFieldEquals(value, "type", "streamableHttp"), "command", value),
		forbiddenWhen(wireFieldEquals(value, "type", "streamableHttp"), "args", value),
		forbiddenWhen(wireFieldEquals(value, "type", "streamableHttp"), "envMasked", value),
		forbiddenWhen(wireFieldEquals(value, "type", "streamableHttp"), "dir", value),
		requiredWhen(wireFieldEquals(value, "type", "stdio"), "command", value),
		forbiddenWhen(wireFieldEquals(value, "type", "stdio"), "url", value),
		forbiddenWhen(wireFieldEquals(value, "type", "stdio"), "authorizationMasked", value),
		forbiddenWhen(wireFieldEquals(value, "type", "stdio"), "headersMasked", value),
	)
}

func (value McpConnectionInput) ValidateWire() error {
	return collectWireViolations("McpConnectionInput",
		requiredText("url", value.URL),
		requiredText("command", value.Command),
		closedEnum("type", string(value.Type), []string{"stdio", "streamableHttp"}, false),
		requiredWhen(wireFieldEquals(value, "type", "streamableHttp"), "url", value),
		forbiddenWhen(wireFieldEquals(value, "type", "streamableHttp"), "command", value),
		forbiddenWhen(wireFieldEquals(value, "type", "streamableHttp"), "args", value),
		forbiddenWhen(wireFieldEquals(value, "type", "streamableHttp"), "env", value),
		forbiddenWhen(wireFieldEquals(value, "type", "streamableHttp"), "dir", value),
		requiredWhen(wireFieldEquals(value, "type", "stdio"), "command", value),
		forbiddenWhen(wireFieldEquals(value, "type", "stdio"), "url", value),
		forbiddenWhen(wireFieldEquals(value, "type", "stdio"), "authorization", value),
		forbiddenWhen(wireFieldEquals(value, "type", "stdio"), "headers", value),
	)
}

func (value McpAuthorizationChange) ValidateWire() error {
	return collectWireViolations("McpAuthorizationChange",
		requiredText("value", value.Value),
		closedEnum("type", string(value.Type), []string{"set", "clear"}, false),
		requiredWhen(wireFieldEquals(value, "type", "set"), "value", value),
		forbiddenWhen(wireFieldEquals(value, "type", "clear"), "value", value),
	)
}

func (value McpHeadersChange) ValidateWire() error {
	return collectWireViolations("McpHeadersChange",
		nonEmptyProperties("value", value.Value),
		closedEnum("type", string(value.Type), []string{"set", "clear"}, false),
		requiredWhen(wireFieldEquals(value, "type", "set"), "value", value),
		forbiddenWhen(wireFieldEquals(value, "type", "clear"), "value", value),
	)
}

func (value McpEnvironmentChange) ValidateWire() error {
	return collectWireViolations("McpEnvironmentChange",
		nonEmptyProperties("value", value.Value),
		closedEnum("type", string(value.Type), []string{"set", "clear"}, false),
		requiredWhen(wireFieldEquals(value, "type", "set"), "value", value),
		forbiddenWhen(wireFieldEquals(value, "type", "clear"), "value", value),
	)
}

func (value McpServerState) ValidateWire() error {
	return collectWireViolations("McpServerState",
		closedEnum("type", string(value.Type), []string{"disabled", "disconnected", "connecting", "connected", "failed", "needsAuth"}, false),
		forbiddenWhen(wireFieldEquals(value, "type", "disabled"), "toolCount", value),
		forbiddenWhen(wireFieldEquals(value, "type", "disabled"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "disconnected"), "toolCount", value),
		forbiddenWhen(wireFieldEquals(value, "type", "disconnected"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "connecting"), "toolCount", value),
		forbiddenWhen(wireFieldEquals(value, "type", "connecting"), "error", value),
		requiredWhen(wireFieldEquals(value, "type", "connected"), "toolCount", value),
		forbiddenWhen(wireFieldEquals(value, "type", "connected"), "error", value),
		requiredWhen(wireFieldEquals(value, "type", "failed"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "failed"), "toolCount", value),
		requiredWhen(wireFieldEquals(value, "type", "needsAuth"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "needsAuth"), "toolCount", value),
	)
}

func (value McpAuthorizationAttemptStatus) ValidateWire() error {
	return collectWireViolations("McpAuthorizationAttemptStatus",
		closedEnum("type", string(value.Type), []string{"pending", "succeeded", "failed", "canceled"}, false),
		forbiddenWhen(wireFieldEquals(value, "type", "pending"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "succeeded"), "error", value),
		requiredWhen(wireFieldEquals(value, "type", "failed"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "canceled"), "error", value),
	)
}

func (value Interrupt) ValidateWire() error {
	return collectWireViolations("Interrupt",
		requiredText("itemId", value.ItemID),
		requiredText("runId", value.RunID),
		closedEnum("type", string(value.Type), []string{"approval", "question", "toolResult"}, false),
		requiredWhen(wireFieldEquals(value, "type", "approval"), "itemId", value),
		requiredWhen(wireFieldEquals(value, "type", "approval"), "runId", value),
		requiredWhen(wireFieldEquals(value, "type", "approval"), "payload.tool", value),
		forbiddenWhen(wireFieldEquals(value, "type", "approval"), "payload.question", value),
		requiredWhen(wireFieldEquals(value, "type", "question"), "itemId", value),
		requiredWhen(wireFieldEquals(value, "type", "question"), "runId", value),
		requiredWhen(wireFieldEquals(value, "type", "question"), "payload.question", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "payload.tool", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "payload.risk", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "payload.reason", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "payload.rememberable", value),
		requiredWhen(wireFieldEquals(value, "type", "toolResult"), "itemId", value),
		requiredWhen(wireFieldEquals(value, "type", "toolResult"), "runId", value),
		requiredWhen(wireFieldEquals(value, "type", "toolResult"), "payload.tool", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolResult"), "payload.risk", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolResult"), "payload.reason", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolResult"), "payload.rememberable", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolResult"), "payload.question", value),
	)
}

func (value InterruptResponseValue) ValidateWire() error {
	return collectWireViolations("InterruptResponseValue",
		nonEmptyItems("answers", value.Answers),
		closedEnum("type", string(value.Type), []string{"approval", "answer", "toolResult"}, false),
		closedEnum("decision", string(value.Decision), []string{"approve", "deny"}, true),
		requiredWhen(wireFieldEquals(value, "type", "approval"), "decision", value),
		forbiddenWhen(wireFieldEquals(value, "type", "approval"), "answers", value),
		forbiddenWhen(wireFieldEquals(value, "type", "approval"), "result", value),
		forbiddenWhen(wireFieldEquals(value, "type", "approval"), "error", value),
		requiredWhen(wireFieldEquals(value, "type", "answer"), "answers", value),
		forbiddenWhen(wireFieldEquals(value, "type", "answer"), "decision", value),
		forbiddenWhen(wireFieldEquals(value, "type", "answer"), "remember", value),
		forbiddenWhen(wireFieldEquals(value, "type", "answer"), "editedArgs", value),
		forbiddenWhen(wireFieldEquals(value, "type", "answer"), "reason", value),
		forbiddenWhen(wireFieldEquals(value, "type", "answer"), "result", value),
		forbiddenWhen(wireFieldEquals(value, "type", "answer"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolResult"), "decision", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolResult"), "remember", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolResult"), "editedArgs", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolResult"), "reason", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolResult"), "answers", value),
	)
}

func (value StreamEvent) ValidateWire() error {
	return collectWireViolations("StreamEvent",
		closedEnum("type", string(value.Type), []string{"segment.started", "segment.progress", "segment.finished", "item.started", "item.delta", "item.completed", "state.snapshot", "custom"}, false),
		requiredWhen(wireFieldEquals(value, "type", "segment.started"), "run", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.started"), "progress", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.started"), "outcome", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.started"), "metrics", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.started"), "item", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.started"), "itemId", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.started"), "delta", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.started"), "state", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.started"), "name", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.started"), "payload", value),
		requiredWhen(wireFieldEquals(value, "type", "segment.progress"), "progress", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.progress"), "run", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.progress"), "outcome", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.progress"), "metrics", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.progress"), "item", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.progress"), "itemId", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.progress"), "delta", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.progress"), "state", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.progress"), "name", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.progress"), "payload", value),
		requiredWhen(wireFieldEquals(value, "type", "segment.finished"), "outcome", value),
		requiredWhen(wireFieldEquals(value, "type", "segment.finished"), "metrics", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.finished"), "run", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.finished"), "progress", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.finished"), "item", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.finished"), "itemId", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.finished"), "delta", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.finished"), "state", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.finished"), "name", value),
		forbiddenWhen(wireFieldEquals(value, "type", "segment.finished"), "payload", value),
		requiredWhen(wireFieldEquals(value, "type", "item.started"), "item", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.started"), "run", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.started"), "progress", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.started"), "outcome", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.started"), "metrics", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.started"), "itemId", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.started"), "delta", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.started"), "state", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.started"), "name", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.started"), "payload", value),
		requiredWhen(wireFieldEquals(value, "type", "item.delta"), "itemId", value),
		requiredWhen(wireFieldEquals(value, "type", "item.delta"), "delta", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.delta"), "run", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.delta"), "progress", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.delta"), "outcome", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.delta"), "metrics", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.delta"), "item", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.delta"), "state", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.delta"), "name", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.delta"), "payload", value),
		requiredWhen(wireFieldEquals(value, "type", "item.completed"), "item", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.completed"), "run", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.completed"), "progress", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.completed"), "outcome", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.completed"), "metrics", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.completed"), "itemId", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.completed"), "delta", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.completed"), "state", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.completed"), "name", value),
		forbiddenWhen(wireFieldEquals(value, "type", "item.completed"), "payload", value),
		requiredWhen(wireFieldEquals(value, "type", "state.snapshot"), "state", value),
		forbiddenWhen(wireFieldEquals(value, "type", "state.snapshot"), "run", value),
		forbiddenWhen(wireFieldEquals(value, "type", "state.snapshot"), "progress", value),
		forbiddenWhen(wireFieldEquals(value, "type", "state.snapshot"), "outcome", value),
		forbiddenWhen(wireFieldEquals(value, "type", "state.snapshot"), "metrics", value),
		forbiddenWhen(wireFieldEquals(value, "type", "state.snapshot"), "item", value),
		forbiddenWhen(wireFieldEquals(value, "type", "state.snapshot"), "itemId", value),
		forbiddenWhen(wireFieldEquals(value, "type", "state.snapshot"), "delta", value),
		forbiddenWhen(wireFieldEquals(value, "type", "state.snapshot"), "name", value),
		forbiddenWhen(wireFieldEquals(value, "type", "state.snapshot"), "payload", value),
		requiredWhen(wireFieldEquals(value, "type", "custom"), "name", value),
		forbiddenWhen(wireFieldEquals(value, "type", "custom"), "run", value),
		forbiddenWhen(wireFieldEquals(value, "type", "custom"), "progress", value),
		forbiddenWhen(wireFieldEquals(value, "type", "custom"), "outcome", value),
		forbiddenWhen(wireFieldEquals(value, "type", "custom"), "metrics", value),
		forbiddenWhen(wireFieldEquals(value, "type", "custom"), "item", value),
		forbiddenWhen(wireFieldEquals(value, "type", "custom"), "itemId", value),
		forbiddenWhen(wireFieldEquals(value, "type", "custom"), "delta", value),
		forbiddenWhen(wireFieldEquals(value, "type", "custom"), "state", value),
	)
}

func (value RuntimeEvent) ValidateWire() error {
	return collectWireViolations("RuntimeEvent",
		positiveNumber("sequence", value.Sequence),
		nonEmptyItems("paths", value.Paths),
		uniqueItems("paths", value.Paths),
		nonEmptyItems("names", value.Names),
		uniqueItems("names", value.Names),
		nonEmptyItems("serverIds", value.ServerIDs),
		uniqueItems("serverIds", value.ServerIDs),
		nonEmptyItems("scheduleIds", value.ScheduleIDs),
		uniqueItems("scheduleIds", value.ScheduleIDs),
		nonEmptyItems("sessionIds", value.SessionIDs),
		uniqueItems("sessionIds", value.SessionIDs),
		nonEmptyItems("runIds", value.RunIDs),
		uniqueItems("runIds", value.RunIDs),
		nonEmptyItems("topics", value.Topics),
		uniqueItems("topics", value.Topics),
		nonEmptyItems("watchIds", value.WatchIDs),
		uniqueItems("watchIds", value.WatchIDs),
		closedEnum("type", string(value.Type), []string{"files.changed", "skills.changed", "mcp.changed", "schedules.changed", "sessions.changed", "runs.changed", "state.changed", "goals.changed", "interrupts.changed", "resync"}, false),
		closedEnum("key", string(value.Key), []string{"plan"}, true),
		closedEnumItems("topics", value.Topics, []string{"files.changed", "skills.changed", "mcp.changed", "schedules.changed", "sessions.changed", "runs.changed", "state.changed", "goals.changed", "interrupts.changed"}),
		requiredWhen(wireFieldEquals(value, "type", "files.changed"), "sequence", value),
		requiredWhen(wireFieldEquals(value, "type", "files.changed"), "paths", value),
		forbiddenWhen(wireFieldEquals(value, "type", "files.changed"), "names", value),
		forbiddenWhen(wireFieldEquals(value, "type", "files.changed"), "serverIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "files.changed"), "scheduleIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "files.changed"), "sessionIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "files.changed"), "runIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "files.changed"), "key", value),
		forbiddenWhen(wireFieldEquals(value, "type", "files.changed"), "topics", value),
		forbiddenWhen(wireFieldEquals(value, "type", "files.changed"), "watchIds", value),
		requiredWhen(wireFieldEquals(value, "type", "skills.changed"), "sequence", value),
		forbiddenWhen(wireFieldEquals(value, "type", "skills.changed"), "paths", value),
		forbiddenWhen(wireFieldEquals(value, "type", "skills.changed"), "watchId", value),
		forbiddenWhen(wireFieldEquals(value, "type", "skills.changed"), "workspace", value),
		forbiddenWhen(wireFieldEquals(value, "type", "skills.changed"), "serverIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "skills.changed"), "scheduleIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "skills.changed"), "sessionIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "skills.changed"), "runIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "skills.changed"), "key", value),
		forbiddenWhen(wireFieldEquals(value, "type", "skills.changed"), "topics", value),
		forbiddenWhen(wireFieldEquals(value, "type", "skills.changed"), "watchIds", value),
		requiredWhen(wireFieldEquals(value, "type", "mcp.changed"), "sequence", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp.changed"), "paths", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp.changed"), "watchId", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp.changed"), "workspace", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp.changed"), "names", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp.changed"), "scheduleIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp.changed"), "sessionIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp.changed"), "runIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp.changed"), "key", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp.changed"), "topics", value),
		forbiddenWhen(wireFieldEquals(value, "type", "mcp.changed"), "watchIds", value),
		requiredWhen(wireFieldEquals(value, "type", "schedules.changed"), "sequence", value),
		forbiddenWhen(wireFieldEquals(value, "type", "schedules.changed"), "paths", value),
		forbiddenWhen(wireFieldEquals(value, "type", "schedules.changed"), "watchId", value),
		forbiddenWhen(wireFieldEquals(value, "type", "schedules.changed"), "workspace", value),
		forbiddenWhen(wireFieldEquals(value, "type", "schedules.changed"), "names", value),
		forbiddenWhen(wireFieldEquals(value, "type", "schedules.changed"), "serverIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "schedules.changed"), "sessionIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "schedules.changed"), "runIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "schedules.changed"), "key", value),
		forbiddenWhen(wireFieldEquals(value, "type", "schedules.changed"), "topics", value),
		forbiddenWhen(wireFieldEquals(value, "type", "schedules.changed"), "watchIds", value),
		requiredWhen(wireFieldEquals(value, "type", "sessions.changed"), "sequence", value),
		forbiddenWhen(wireFieldEquals(value, "type", "sessions.changed"), "paths", value),
		forbiddenWhen(wireFieldEquals(value, "type", "sessions.changed"), "watchId", value),
		forbiddenWhen(wireFieldEquals(value, "type", "sessions.changed"), "workspace", value),
		forbiddenWhen(wireFieldEquals(value, "type", "sessions.changed"), "names", value),
		forbiddenWhen(wireFieldEquals(value, "type", "sessions.changed"), "serverIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "sessions.changed"), "scheduleIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "sessions.changed"), "runIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "sessions.changed"), "key", value),
		forbiddenWhen(wireFieldEquals(value, "type", "sessions.changed"), "topics", value),
		forbiddenWhen(wireFieldEquals(value, "type", "sessions.changed"), "watchIds", value),
		requiredWhen(wireFieldEquals(value, "type", "runs.changed"), "sequence", value),
		forbiddenWhen(wireFieldEquals(value, "type", "runs.changed"), "paths", value),
		forbiddenWhen(wireFieldEquals(value, "type", "runs.changed"), "watchId", value),
		forbiddenWhen(wireFieldEquals(value, "type", "runs.changed"), "workspace", value),
		forbiddenWhen(wireFieldEquals(value, "type", "runs.changed"), "names", value),
		forbiddenWhen(wireFieldEquals(value, "type", "runs.changed"), "serverIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "runs.changed"), "scheduleIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "runs.changed"), "key", value),
		forbiddenWhen(wireFieldEquals(value, "type", "runs.changed"), "topics", value),
		forbiddenWhen(wireFieldEquals(value, "type", "runs.changed"), "watchIds", value),
		requiredWhen(wireFieldEquals(value, "type", "state.changed"), "sequence", value),
		requiredWhen(wireFieldEquals(value, "type", "state.changed"), "key", value),
		forbiddenWhen(wireFieldEquals(value, "type", "state.changed"), "paths", value),
		forbiddenWhen(wireFieldEquals(value, "type", "state.changed"), "watchId", value),
		forbiddenWhen(wireFieldEquals(value, "type", "state.changed"), "workspace", value),
		forbiddenWhen(wireFieldEquals(value, "type", "state.changed"), "names", value),
		forbiddenWhen(wireFieldEquals(value, "type", "state.changed"), "serverIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "state.changed"), "scheduleIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "state.changed"), "topics", value),
		forbiddenWhen(wireFieldEquals(value, "type", "state.changed"), "watchIds", value),
		requiredWhen(wireFieldEquals(value, "type", "goals.changed"), "sequence", value),
		forbiddenWhen(wireFieldEquals(value, "type", "goals.changed"), "paths", value),
		forbiddenWhen(wireFieldEquals(value, "type", "goals.changed"), "watchId", value),
		forbiddenWhen(wireFieldEquals(value, "type", "goals.changed"), "workspace", value),
		forbiddenWhen(wireFieldEquals(value, "type", "goals.changed"), "names", value),
		forbiddenWhen(wireFieldEquals(value, "type", "goals.changed"), "serverIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "goals.changed"), "scheduleIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "goals.changed"), "runIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "goals.changed"), "key", value),
		forbiddenWhen(wireFieldEquals(value, "type", "goals.changed"), "topics", value),
		forbiddenWhen(wireFieldEquals(value, "type", "goals.changed"), "watchIds", value),
		requiredWhen(wireFieldEquals(value, "type", "interrupts.changed"), "sequence", value),
		forbiddenWhen(wireFieldEquals(value, "type", "interrupts.changed"), "paths", value),
		forbiddenWhen(wireFieldEquals(value, "type", "interrupts.changed"), "watchId", value),
		forbiddenWhen(wireFieldEquals(value, "type", "interrupts.changed"), "workspace", value),
		forbiddenWhen(wireFieldEquals(value, "type", "interrupts.changed"), "names", value),
		forbiddenWhen(wireFieldEquals(value, "type", "interrupts.changed"), "serverIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "interrupts.changed"), "scheduleIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "interrupts.changed"), "key", value),
		forbiddenWhen(wireFieldEquals(value, "type", "interrupts.changed"), "topics", value),
		forbiddenWhen(wireFieldEquals(value, "type", "interrupts.changed"), "watchIds", value),
		requiredWhen(wireFieldEquals(value, "type", "resync"), "sequence", value),
		requiredWhen(wireFieldEquals(value, "type", "resync"), "topics", value),
		forbiddenWhen(wireFieldEquals(value, "type", "resync"), "paths", value),
		forbiddenWhen(wireFieldEquals(value, "type", "resync"), "watchId", value),
		forbiddenWhen(wireFieldEquals(value, "type", "resync"), "workspace", value),
		forbiddenWhen(wireFieldEquals(value, "type", "resync"), "names", value),
		forbiddenWhen(wireFieldEquals(value, "type", "resync"), "serverIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "resync"), "scheduleIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "resync"), "sessionIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "resync"), "runIds", value),
		forbiddenWhen(wireFieldEquals(value, "type", "resync"), "key", value),
	)
}

func (value ArtifactOutcome) ValidateWire() error {
	return collectWireViolations("ArtifactOutcome",
		closedEnum("type", string(value.Type), []string{"completed", "error", "maxSteps", "maxBudget", "canceled"}, false),
		forbiddenWhen(wireFieldEquals(value, "type", "completed"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "completed"), "detail", value),
		requiredWhen(wireFieldEquals(value, "type", "error"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "error"), "detail", value),
		forbiddenWhen(wireFieldEquals(value, "type", "maxSteps"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "maxBudget"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "canceled"), "error", value),
		requiredWhen(wireFieldEquals(value, "type", "error"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "error"), "detail", value),
	)
}

func (value ArtifactItem) ValidateWire() error {
	return collectWireViolations("ArtifactItem",
		nonNegativeNumber("droppedMessages", value.DroppedMessages),
		optionalNonNegativeNumber("durationMs", value.DurationMs),
		closedEnum("status", string(value.Status), []string{"running", "completed", "incomplete"}, false),
		closedEnum("type", string(value.Type), []string{"userMessage", "agentMessage", "reasoning", "question", "toolCall", "compaction"}, false),
		closedEnum("safetyClass", string(value.SafetyClass), []string{"safe", "write", "exec", "network"}, true),
		requiredWhen(wireFieldEquals(value, "type", "userMessage"), "id", value),
		requiredWhen(wireFieldEquals(value, "type", "userMessage"), "runId", value),
		requiredWhen(wireFieldEquals(value, "type", "userMessage"), "status", value),
		requiredWhen(wireFieldEquals(value, "type", "userMessage"), "createdAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "text", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "redacted", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "question", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "startedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "finishedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "durationMs", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "tool", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "safetyClass", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "summary", value),
		forbiddenWhen(wireFieldEquals(value, "type", "userMessage"), "droppedMessages", value),
		requiredWhen(wireFieldEquals(value, "type", "agentMessage"), "id", value),
		requiredWhen(wireFieldEquals(value, "type", "agentMessage"), "runId", value),
		requiredWhen(wireFieldEquals(value, "type", "agentMessage"), "status", value),
		requiredWhen(wireFieldEquals(value, "type", "agentMessage"), "createdAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "text", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "redacted", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "question", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "startedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "finishedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "durationMs", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "tool", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "safetyClass", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "summary", value),
		forbiddenWhen(wireFieldEquals(value, "type", "agentMessage"), "droppedMessages", value),
		requiredWhen(wireFieldEquals(value, "type", "reasoning"), "id", value),
		requiredWhen(wireFieldEquals(value, "type", "reasoning"), "runId", value),
		requiredWhen(wireFieldEquals(value, "type", "reasoning"), "status", value),
		requiredWhen(wireFieldEquals(value, "type", "reasoning"), "createdAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "content", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "question", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "startedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "finishedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "durationMs", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "tool", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "safetyClass", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "summary", value),
		forbiddenWhen(wireFieldEquals(value, "type", "reasoning"), "droppedMessages", value),
		requiredWhen(wireFieldEquals(value, "type", "question"), "id", value),
		requiredWhen(wireFieldEquals(value, "type", "question"), "runId", value),
		requiredWhen(wireFieldEquals(value, "type", "question"), "status", value),
		requiredWhen(wireFieldEquals(value, "type", "question"), "createdAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "content", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "text", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "redacted", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "startedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "finishedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "durationMs", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "tool", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "safetyClass", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "summary", value),
		forbiddenWhen(wireFieldEquals(value, "type", "question"), "droppedMessages", value),
		requiredWhen(wireFieldEquals(value, "type", "toolCall"), "id", value),
		requiredWhen(wireFieldEquals(value, "type", "toolCall"), "runId", value),
		requiredWhen(wireFieldEquals(value, "type", "toolCall"), "status", value),
		requiredWhen(wireFieldEquals(value, "type", "toolCall"), "createdAt", value),
		requiredWhen(wireFieldEquals(value, "type", "toolCall"), "startedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolCall"), "content", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolCall"), "text", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolCall"), "redacted", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolCall"), "question", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolCall"), "summary", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolCall"), "droppedMessages", value),
		requiredWhen(wireFieldEquals(value, "type", "compaction"), "id", value),
		requiredWhen(wireFieldEquals(value, "type", "compaction"), "runId", value),
		requiredWhen(wireFieldEquals(value, "type", "compaction"), "status", value),
		requiredWhen(wireFieldEquals(value, "type", "compaction"), "createdAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "compaction"), "content", value),
		forbiddenWhen(wireFieldEquals(value, "type", "compaction"), "text", value),
		forbiddenWhen(wireFieldEquals(value, "type", "compaction"), "redacted", value),
		forbiddenWhen(wireFieldEquals(value, "type", "compaction"), "question", value),
		forbiddenWhen(wireFieldEquals(value, "type", "compaction"), "startedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "compaction"), "finishedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "compaction"), "durationMs", value),
		forbiddenWhen(wireFieldEquals(value, "type", "compaction"), "tool", value),
		forbiddenWhen(wireFieldEquals(value, "type", "compaction"), "safetyClass", value),
		forbiddenWhen(wireFieldEquals(value, "type", "compaction"), "error", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolCall") && wireFieldEquals(value, "status", "running"), "finishedAt", value),
		forbiddenWhen(wireFieldEquals(value, "type", "toolCall") && wireFieldEquals(value, "status", "running"), "durationMs", value),
		requiredWhen(wireFieldEquals(value, "type", "toolCall") && wireFieldEquals(value, "status", "completed"), "finishedAt", value),
		requiredWhen(wireFieldEquals(value, "type", "toolCall") && wireFieldEquals(value, "status", "completed"), "durationMs", value),
		requiredWhen(wireFieldEquals(value, "type", "toolCall") && wireFieldEquals(value, "status", "incomplete"), "finishedAt", value),
		requiredWhen(wireFieldEquals(value, "type", "toolCall") && wireFieldEquals(value, "status", "incomplete"), "durationMs", value),
	)
}

func (value ArtifactContentBlock) ValidateWire() error {
	return collectWireViolations("ArtifactContentBlock",
		closedEnum("type", string(value.Type), []string{"text", "image"}, false),
		requiredWhen(wireFieldEquals(value, "type", "text"), "text", value),
		forbiddenWhen(wireFieldEquals(value, "type", "text"), "mime", value),
		forbiddenWhen(wireFieldEquals(value, "type", "text"), "data", value),
		requiredWhen(wireFieldEquals(value, "type", "image"), "mime", value),
		requiredWhen(wireFieldEquals(value, "type", "image"), "data", value),
		forbiddenWhen(wireFieldEquals(value, "type", "image"), "text", value),
	)
}

func (value DiffRow) ValidateWire() error {
	return collectWireViolations("DiffRow",
		closedEnum("type", string(value.Type), []string{"hunk", "context", "added", "deleted"}, false),
		requiredWhen(wireFieldEquals(value, "type", "hunk"), "text", value),
		forbiddenWhen(wireFieldEquals(value, "type", "hunk"), "code", value),
		forbiddenWhen(wireFieldEquals(value, "type", "hunk"), "leftLine", value),
		forbiddenWhen(wireFieldEquals(value, "type", "hunk"), "rightLine", value),
		requiredWhen(wireFieldEquals(value, "type", "context"), "code", value),
		requiredWhen(wireFieldEquals(value, "type", "context"), "leftLine", value),
		requiredWhen(wireFieldEquals(value, "type", "context"), "rightLine", value),
		forbiddenWhen(wireFieldEquals(value, "type", "context"), "text", value),
		requiredWhen(wireFieldEquals(value, "type", "added"), "code", value),
		requiredWhen(wireFieldEquals(value, "type", "added"), "rightLine", value),
		forbiddenWhen(wireFieldEquals(value, "type", "added"), "text", value),
		forbiddenWhen(wireFieldEquals(value, "type", "added"), "leftLine", value),
		requiredWhen(wireFieldEquals(value, "type", "deleted"), "code", value),
		requiredWhen(wireFieldEquals(value, "type", "deleted"), "leftLine", value),
		forbiddenWhen(wireFieldEquals(value, "type", "deleted"), "text", value),
		forbiddenWhen(wireFieldEquals(value, "type", "deleted"), "rightLine", value),
	)
}

func (value McpAuthorizationAttempt) ValidateWire() error {
	return collectWireViolations("McpAuthorizationAttempt",
		requiredText("id", value.ID),
		requiredText("server", value.Server),
		forbiddenWhen(wireFieldEquals(value, "status.type", "pending"), "finishedAt", value),
		requiredWhen(wireFieldEquals(value, "status.type", "succeeded"), "finishedAt", value),
		requiredWhen(wireFieldEquals(value, "status.type", "failed"), "finishedAt", value),
		requiredWhen(wireFieldEquals(value, "status.type", "canceled"), "finishedAt", value),
	)
}

func (value RunSummary) ValidateWire() error {
	return collectWireViolations("RunSummary",
		closedEnum("status", string(value.Status), []string{"running", "waiting", "finished"}, true),
		requiredWhen(wireFieldEquals(value, "status", "finished"), "outcome", value),
		requiredWhen(wireFieldEquals(value, "status", "finished"), "finishedAt", value),
		forbiddenWhen(wireFieldEquals(value, "status", "running"), "outcome", value),
		forbiddenWhen(wireFieldEquals(value, "status", "running"), "finishedAt", value),
		forbiddenWhen(wireFieldEquals(value, "status", "waiting"), "outcome", value),
		forbiddenWhen(wireFieldEquals(value, "status", "waiting"), "finishedAt", value),
		requiredWhen(wireFieldPresent(value, "spawnedByItemId"), "parentRunId", value),
		requiredWhen(wireFieldPresent(value, "spawnedByItemId"), "rootRunId", value),
		requiredWhen(wireFieldPresent(value, "parentRunId"), "spawnedByItemId", value),
		requiredWhen(wireFieldPresent(value, "parentRunId"), "rootRunId", value),
		requiredWhen(wireFieldPresent(value, "rootRunId"), "spawnedByItemId", value),
		requiredWhen(wireFieldPresent(value, "rootRunId"), "parentRunId", value),
	)
}

func (value RunRef) ValidateWire() error {
	return collectWireViolations("RunRef",
		closedEnum("status", string(value.Status), []string{"running", "waiting", "finished"}, true),
		requiredWhen(wireFieldEquals(value, "status", "finished"), "outcome", value),
		requiredWhen(wireFieldEquals(value, "status", "finished"), "finishedAt", value),
		forbiddenWhen(wireFieldEquals(value, "status", "running"), "outcome", value),
		forbiddenWhen(wireFieldEquals(value, "status", "running"), "finishedAt", value),
		forbiddenWhen(wireFieldEquals(value, "status", "waiting"), "outcome", value),
		forbiddenWhen(wireFieldEquals(value, "status", "waiting"), "finishedAt", value),
		requiredWhen(wireFieldPresent(value, "spawnedByItemId"), "parentRunId", value),
		requiredWhen(wireFieldPresent(value, "spawnedByItemId"), "rootRunId", value),
		requiredWhen(wireFieldPresent(value, "parentRunId"), "spawnedByItemId", value),
		requiredWhen(wireFieldPresent(value, "parentRunId"), "rootRunId", value),
		requiredWhen(wireFieldPresent(value, "rootRunId"), "spawnedByItemId", value),
		requiredWhen(wireFieldPresent(value, "rootRunId"), "parentRunId", value),
		requiredWhen(wireFieldEquals(value, "status", "running"), "activeSegmentId", value),
		forbiddenWhen(wireFieldEquals(value, "status", "waiting"), "activeSegmentId", value),
		forbiddenWhen(wireFieldEquals(value, "status", "finished"), "activeSegmentId", value),
	)
}

func (value PendingInterruptSet) ValidateWire() error {
	return collectWireViolations("PendingInterruptSet",
		requiredText("rootRunId", value.RootRunID),
		requiredText("sessionId", value.SessionID),
		requiredItems("interrupts", value.Interrupts),
		requiredWhen(true, "rootRunId", value),
		requiredWhen(true, "sessionId", value),
		requiredWhen(true, "interrupts", value),
		requiredWhen(true, "createdAt", value),
	)
}

func (value ArtifactRun) ValidateWire() error {
	return collectWireViolations("ArtifactRun",
		nonNegativeNumber("messageMark", value.MessageMark),
		forbiddenWhen(wireFieldPresent(value, "spawnedByItemId"), "protocolProfile", value),
		requiredWhen(wireFieldPresent(value, "spawnedByItemId"), "parentRunId", value),
		requiredWhen(wireFieldPresent(value, "spawnedByItemId"), "rootRunId", value),
		requiredWhen(wireFieldPresent(value, "parentRunId"), "spawnedByItemId", value),
		requiredWhen(wireFieldPresent(value, "parentRunId"), "rootRunId", value),
		requiredWhen(wireFieldPresent(value, "rootRunId"), "spawnedByItemId", value),
		requiredWhen(wireFieldPresent(value, "rootRunId"), "parentRunId", value),
	)
}

func (value SessionArtifact) ValidateWire() error {
	return collectWireViolations("SessionArtifact",
		minimumNumber("version", value.Version, 11),
		maximumNumber("version", value.Version, 11),
	)
}

func (value ArtifactRunMetrics) ValidateWire() error {
	return collectWireViolations("ArtifactRunMetrics",
		nonNegativeNumber("steps", value.Steps),
		nonNegativeNumber("activeDurationMs", value.ActiveDurationMs),
	)
}

func (value ArtifactUsage) ValidateWire() error {
	return collectWireViolations("ArtifactUsage",
		nonNegativeNumber("inputTokens", value.InputTokens),
		nonNegativeNumber("outputTokens", value.OutputTokens),
		nonNegativeNumber("cacheReadTokens", value.CacheReadTokens),
		nonNegativeNumber("cacheWriteTokens", value.CacheWriteTokens),
		nonNegativeNumber("reasoningTokens", value.ReasoningTokens),
		optionalNonNegativeNumber("costUsd", value.CostUSD),
	)
}

func (value ArtifactModelUsage) ValidateWire() error {
	return collectWireViolations("ArtifactModelUsage",
		nonNegativeNumber("inputTokens", value.InputTokens),
		nonNegativeNumber("outputTokens", value.OutputTokens),
		nonNegativeNumber("cacheReadTokens", value.CacheReadTokens),
		nonNegativeNumber("cacheWriteTokens", value.CacheWriteTokens),
		nonNegativeNumber("reasoningTokens", value.ReasoningTokens),
		optionalNonNegativeNumber("costUsd", value.CostUSD),
	)
}

func (value ArtifactProblem) ValidateWire() error {
	return collectWireViolations("ArtifactProblem",
		optionalPositiveScalarNumber("retryAfterSeconds", value.RetryAfterSeconds),
		closedEnum("type", string(value.Type), []string{"internalError", "runLost", "agentStuck", "rateLimited", "invalidApiKey", "timeout", "providerUnavailable", "providerRejected", "deniedByUser", "toolFailed", "childRunCanceled"}, false),
	)
}

func (value RunProtocolProfile) ValidateWire() error {
	return collectWireViolations("RunProtocolProfile",
		uniqueItems("requiredFeatures", value.RequiredFeatures),
		uniqueItems("interruptTypes", value.InterruptTypes),
		closedEnumItems("requiredFeatures", value.RequiredFeatures, []string{"subagents"}),
		closedEnumItems("interruptTypes", value.InterruptTypes, []string{"approval", "question", "toolResult"}),
	)
}

func (value GenerationParams) ValidateWire() error {
	return collectWireViolations("GenerationParams",
		optionalNonNegativeNumber("temperature", value.Temperature),
		optionalMaximumNumber("temperature", value.Temperature, 2),
		optionalPositiveNumber("maxTokens", value.MaxTokens),
		optionalNonNegativeNumber("topP", value.TopP),
		optionalMaximumNumber("topP", value.TopP, 1),
		nonEmptyItems("stop", value.Stop),
		uniqueItems("stop", value.Stop),
	)
}

func (value RunLimits) ValidateWire() error {
	return collectWireViolations("RunLimits",
		nonNegativeNumber("maxTotalTokens", value.MaxTotalTokens),
		nonNegativeNumber("maxSteps", value.MaxSteps),
		nonNegativeNumber("maxBudgetUsd", value.MaxBudgetUSD),
	)
}

func (value ArtifactRunLimits) ValidateWire() error {
	return collectWireViolations("ArtifactRunLimits",
		nonNegativeNumber("maxTotalTokens", value.MaxTotalTokens),
		nonNegativeNumber("maxSteps", value.MaxSteps),
		nonNegativeNumber("maxBudgetUsd", value.MaxBudgetUSD),
	)
}

func (value Question) ValidateWire() error {
	return collectWireViolations("Question",
		requiredItems("fields", value.Fields),
	)
}

func (value ArtifactQuestion) ValidateWire() error {
	return collectWireViolations("ArtifactQuestion",
		requiredItems("fields", value.Fields),
	)
}

func (value QuestionOption) ValidateWire() error {
	return collectWireViolations("QuestionOption",
		requiredText("label", value.Label),
	)
}

func (value ArtifactQuestionOption) ValidateWire() error {
	return collectWireViolations("ArtifactQuestionOption",
		requiredText("label", value.Label),
	)
}

func (value StartRunResponse) ValidateWire() error {
	return collectWireViolations("StartRunResponse",
		requiredText("runId", value.RunID),
		requiredText("segmentId", value.SegmentID),
		requiredText("userItemId", value.UserItemID),
	)
}

func (value ResumeRunResponse) ValidateWire() error {
	return collectWireViolations("ResumeRunResponse",
		requiredText("runId", value.RunID),
		requiredText("segmentId", value.SegmentID),
		optionalText("userItemId", value.UserItemID),
	)
}

func (value WorkspaceRef) ValidateWire() error {
	return collectWireViolations("WorkspaceRef",
		requiredText("path", value.Path),
	)
}

func (value GoalBudget) ValidateWire() error {
	return collectWireViolations("GoalBudget",
		nonNegativeNumber("maxTurns", value.MaxTurns),
		nonNegativeNumber("maxCostUsd", value.MaxCostUsd),
		nonNegativeNumber("maxSteps", value.MaxSteps),
	)
}

func (value ClientInfo) ValidateWire() error {
	return collectWireViolations("ClientInfo",
		requiredText("name", value.Name),
		requiredText("version", value.Version),
	)
}

func (value ClientCapabilities) ValidateWire() error {
	return collectWireViolations("ClientCapabilities",
		uniqueItems("interruptTypes", value.InterruptTypes),
		uniqueItems("excludedEphemeralEvents", value.ExcludedEphemeralEvents),
		closedEnumItems("interruptTypes", value.InterruptTypes, []string{"approval", "question", "toolResult"}),
		closedEnumItems("excludedEphemeralEvents", value.ExcludedEphemeralEvents, []string{"segment.progress", "item.delta"}),
	)
}

func (value MCPAuthorizationAttemptLimits) ValidateWire() error {
	return collectWireViolations("MCPAuthorizationAttemptLimits",
		positiveNumber("retentionSeconds", value.RetentionSeconds),
	)
}

func (value ActiveRunRef) ValidateWire() error {
	return collectWireViolations("ActiveRunRef",
		requiredText("runId", value.RunID),
		closedEnum("status", string(value.Status), []string{"running", "waiting", "finished"}, false),
	)
}

func (value FieldError) ValidateWire() error {
	return collectWireViolations("FieldError",
		requiredText("field", value.Field),
		requiredText("detail", value.Detail),
	)
}

func (value RunReplayLimits) ValidateWire() error {
	return collectWireViolations("RunReplayLimits",
		positiveNumber("maxEvents", value.MaxEvents),
		positiveNumber("maxBytes", value.MaxBytes),
		closedEnum("scope", string(value.Scope), []string{"processRootSegment"}, false),
	)
}

func (value IdempotencyLimits) ValidateWire() error {
	return collectWireViolations("IdempotencyLimits",
		positiveNumber("retentionSeconds", value.RetentionSeconds),
	)
}

func (value SubscriptionLimits) ValidateWire() error {
	return collectWireViolations("SubscriptionLimits",
		positiveNumber("maxTopics", value.MaxTopics),
		positiveNumber("maxWatches", value.MaxWatches),
	)
}
