// Code generated by cmd/contractgen. DO NOT EDIT.
//
// The wire types of the Lyra Runtime Protocol, projected from the Contract
// Registry. Prose lives with the Go types and in docs/protocol/API.md; this file
// carries the shapes so the frontend and the runtime cannot disagree about them.
//
// Cross-field rules — a finished run carries an outcome, an interrupt outcome
// carries no result — are NOT here: TypeScript has no way to state them. They are
// in the generated validator and in schema.json.

// The methods the runtime sends downstream. A client only ever subscribes.
export const NOTIFICATIONS_RUN_EVENT = "notifications.run.event";
export const NOTIFICATIONS_WORKSPACE_EVENT = "notifications.workspace.event";

export interface Page<T> {
  data: T[];
  nextCursor?: string;
}

export interface ActiveRunRef {
  runId: string;
  status: RunStatus;
}

export interface AgentDoc {
  path: string;
  scope: AgentDocScope;
  title?: string;
}

export type AgentDocScope = "cwd" | "projectRoot" | "home";

export interface AgentMemoryAddRequest {
  content: string;
  cwd?: string;
  scope?: AgentMemoryScope;
}

export interface AgentMemoryItem {
  content: string;
  createdAt: string;
  day?: string;
  id: string;
  origin: AgentMemoryOrigin;
  pinned: boolean;
  scope: AgentMemoryScope;
  sessionId?: string;
  status: AgentMemoryStatus;
  updatedAt: string;
}

export interface AgentMemoryItemRequest {
  id: string;
}

export interface AgentMemoryList {
  items: AgentMemoryItem[];
}

export interface AgentMemoryListRequest {
  cwd?: string;
  scope?: AgentMemoryScope;
}

export type AgentMemoryOrigin = "auto" | "user";

export type AgentMemoryReviewDecision = "approve" | "reject";

export interface AgentMemoryReviewRequest {
  decision: AgentMemoryReviewDecision;
  id: string;
}

export type AgentMemoryScope = "project" | "user";

export type AgentMemoryStatus = "active" | "pending";

export interface AgentMemoryUpdateRequest {
  content?: string;
  id: string;
  pinned?: boolean;
}

export type ApprovalDecision = "approve" | "deny";

export type ApprovalMode = "safe" | "balanced" | "yolo" | "plan";

export interface ApprovalModeResult {
  mode: ApprovalMode;
}

export type ApprovalRisk = "low" | "medium" | "high";

export interface ApprovalRule {
  decision: ApprovalRuleDecision;
  dir?: string;
  id: string;
  scope: ApprovalRuleScope;
  subject?: string;
  tool: string;
}

export type ApprovalRuleDecision = "allow" | "deny";

export type ApprovalRuleScope = "session" | "project" | "global";

export type ArtifactContentBlock =
  | { type: "text"; text: string }
  | { type: "image"; data: string; mime: string };

export type ArtifactItem =
  | { type: "userMessage"; content?: ArtifactContentBlock[]; createdAt: string; id: string; runId: string; status: ItemStatus }
  | { type: "agentMessage"; content?: ArtifactContentBlock[]; createdAt: string; id: string; runId: string; status: ItemStatus }
  | { type: "reasoning"; createdAt: string; id: string; redacted?: boolean; runId: string; status: ItemStatus; text?: string }
  | { type: "plan"; createdAt: string; id: string; runId: string; status: ItemStatus; steps?: ArtifactPlanStep[] }
  | { type: "question"; createdAt: string; id: string; question?: ArtifactQuestion; runId: string; status: ItemStatus }
  | { type: "toolCall"; createdAt: string; error?: ArtifactProblem; id: string; runId: string; safetyClass?: SafetyClass; status: ItemStatus; tool?: ArtifactToolInvocation }
  | { type: "compaction"; createdAt: string; droppedMessages?: number; id: string; runId: string; status: ItemStatus; summary?: string };

export interface ArtifactModelUsage {
  cacheReadTokens?: number;
  cacheWriteTokens?: number;
  costUsd?: number;
  inputTokens?: number;
  outputTokens?: number;
  reasoningTokens?: number;
}

export type ArtifactOutcome =
  | { type: "completed" }
  | { type: "error"; error: ArtifactProblem }
  | { type: "maxSteps"; detail?: string }
  | { type: "maxBudget"; detail?: string }
  | { type: "canceled"; detail?: string };

export type ArtifactOutcomeType = "completed" | "error" | "maxSteps" | "maxBudget" | "canceled";

export interface ArtifactPlanStep {
  id: string;
  status: PlanStepStatus;
  title: string;
}

export interface ArtifactProblem {
  detail?: string;
  docUrl?: string;
  retryAfterSeconds?: number;
  type: ArtifactProblemType;
}

export type ArtifactProblemType = "internalError" | "runLost" | "agentStuck" | "rateLimited" | "invalidApiKey" | "timeout" | "providerUnavailable" | "providerRejected" | "deniedByUser" | "toolFailed";

export interface ArtifactQuestion {
  fields: ArtifactQuestionField[];
  prompt: string;
}

export interface ArtifactQuestionField {
  header?: string;
  label: string;
  multiple?: boolean;
  name: string;
  options?: ArtifactQuestionOption[];
  required?: boolean;
  type: QuestionFieldType;
}

export interface ArtifactQuestionOption {
  description?: string;
  label: string;
  preview?: string;
}

export interface ArtifactRun {
  createdAt: string;
  finishedAt: string;
  id: string;
  limits?: ArtifactRunLimits;
  messageMark: number;
  metrics: ArtifactRunMetrics;
  model?: string;
  outcome: ArtifactOutcome;
  protocolProfile: RunProtocolProfile;
  provider?: string;
  sessionId: string;
  spawnedByItemId?: string;
  updatedAt: string;
}

export interface ArtifactRunLimits {
  maxBudgetUsd?: number;
  maxSteps?: number;
}

export interface ArtifactRunMetrics {
  activeDurationMs: number;
  steps: number;
  usage?: ArtifactUsage;
}

export interface ArtifactSession {
  createdAt: string;
  cwd: string;
  favorite?: boolean;
  id: string;
  model: string;
  title: string;
  updatedAt: string;
}

export interface ArtifactToolInvocation {
  arguments: Record<string, unknown>;
  name: string;
  result?: unknown;
}

export interface ArtifactToolResult {
  body: string;
  createdAt: string;
  id: string;
  itemId: string;
  preview: string;
  toolName: string;
}

export interface ArtifactUsage {
  byModel?: Record<string, ArtifactModelUsage>;
  cacheReadTokens?: number;
  cacheWriteTokens?: number;
  costUsd?: number;
  inputTokens?: number;
  outputTokens?: number;
  reasoningTokens?: number;
}

export interface CancelRunRequest {
  reason?: string;
  runId: string;
}

export type CapabilityRequirement =
  | { type: "feature"; name: string }
  | { type: "interruptType"; name: string }
  | { type: "runtimeTopic"; name: string }
  | { type: "stateSnapshot"; name: string };

export type CapabilityRequirementType = "feature" | "interruptType" | "runtimeTopic" | "stateSnapshot";

export interface ClientCapabilities {
  excludedEphemeralEvents?: StreamEventType[];
  features?: Record<string, FeaturePreference>;
  interruptTypes?: InterruptType[];
}

export interface ClientInfo {
  name: string;
  version: string;
}

export interface CodebaseHit {
  endLine: number;
  path: string;
  score: number;
  snippet: string;
  startLine: number;
}

export interface CodebaseReindexRequest {
  cwd?: string;
}

export interface CodebaseReindexResponse {
  operationId: string;
}

export interface CodebaseSearchRequest {
  cwd?: string;
  limit?: number;
  query: string;
}

export interface CodebaseSearchResult {
  hits: CodebaseHit[];
}

export type CodebaseState = "none" | "indexing" | "ready" | "error";

export interface CodebaseStatus {
  chunkCount: number;
  fileCount: number;
  indexedAt?: string;
  modelId?: string;
  operationId?: string;
  state: CodebaseState;
  truncated?: boolean;
}

export interface CodebaseStatusRequest {
  cwd?: string;
}

export interface ConfigureMCPServerRequest {
  args?: string[];
  authorization?: string;
  autoApproveTools?: string[];
  command?: string;
  description?: string;
  dir?: string;
  disabledTools?: string[];
  enabled: boolean;
  env?: Record<string, string>;
  headers?: Record<string, string>;
  name: string;
  timeoutSeconds?: number;
  type: McpTransport;
  url?: string;
}

export interface ConfigureProviderRequest {
  apiKey?: string;
  baseUrl?: string;
  provider: string;
}

export type ContentBlock =
  | { type: "text"; text: string }
  | { type: "image"; data: string; mime: string };

export type ContentBlockType = "text" | "image";

export interface CreateScheduleRequest {
  cron: string;
  cwd?: string;
  model?: string;
  prompt: string;
  provider?: string;
  title?: string;
}

export interface CreateSessionRequest {
  cwd?: string;
  title?: string;
}

export interface DeleteScheduleRequest {
  id: string;
}

export interface DeleteSessionRequest {
  sessionId: string;
}

export interface Diff {
  files?: FileDiff[];
  patch?: string;
  truncated?: boolean;
}

export type DiffFormat = "rows" | "raw";

export type DiffMode = "worktree" | "base";

export type DiffRow =
  | { type: "hunk"; text: string }
  | { type: "context"; code: string; leftLine: number; rightLine: number }
  | { type: "added"; code: string; rightLine: number }
  | { type: "deleted"; code: string; leftLine: number };

export type DiffRowType = "hunk" | "context" | "added" | "deleted";

export interface DiscoverResponse {
  capabilities: ServerCapabilities;
  protocol: ProtocolRange;
  serverInfo: ServerInfo;
}

export interface DroppedRun {
  run: RunRef;
  userInput?: ContentBlock[];
}

export interface EmbeddingRole {
  model?: string;
  provider?: string;
}

export type ExportFormat = "md" | "json";

export interface ExportSessionRequest {
  format?: ExportFormat;
  sessionId: string;
}

export interface ExportSessionResponse {
  artifact?: SessionArtifact;
  format: ExportFormat;
  markdown?: string;
}

export interface FeatureCapability {
  clientOptIn: boolean;
  enabled: boolean;
  requiredByRunProtocol: boolean;
  stability: Stability;
}

export interface FeaturePreference {
  enabled: boolean;
}

export type FeedbackRating = "positive" | "negative";

export interface FeedbackRequest {
  itemId?: string;
  rating?: FeedbackRating;
  runId?: string;
  sessionId?: string;
  text?: string;
}

export interface FieldError {
  detail: string;
  field: string;
}

export interface FileContent {
  content: string;
  encoding: string;
  endLine?: number;
  path: string;
  startLine?: number;
  totalLines: number;
  truncated?: boolean;
}

export interface FileDiff {
  added?: number;
  binary?: boolean;
  path: string;
  previousPath?: string;
  removed?: number;
  rows: DiffRow[];
  status: FileStatus;
}

export interface FileEdit {
  diff?: DiffRow[];
  path: string;
  status: FileStatus;
}

export interface FileEntry {
  modifiedAt: string;
  name: string;
  path: string;
  sizeBytes?: number;
  type: FileEntryType;
}

export type FileEntryType = "file" | "dir" | "symlink";

export interface FileHead {
  lines: FileLine[];
  path: string;
}

export interface FileLine {
  lineNumber: number;
  text: string;
}

export type FileStatus = "added" | "modified" | "deleted" | "renamed" | "untracked";

export interface ForgetApprovalRuleRequest {
  id: string;
}

export interface ForkSessionRequest {
  fromRunId?: string;
  sessionId: string;
  title?: string;
}

export interface GenerationParams {
  maxTokens?: number;
  stop?: string[];
  temperature?: number;
  topP?: number;
}

export interface GetDiffRequest {
  cwd?: string;
  format?: DiffFormat;
  limit?: number;
  mode?: DiffMode;
  path?: string;
}

export interface GetFileHeadRequest {
  cwd?: string;
  lines?: number;
  path: string;
}

export interface GetMemoryRequest {
  cwd?: string;
  scope: MemoryScope;
}

export interface GetRunRequest {
  runId: string;
}

export interface GetSessionRequest {
  sessionId: string;
}

export interface GetTodosRequest {
  sessionId: string;
}

export interface Goal {
  budget: GoalBudget;
  createdAt: string;
  model?: string;
  objective: string;
  provider?: string;
  reason?: string;
  sessionId: string;
  status: GoalStatus;
  updatedAt: string;
  used: GoalUsage;
}

export interface GoalBudget {
  maxCostUsd?: number;
  maxSteps?: number;
  maxTurns?: number;
}

export interface GoalRequest {
  sessionId: string;
}

export type GoalStatus = "active" | "paused" | "blocked";

export interface GoalUsage {
  costUsd: number;
  steps: number;
  turns: number;
}

export interface GrepMatch {
  lineNumber: number;
  path: string;
  text: string;
}

export interface GrepRequest {
  cwd?: string;
  limit?: number;
  path?: string;
  query: string;
}

export interface GrepResult {
  matches: GrepMatch[];
  total: number;
}

export type HookEvent = "PreToolUse" | "PostToolUse" | "UserPromptSubmit" | "SessionStart" | "SubagentStart" | "SubagentStop" | "PreCompact" | "Stop" | "Notification";

export interface HookInfo {
  active: boolean;
  command?: string;
  event: HookEvent;
  inject?: string;
  matcher?: string;
  scope: HookScope;
  source: string;
  timeoutMs?: number;
}

export type HookScope = "global" | "project";

export interface HooksListResult {
  hooks: HookInfo[];
  projectRoot?: string;
  projectTrusted: boolean;
}

export interface ImportSessionRequest {
  artifact: SessionArtifact;
}

export interface ImportSessionResponse {
  session: Session;
}

export type Interrupt =
  | { type: "approval"; itemId: string; payload: { reason?: string; rememberable?: boolean; risk?: ApprovalRisk; tool: ToolInvocation }; runId: string }
  | { type: "question"; itemId: string; payload: { question: Question }; runId: string }
  | { type: "toolResult"; itemId: string; payload: { tool: ToolInvocation }; runId: string };

export interface InterruptPayload {
  question?: Question;
  reason?: string;
  rememberable?: boolean;
  risk?: ApprovalRisk;
  tool?: ToolInvocation;
}

export interface InterruptResponse {
  itemId: string;
  response: InterruptResponseValue;
}

export type InterruptResponseType = "approval" | "answer" | "toolResult";

export type InterruptResponseValue =
  | { type: "approval"; decision: ApprovalDecision; editedArgs?: Record<string, unknown>; reason?: string; remember?: RememberScope }
  | { type: "answer"; answers: Record<string, string[]> }
  | { type: "toolResult"; error?: ProblemData; result?: unknown };

export type InterruptType = "approval" | "question" | "toolResult";

export interface InvokeToolRequest {
  arguments: Record<string, unknown>;
  cwd?: string;
  name: string;
}

export type Item =
  | { type: "userMessage"; content?: ContentBlock[]; createdAt: string; id: string; runId: string; status: ItemStatus }
  | { type: "agentMessage"; content?: ContentBlock[]; createdAt: string; id: string; runId: string; status: ItemStatus }
  | { type: "reasoning"; createdAt: string; id: string; redacted?: boolean; runId: string; status: ItemStatus; text?: string }
  | { type: "plan"; createdAt: string; id: string; runId: string; status: ItemStatus; steps?: PlanStep[] }
  | { type: "question"; createdAt: string; id: string; question?: Question; runId: string; status: ItemStatus }
  | { type: "toolCall"; createdAt: string; error?: ProblemData; id: string; runId: string; safetyClass?: SafetyClass; status: ItemStatus; tool?: ToolInvocation }
  | { type: "compaction"; createdAt: string; droppedMessages?: number; id: string; runId: string; status: ItemStatus; summary?: string };

export type ItemDelta =
  | { type: "content"; index?: number; text: string }
  | { type: "reasoning"; text: string }
  | { type: "toolArguments"; argumentsTextDelta: string }
  | { type: "toolOutput"; text: string }
  | { type: "plan"; steps: PlanStep[] };

export type ItemDeltaType = "content" | "reasoning" | "toolArguments" | "toolOutput" | "plan";

export type ItemListScope =
  | { type: "session"; sessionId: string }
  | { type: "run"; includeDescendants?: boolean; runId: string };

export type ItemOrder = "asc" | "desc";

export type ItemScopeType = "session" | "run";

export type ItemStatus = "running" | "completed" | "incomplete";

export type ItemType = "userMessage" | "agentMessage" | "reasoning" | "plan" | "question" | "toolCall" | "compaction";

export interface ListApprovalRulesRequest {
  sessionId: string;
}

export interface ListApprovalRulesResult {
  rules: ApprovalRule[];
}

export interface ListFilesRequest {
  cursor?: string;
  cwd?: string;
  glob?: string;
  includeIgnored?: boolean;
  limit?: number;
  path?: string;
  recursive?: boolean;
}

export interface ListHooksRequest {
  cwd?: string;
}

export interface ListInterruptsRequest {
  cursor?: string;
  limit?: number;
  rootRunId?: string;
  sessionId?: string;
}

export interface ListItemsRequest {
  cursor?: string;
  limit?: number;
  order?: ItemOrder;
  scope: ItemListScope;
}

export interface ListItemsResponse {
  data: Item[];
  nextCursor?: string;
  runs: RunSummary[];
}

export interface ListModelsRequest {
  cursor?: string;
  limit?: number;
  provider?: string;
}

export interface ListRunsRequest {
  cursor?: string;
  includeDescendants?: boolean;
  limit?: number;
  sessionId?: string;
  statuses?: RunStatus[];
}

export interface MCPListToolsRequest {
  cursor?: string;
  limit?: number;
  server?: string;
}

export interface MCPServerRequest {
  server: string;
}

export interface ManagedSkill {
  description?: string;
  lifecycle: SkillLifecycle;
  name: string;
}

export type McpAuthStatus = "none" | "bearerToken" | "oauth" | "notLoggedIn";

export interface McpServer {
  authStatus?: McpAuthStatus;
  description?: string;
  error?: ProblemData;
  name: string;
  status: McpStatus;
  toolCount?: number;
}

export interface McpServerConfig {
  args?: string[];
  authorizationMasked?: string;
  autoApproveTools?: string[];
  command?: string;
  description?: string;
  dir?: string;
  disabledTools?: string[];
  enabled: boolean;
  env?: Record<string, string>;
  headers?: Record<string, string>;
  name: string;
  timeoutSeconds?: number;
  type: McpTransport;
  url?: string;
}

export type McpStatus = "connecting" | "connected" | "disconnected" | "failed" | "needsAuth";

export interface McpTestResult {
  error?: ProblemData;
  ok: boolean;
}

export interface McpTool {
  description?: string;
  inputSchema?: Record<string, unknown>;
  name: string;
  server: string;
}

export type McpTransport = "stdio" | "streamableHttp";

export interface MemoryEntry {
  content: string;
  path: string;
  scope: MemoryScope;
  updatedAt?: string;
}

export type MemoryScope = "cwd" | "projectRoot" | "home";

export type Modality = "text" | "image" | "audio" | "video" | "pdf";

export interface Model {
  capabilities?: ModelCapabilities;
  contextWindow?: number;
  deprecated?: boolean;
  displayName?: string;
  id: string;
  knowledgeCutoff?: string;
  maxInputTokens?: number;
  maxOutputTokens?: number;
  pricing?: ModelPricing;
  provider: string;
}

export interface ModelCapabilities {
  inputModalities?: Modality[];
  multimodal?: boolean;
  outputModalities?: Modality[];
  reasoning?: boolean;
  reasoningDefaultLevel?: string;
  reasoningLevels?: string[];
  structuredOutput?: boolean;
  toolUse?: boolean;
}

export interface ModelPricing {
  cacheReadUsdPerMillionTokens?: number;
  cacheWriteUsdPerMillionTokens?: number;
  inputUsdPerMillionTokens?: number;
  outputUsdPerMillionTokens?: number;
}

export interface ModelUsage {
  cacheReadTokens?: number;
  cacheWriteTokens?: number;
  costUsd?: number;
  inputTokens?: number;
  outputTokens?: number;
  reasoningTokens?: number;
}

export type PageOfAgentDoc = Page<AgentDoc>;

export type PageOfFileEntry = Page<FileEntry>;

export type PageOfManagedSkill = Page<ManagedSkill>;

export type PageOfMcpServer = Page<McpServer>;

export type PageOfMcpServerConfig = Page<McpServerConfig>;

export type PageOfMcpTool = Page<McpTool>;

export type PageOfMemoryEntry = Page<MemoryEntry>;

export type PageOfModel = Page<Model>;

export type PageOfPendingInterruptSet = Page<PendingInterruptSet>;

export type PageOfProject = Page<Project>;

export type PageOfProvider = Page<Provider>;

export type PageOfRecipe = Page<Recipe>;

export type PageOfRunRef = Page<RunRef>;

export type PageOfSchedule = Page<Schedule>;

export type PageOfSession = Page<Session>;

export type PageOfSkill = Page<Skill>;

export type PageOfSkillDraft = Page<SkillDraft>;

export type PageOfToolSpec = Page<ToolSpec>;

export type PageOfWorkspaceFileChange = Page<WorkspaceFileChange>;

export interface PageQuery {
  cursor?: string;
  limit?: number;
}

export interface PendingInterruptSet {
  createdAt: string;
  interrupts: Interrupt[];
  rootRunId: string;
  sessionId: string;
}

export interface PlanStep {
  id: string;
  status: PlanStepStatus;
  title: string;
}

export type PlanStepStatus = "pending" | "running" | "completed" | "failed";

export interface ProblemData {
  activeRun?: ActiveRunRef;
  detail?: string;
  docUrl?: string;
  errors?: FieldError[];
  requiredCapabilities?: CapabilityRequirement[];
  retryAfterSeconds?: number;
  type: string;
}

export interface Project {
  branch?: string;
  cwd: string;
  cwdMissing?: boolean;
  lastActiveAt?: string;
  name: string;
  projectRoot?: string;
  sessionCount: number;
}

export interface ProtocolRange {
  current: string;
  minSupported: string;
}

export interface Provider {
  apiKeyMasked: string;
  baseUrl?: string;
  defaultEmbeddingModel?: string;
  embeddingCapable?: boolean;
  id: string;
  keySource?: ProviderKeySource;
  requiresBaseUrl?: boolean;
}

export type ProviderKeySource = "stored" | "env";

export interface ProviderTestResult {
  error?: ProblemData;
  ok: boolean;
}

export interface Question {
  fields: QuestionField[];
  prompt: string;
}

export type QuestionField =
  | { type: "text"; header?: string; label: string; name: string; required?: boolean }
  | { type: "choice"; header?: string; label: string; multiple?: boolean; name: string; options: QuestionOption[]; required?: boolean };

export type QuestionFieldType = "text" | "choice";

export interface QuestionOption {
  description?: string;
  label: string;
  preview?: string;
}

export interface ReadFileRequest {
  cwd?: string;
  endLine?: number;
  maxBytes?: number;
  path: string;
  startLine?: number;
}

export interface Recipe {
  argumentHint?: string;
  body: string;
  description?: string;
  name: string;
  scope: RecipeScope;
  source: string;
}

export type RecipeScope = "project" | "global";

export interface RememberScope {
  scope: RememberScopeKind;
}

export type RememberScopeKind = "session" | "project" | "global";

export interface RemoveMCPServerRequest {
  name: string;
}

export interface RequestMeta {
  clientCapabilities?: ClientCapabilities;
  clientInfo?: ClientInfo;
  protocolVersion?: string;
}

export type RestoreType = "history" | "files" | "both";

export interface ResumeRunRequest {
  input?: ContentBlock[];
  responses: InterruptResponse[];
  runId: string;
}

export interface RollbackSessionRequest {
  restoreType?: RestoreType;
  sessionId: string;
  toRunId?: string;
}

export interface RollbackSessionResponse {
  droppedRuns: DroppedRun[];
  session: Session;
}

export interface RunEvent {
  event: StreamEvent;
  eventId: string;
  runId: string;
  segmentId: string;
  timestamp: string;
}

export interface RunLimits {
  maxBudgetUsd?: number;
  maxSteps?: number;
}

export interface RunMetrics {
  activeDurationMs: number;
  steps: number;
  usage?: Usage;
}

export type RunOutcome =
  | { type: "completed" }
  | { type: "error"; error: ProblemData }
  | { type: "maxSteps"; detail?: string }
  | { type: "maxBudget"; detail?: string }
  | { type: "canceled"; detail?: string };

export type RunOutcomeType = "completed" | "error" | "maxSteps" | "maxBudget" | "canceled";

export interface RunProgress {
  activity?: string;
  contextTokens?: number;
  step?: number;
  usage?: Usage;
}

export interface RunProtocolProfile {
  interruptTypes: InterruptType[];
  requiredFeatures: string[];
}

export interface RunRef {
  activeSegmentId?: string;
  createdAt?: string;
  finishedAt?: string;
  id: string;
  limits?: RunLimits;
  metrics: RunMetrics;
  model?: string;
  outcome?: RunOutcome;
  parentRunId?: string;
  protocolProfile: RunProtocolProfile;
  provider?: string;
  rootRunId?: string;
  sessionId: string;
  spawnedByItemId?: string;
  status?: RunStatus;
}

export interface RunScheduleNowRequest {
  id: string;
}

export interface RunScheduleNowResponse {
  runId: string;
  sessionId: string;
}

export type RunStatus = "running" | "waiting" | "finished";

export interface RunSummary {
  createdAt?: string;
  finishedAt?: string;
  id: string;
  model?: string;
  outcome?: RunOutcome;
  parentRunId?: string;
  provider?: string;
  rootRunId?: string;
  sessionId: string;
  spawnedByItemId?: string;
  status?: RunStatus;
}

export interface RuntimeLimits {
  maxConcurrentRuns?: number;
}

export type SafetyClass = "safe" | "write" | "exec" | "network";

export interface Schedule {
  createdAt: string;
  cron: string;
  cwd?: string;
  enabled: boolean;
  id: string;
  lastRunAt?: string;
  model?: string;
  nextRunAt?: string;
  prompt: string;
  provider?: string;
  revision: number;
  title: string;
}

export interface SearchHit {
  lineNumber?: number;
  path: string;
  snippet?: string;
}

export type SegmentOutcome =
  | { type: "interrupt"; interrupts: Interrupt[] }
  | { type: "suspended" }
  | { type: "completed" }
  | { type: "error"; error: ProblemData }
  | { type: "maxSteps"; detail?: string }
  | { type: "maxBudget"; detail?: string }
  | { type: "canceled"; detail?: string };

export type SegmentOutcomeType = "interrupt" | "suspended" | "completed" | "error" | "maxSteps" | "maxBudget" | "canceled";

export interface ServerCapabilities {
  events: StreamEventType[];
  features: Record<string, FeatureCapability>;
  limits: RuntimeLimits;
  streamingMethods: string[];
}

export interface ServerInfo {
  cwd: string;
  home: string;
  name: string;
  version: string;
}

export interface Session {
  createdAt: string;
  cwd: string;
  cwdMissing?: boolean;
  favorite?: boolean;
  id: string;
  model: string;
  projectRoot?: string;
  revision: number;
  status: SessionStatus;
  title: string;
  updatedAt: string;
}

export interface SessionArtifact {
  items: ArtifactItem[];
  messages: unknown[];
  runs: ArtifactRun[];
  session: ArtifactSession;
  toolResults: ArtifactToolResult[];
  version: number;
}

export type SessionStatus = "running" | "waiting" | "idle";

export interface SessionUsageRequest {
  sessionId: string;
}

export interface SetApprovalModeRequest {
  mode: ApprovalMode;
}

export interface SetHookTrustRequest {
  projectRoot: string;
  trusted: boolean;
}

export interface SetMCPEnabledRequest {
  enabled: boolean;
  name: string;
}

export interface Skill {
  description?: string;
  name: string;
  source?: SkillSource;
}

export interface SkillDraft {
  createdBy?: string;
  description?: string;
  name: string;
  revision: string;
  sourceSession?: string;
}

export interface SkillDraftRef {
  name: string;
  revision: string;
}

export type SkillLifecycle = "active" | "archived";

export interface SkillNameRequest {
  name: string;
}

export type SkillSource = "project" | "global";

export type Stability = "stable" | "experimental";

export interface StartGoalRequest {
  budget?: GoalBudget;
  model?: string;
  objective: string;
  provider?: string;
  sessionId: string;
}

export interface StartRunRequest {
  input: ContentBlock[];
  maxBudgetUsd?: number;
  maxSteps?: number;
  model?: string;
  params?: GenerationParams;
  provider?: string;
  sessionId: string;
}

export interface StartRunResponse {
  runId: string;
  segmentId: string;
  userItemId?: string;
}

export type StateSnapshot =
  | { type: "todos"; revision: number; sessionId: string; todos: TodoSnapshot[]; updatedAt?: string };

export type StateSnapshotType = "todos";

export interface SteerRunRequest {
  message: string;
  runId: string;
}

export type StreamEvent =
  | { type: "segment.started"; run: RunRef }
  | { type: "segment.progress"; progress: RunProgress }
  | { type: "segment.finished"; metrics: RunMetrics; outcome: SegmentOutcome }
  | { type: "item.started"; item: Item }
  | { type: "item.delta"; delta: ItemDelta; itemId: string }
  | { type: "item.completed"; item: Item }
  | { type: "state.snapshot"; state: StateSnapshot }
  | { type: "custom"; durable?: boolean; name: string; payload?: unknown };

export type StreamEventType = "segment.started" | "segment.progress" | "segment.finished" | "item.started" | "item.delta" | "item.completed" | "state.snapshot" | "custom";

export interface SubscribeRunRequest {
  runId: string;
}

export interface TestProviderRequest {
  provider: string;
}

export interface TodoSnapshot {
  blockedReason?: string;
  id: string;
  nextAction?: string;
  status: TodoStatus;
  text: string;
}

export type TodoStatus = "pending" | "in_progress" | "completed";

export interface ToolInvocation {
  arguments: Record<string, unknown>;
  name: string;
  result?: unknown;
}

export interface ToolSpec {
  description?: string;
  name: string;
  parameters?: Record<string, unknown>;
  safetyClass?: SafetyClass;
}

export interface UpdateMemoryRequest {
  content: string;
  cwd?: string;
  scope: MemoryScope;
}

export interface UpdateScheduleRequest {
  cron?: string;
  cwd?: string;
  enabled?: boolean;
  expectedRevision: number;
  id: string;
  model?: string;
  prompt?: string;
  provider?: string;
  title?: string;
}

export interface UpdateSessionRequest {
  cwd?: string;
  expectedRevision: number;
  favorite?: boolean;
  model?: string;
  sessionId: string;
  title?: string;
}

export interface Usage {
  byModel?: Record<string, ModelUsage>;
  cacheReadTokens?: number;
  cacheWriteTokens?: number;
  costUsd?: number;
  inputTokens?: number;
  outputTokens?: number;
  reasoningTokens?: number;
}

export interface UsageBucket {
  cacheReadTokens?: number;
  cacheWriteTokens?: number;
  costUsd?: number;
  inputTokens?: number;
  key: string;
  outputTokens?: number;
  reasoningTokens?: number;
  runs?: number;
}

export interface UsageSummary {
  byDay?: UsageBucket[];
  byModel?: UsageBucket[];
  byProvider?: UsageBucket[];
  runs?: number;
  sessions?: number;
  total: ModelUsage;
}

export interface UsageSummaryRequest {
  sinceDays?: number;
}

export interface UtilityRole {
  model?: string;
  provider?: string;
}

export interface WatchSpec {
  cwd?: string;
  path?: string;
  watchId: string;
}

export interface WebSearchResult {
  faviconUrl?: string;
  snippet?: string;
  title?: string;
  url: string;
}

export type WorkspaceEvent =
  | { type: "files.changed"; cwd?: string; paths: string[]; sequence: number; watchId?: string }
  | { type: "skills.changed"; sequence: number }
  | { type: "mcp.serverChanged"; error?: ProblemData; sequence: number; server: string; status?: McpStatus; toolCount?: number }
  | { type: "schedules.fired"; scheduleId: string; sequence: number }
  | { type: "resync"; sequence: number };

export type WorkspaceEventType = "files.changed" | "skills.changed" | "mcp.serverChanged" | "schedules.fired" | "resync";

export interface WorkspaceFileChange {
  added?: number;
  binary?: boolean;
  path: string;
  previousPath?: string;
  removed?: number;
  status: FileStatus;
}

export interface WorkspaceListQuery {
  cursor?: string;
  cwd?: string;
  limit?: number;
}

export interface WorkspaceSubscribeRequest {
  watches?: WatchSpec[];
}

export interface WorkspaceSubscribeResponse {
}

// The closed value sets, as data: a union type does not exist at runtime.
export const WIRE_ENUMS = {
  AgentDocScope: ["cwd", "projectRoot", "home"],
  AgentMemoryOrigin: ["auto", "user"],
  AgentMemoryReviewDecision: ["approve", "reject"],
  AgentMemoryScope: ["project", "user"],
  AgentMemoryStatus: ["active", "pending"],
  ApprovalDecision: ["approve", "deny"],
  ApprovalMode: ["safe", "balanced", "yolo", "plan"],
  ApprovalRisk: ["low", "medium", "high"],
  ApprovalRuleDecision: ["allow", "deny"],
  ApprovalRuleScope: ["session", "project", "global"],
  ArtifactOutcomeType: ["completed", "error", "maxSteps", "maxBudget", "canceled"],
  ArtifactProblemType: ["internalError", "runLost", "agentStuck", "rateLimited", "invalidApiKey", "timeout", "providerUnavailable", "providerRejected", "deniedByUser", "toolFailed"],
  CapabilityRequirementType: ["feature", "interruptType", "runtimeTopic", "stateSnapshot"],
  CodebaseState: ["none", "indexing", "ready", "error"],
  ContentBlockType: ["text", "image"],
  DiffFormat: ["rows", "raw"],
  DiffMode: ["worktree", "base"],
  DiffRowType: ["hunk", "context", "added", "deleted"],
  ExportFormat: ["md", "json"],
  FeedbackRating: ["positive", "negative"],
  FileEntryType: ["file", "dir", "symlink"],
  FileStatus: ["added", "modified", "deleted", "renamed", "untracked"],
  GoalStatus: ["active", "paused", "blocked"],
  HookEvent: ["PreToolUse", "PostToolUse", "UserPromptSubmit", "SessionStart", "SubagentStart", "SubagentStop", "PreCompact", "Stop", "Notification"],
  HookScope: ["global", "project"],
  InterruptResponseType: ["approval", "answer", "toolResult"],
  InterruptType: ["approval", "question", "toolResult"],
  ItemDeltaType: ["content", "reasoning", "toolArguments", "toolOutput", "plan"],
  ItemOrder: ["asc", "desc"],
  ItemScopeType: ["session", "run"],
  ItemStatus: ["running", "completed", "incomplete"],
  ItemType: ["userMessage", "agentMessage", "reasoning", "plan", "question", "toolCall", "compaction"],
  McpAuthStatus: ["none", "bearerToken", "oauth", "notLoggedIn"],
  McpStatus: ["connecting", "connected", "disconnected", "failed", "needsAuth"],
  McpTransport: ["stdio", "streamableHttp"],
  MemoryScope: ["cwd", "projectRoot", "home"],
  Modality: ["text", "image", "audio", "video", "pdf"],
  PlanStepStatus: ["pending", "running", "completed", "failed"],
  ProviderKeySource: ["stored", "env"],
  QuestionFieldType: ["text", "choice"],
  RecipeScope: ["project", "global"],
  RememberScopeKind: ["session", "project", "global"],
  RestoreType: ["history", "files", "both"],
  RunOutcomeType: ["completed", "error", "maxSteps", "maxBudget", "canceled"],
  RunStatus: ["running", "waiting", "finished"],
  SafetyClass: ["safe", "write", "exec", "network"],
  SegmentOutcomeType: ["interrupt", "suspended", "completed", "error", "maxSteps", "maxBudget", "canceled"],
  SessionStatus: ["running", "waiting", "idle"],
  SkillLifecycle: ["active", "archived"],
  SkillSource: ["project", "global"],
  Stability: ["stable", "experimental"],
  StateSnapshotType: ["todos"],
  StreamEventType: ["segment.started", "segment.progress", "segment.finished", "item.started", "item.delta", "item.completed", "state.snapshot", "custom"],
  TodoStatus: ["pending", "in_progress", "completed"],
  WorkspaceEventType: ["files.changed", "skills.changed", "mcp.serverChanged", "schedules.fired", "resync"],
} as const;
