// Code generated by cmd/contractgen. DO NOT EDIT.
//
// The runtime checks of the Lyra Runtime Protocol, compiled from the same schema
// tree that produces contract/schema.json — so a rule the published schema states
// is a rule this file enforces, structurally rather than by remembering to.
//
// What each call MEANS lives in wireCheck.ts. This file only says which rule
// applies where.

import { absent, allOf, anything, array, enumOf, fields, flag, ifThen, integer, literal, minLength, minimum, numeric, object, oneOf, record, ref, text } from "./wireCheck";
import type { WireCheck, WireViolation } from "./wireCheck";

/** Every shape the protocol publishes. */
export type WireTypeName =
  | "AgentDoc"
  | "AgentDocScope"
  | "AgentMemoryAddRequest"
  | "AgentMemoryItem"
  | "AgentMemoryItemRequest"
  | "AgentMemoryList"
  | "AgentMemoryListRequest"
  | "AgentMemoryOrigin"
  | "AgentMemoryReviewDecision"
  | "AgentMemoryReviewRequest"
  | "AgentMemoryScope"
  | "AgentMemoryStatus"
  | "AgentMemoryUpdateRequest"
  | "ApprovalDecision"
  | "ApprovalMode"
  | "ApprovalModeResult"
  | "ApprovalRisk"
  | "ApprovalRule"
  | "ApprovalRuleDecision"
  | "ApprovalRuleScope"
  | "ArtifactContentBlock"
  | "ArtifactItem"
  | "ArtifactModelUsage"
  | "ArtifactOutcome"
  | "ArtifactOutcomeType"
  | "ArtifactPlanStep"
  | "ArtifactProblem"
  | "ArtifactProblemType"
  | "ArtifactQuestion"
  | "ArtifactQuestionField"
  | "ArtifactQuestionOption"
  | "ArtifactRun"
  | "ArtifactRunLimits"
  | "ArtifactRunMetrics"
  | "ArtifactSession"
  | "ArtifactToolInvocation"
  | "ArtifactToolResult"
  | "ArtifactUsage"
  | "CancelRunRequest"
  | "ClientCapabilities"
  | "ClientInfo"
  | "CodebaseHit"
  | "CodebaseReindexRequest"
  | "CodebaseReindexResponse"
  | "CodebaseSearchRequest"
  | "CodebaseSearchResult"
  | "CodebaseState"
  | "CodebaseStatus"
  | "CodebaseStatusRequest"
  | "ConfigureMCPServerRequest"
  | "ConfigureProviderRequest"
  | "ContentBlock"
  | "ContentBlockType"
  | "CreateScheduleRequest"
  | "CreateSessionRequest"
  | "DeleteScheduleRequest"
  | "DeleteSessionRequest"
  | "Diff"
  | "DiffFormat"
  | "DiffMode"
  | "DiffRow"
  | "DiffRowType"
  | "DiscoverResponse"
  | "DroppedRun"
  | "EmbeddingRole"
  | "ErrorChannel"
  | "ExportFormat"
  | "ExportSessionRequest"
  | "ExportSessionResponse"
  | "FeatureCapability"
  | "FeaturePreference"
  | "FeedbackRating"
  | "FeedbackRequest"
  | "FieldError"
  | "FileContent"
  | "FileDiff"
  | "FileEdit"
  | "FileEntry"
  | "FileEntryType"
  | "FileHead"
  | "FileLine"
  | "FileStatus"
  | "ForgetApprovalRuleRequest"
  | "ForkSessionRequest"
  | "GenerationParams"
  | "GetDiffRequest"
  | "GetFileHeadRequest"
  | "GetMemoryRequest"
  | "GetSessionRequest"
  | "Goal"
  | "GoalBudget"
  | "GoalRequest"
  | "GoalStatus"
  | "GoalUsage"
  | "GrepMatch"
  | "GrepRequest"
  | "GrepResult"
  | "HookEvent"
  | "HookInfo"
  | "HookScope"
  | "HooksListResult"
  | "ImportSessionRequest"
  | "ImportSessionResponse"
  | "Interrupt"
  | "InterruptPayload"
  | "InterruptResponse"
  | "InterruptResponseType"
  | "InterruptResponseValue"
  | "InterruptType"
  | "InvokeToolRequest"
  | "Item"
  | "ItemDelta"
  | "ItemDeltaType"
  | "ItemStatus"
  | "ItemType"
  | "ListApprovalRulesRequest"
  | "ListApprovalRulesResult"
  | "ListFilesRequest"
  | "ListHooksRequest"
  | "ListItemsRequest"
  | "ListItemsResponse"
  | "ListModelsRequest"
  | "ListOpenInterruptsRequest"
  | "ListRunsRequest"
  | "MCPListToolsRequest"
  | "MCPServerRequest"
  | "ManagedSkill"
  | "McpAuthStatus"
  | "McpServer"
  | "McpServerConfig"
  | "McpStatus"
  | "McpTestResult"
  | "McpTool"
  | "McpTransport"
  | "MemoryEntry"
  | "MemoryScope"
  | "Modality"
  | "Model"
  | "ModelCapabilities"
  | "ModelPricing"
  | "ModelUsage"
  | "OpenInterrupt"
  | "PageOfAgentDoc"
  | "PageOfFileEntry"
  | "PageOfManagedSkill"
  | "PageOfMcpServer"
  | "PageOfMcpServerConfig"
  | "PageOfMcpTool"
  | "PageOfMemoryEntry"
  | "PageOfModel"
  | "PageOfOpenInterrupt"
  | "PageOfProject"
  | "PageOfProvider"
  | "PageOfRecipe"
  | "PageOfRunRef"
  | "PageOfSchedule"
  | "PageOfSession"
  | "PageOfSkill"
  | "PageOfSkillDraft"
  | "PageOfToolSpec"
  | "PageOfWorkspaceFileChange"
  | "PageQuery"
  | "PlanStep"
  | "PlanStepStatus"
  | "ProblemData"
  | "Project"
  | "ProtocolRange"
  | "Provider"
  | "ProviderKeySource"
  | "ProviderTestResult"
  | "Question"
  | "QuestionField"
  | "QuestionFieldType"
  | "QuestionOption"
  | "ReadFileRequest"
  | "Recipe"
  | "RecipeScope"
  | "RememberScope"
  | "RememberScopeKind"
  | "RemoveMCPServerRequest"
  | "RequestMeta"
  | "RestoreType"
  | "ResumeRunRequest"
  | "RollbackSessionRequest"
  | "RollbackSessionResponse"
  | "RunEvent"
  | "RunLimits"
  | "RunMetrics"
  | "RunOutcome"
  | "RunOutcomeType"
  | "RunProgress"
  | "RunRef"
  | "RunScheduleNowRequest"
  | "RunScheduleNowResponse"
  | "RunStatus"
  | "RuntimeLimits"
  | "SafetyClass"
  | "Schedule"
  | "SearchHit"
  | "SegmentOutcome"
  | "SegmentOutcomeType"
  | "ServerCapabilities"
  | "ServerInfo"
  | "Session"
  | "SessionArtifact"
  | "SessionStatus"
  | "SessionUsageRequest"
  | "SetApprovalModeRequest"
  | "SetHookTrustRequest"
  | "SetMCPEnabledRequest"
  | "Skill"
  | "SkillDraft"
  | "SkillDraftRef"
  | "SkillLifecycle"
  | "SkillNameRequest"
  | "SkillSource"
  | "Stability"
  | "StartGoalRequest"
  | "StartRunRequest"
  | "StartRunResponse"
  | "SteerRunRequest"
  | "StreamEvent"
  | "StreamEventType"
  | "SubscribeRunRequest"
  | "TestProviderRequest"
  | "TodoSnapshot"
  | "TodoStatus"
  | "ToolInvocation"
  | "ToolSpec"
  | "UpdateMemoryRequest"
  | "UpdateScheduleRequest"
  | "UpdateSessionRequest"
  | "Usage"
  | "UsageBucket"
  | "UsageSummary"
  | "UsageSummaryRequest"
  | "UtilityRole"
  | "WatchSpec"
  | "WebSearchResult"
  | "WorkspaceEvent"
  | "WorkspaceEventType"
  | "WorkspaceFileChange"
  | "WorkspaceListQuery"
  | "WorkspaceSubscribeRequest"
  | "WorkspaceSubscribeResponse"
  ;

const CHECKS: Record<WireTypeName, WireCheck> = {
  AgentDoc: object({
    path: text(),
    scope: ref(() => CHECKS.AgentDocScope),
    title: text(),
  }, ["path", "scope"]),
  AgentDocScope: enumOf(["cwd", "projectRoot", "home"]),
  AgentMemoryAddRequest: object({
    content: allOf([text(), minLength(1)]),
    cwd: text(),
    scope: ref(() => CHECKS.AgentMemoryScope),
  }, ["content"]),
  AgentMemoryItem: object({
    content: text(),
    createdAt: text(),
    day: text(),
    id: text(),
    origin: ref(() => CHECKS.AgentMemoryOrigin),
    pinned: flag(),
    scope: ref(() => CHECKS.AgentMemoryScope),
    sessionId: text(),
    status: ref(() => CHECKS.AgentMemoryStatus),
    updatedAt: text(),
  }, ["content", "createdAt", "id", "origin", "pinned", "scope", "status", "updatedAt"]),
  AgentMemoryItemRequest: object({
    id: allOf([text(), minLength(1)]),
  }, ["id"]),
  AgentMemoryList: object({
    items: array(ref(() => CHECKS.AgentMemoryItem)),
  }, ["items"]),
  AgentMemoryListRequest: object({
    cwd: text(),
    scope: ref(() => CHECKS.AgentMemoryScope),
  }, []),
  AgentMemoryOrigin: enumOf(["auto", "user"]),
  AgentMemoryReviewDecision: enumOf(["approve", "reject"]),
  AgentMemoryReviewRequest: object({
    decision: ref(() => CHECKS.AgentMemoryReviewDecision),
    id: allOf([text(), minLength(1)]),
  }, ["decision", "id"]),
  AgentMemoryScope: enumOf(["project", "user"]),
  AgentMemoryStatus: enumOf(["active", "pending"]),
  AgentMemoryUpdateRequest: object({
    content: text(),
    id: allOf([text(), minLength(1)]),
    pinned: flag(),
  }, ["id"]),
  ApprovalDecision: enumOf(["approve", "deny"]),
  ApprovalMode: enumOf(["safe", "balanced", "yolo", "plan"]),
  ApprovalModeResult: object({
    mode: ref(() => CHECKS.ApprovalMode),
  }, ["mode"]),
  ApprovalRisk: enumOf(["low", "medium", "high"]),
  ApprovalRule: object({
    decision: ref(() => CHECKS.ApprovalRuleDecision),
    dir: text(),
    id: text(),
    scope: ref(() => CHECKS.ApprovalRuleScope),
    subject: text(),
    tool: text(),
  }, ["decision", "id", "scope", "tool"]),
  ApprovalRuleDecision: enumOf(["allow", "deny"]),
  ApprovalRuleScope: enumOf(["session", "project", "global"]),
  ArtifactContentBlock: allOf([
    object({
      data: text(),
      mime: text(),
      text: text(),
      type: ref(() => CHECKS.ContentBlockType),
    }, []),
    oneOf([
      fields({
        data: absent(),
        mime: absent(),
        type: literal("text"),
      }, ["text", "type"]),
      fields({
        text: absent(),
        type: literal("image"),
      }, ["data", "mime", "type"]),
    ]),
  ]),
  ArtifactItem: allOf([
    object({
      content: array(ref(() => CHECKS.ArtifactContentBlock)),
      createdAt: text(),
      droppedMessages: integer(),
      error: ref(() => CHECKS.ArtifactProblem),
      id: text(),
      question: ref(() => CHECKS.ArtifactQuestion),
      redacted: flag(),
      runId: text(),
      safetyClass: ref(() => CHECKS.SafetyClass),
      status: ref(() => CHECKS.ItemStatus),
      steps: array(ref(() => CHECKS.ArtifactPlanStep)),
      summary: text(),
      text: text(),
      tool: ref(() => CHECKS.ArtifactToolInvocation),
      type: ref(() => CHECKS.ItemType),
    }, []),
    oneOf([
      fields({
        droppedMessages: absent(),
        error: absent(),
        question: absent(),
        redacted: absent(),
        safetyClass: absent(),
        steps: absent(),
        summary: absent(),
        text: absent(),
        tool: absent(),
        type: literal("userMessage"),
      }, ["createdAt", "id", "runId", "status", "type"]),
      fields({
        droppedMessages: absent(),
        error: absent(),
        question: absent(),
        redacted: absent(),
        safetyClass: absent(),
        steps: absent(),
        summary: absent(),
        text: absent(),
        tool: absent(),
        type: literal("agentMessage"),
      }, ["createdAt", "id", "runId", "status", "type"]),
      fields({
        content: absent(),
        droppedMessages: absent(),
        error: absent(),
        question: absent(),
        safetyClass: absent(),
        steps: absent(),
        summary: absent(),
        tool: absent(),
        type: literal("reasoning"),
      }, ["createdAt", "id", "runId", "status", "type"]),
      fields({
        content: absent(),
        droppedMessages: absent(),
        error: absent(),
        question: absent(),
        redacted: absent(),
        safetyClass: absent(),
        summary: absent(),
        text: absent(),
        tool: absent(),
        type: literal("plan"),
      }, ["createdAt", "id", "runId", "status", "type"]),
      fields({
        content: absent(),
        droppedMessages: absent(),
        error: absent(),
        redacted: absent(),
        safetyClass: absent(),
        steps: absent(),
        summary: absent(),
        text: absent(),
        tool: absent(),
        type: literal("question"),
      }, ["createdAt", "id", "runId", "status", "type"]),
      fields({
        content: absent(),
        droppedMessages: absent(),
        question: absent(),
        redacted: absent(),
        steps: absent(),
        summary: absent(),
        text: absent(),
        type: literal("toolCall"),
      }, ["createdAt", "id", "runId", "status", "type"]),
      fields({
        content: absent(),
        error: absent(),
        question: absent(),
        redacted: absent(),
        safetyClass: absent(),
        steps: absent(),
        text: absent(),
        tool: absent(),
        type: literal("compaction"),
      }, ["createdAt", "id", "runId", "status", "type"]),
    ]),
  ]),
  ArtifactModelUsage: object({
    cacheReadTokens: integer(),
    cacheWriteTokens: integer(),
    costUsd: numeric(),
    inputTokens: integer(),
    outputTokens: integer(),
    reasoningTokens: integer(),
  }, []),
  ArtifactOutcome: allOf([
    object({
      detail: text(),
      error: ref(() => CHECKS.ArtifactProblem),
      type: ref(() => CHECKS.ArtifactOutcomeType),
    }, []),
    oneOf([
      fields({
        detail: absent(),
        error: absent(),
        type: literal("completed"),
      }, ["type"]),
      fields({
        detail: absent(),
        type: literal("error"),
      }, ["error", "type"]),
      fields({
        error: absent(),
        type: literal("maxSteps"),
      }, ["type"]),
      fields({
        error: absent(),
        type: literal("maxBudget"),
      }, ["type"]),
      fields({
        error: absent(),
        type: literal("canceled"),
      }, ["type"]),
    ]),
    ifThen(
      fields({
        type: literal("error"),
      }, ["type"]),
      fields({
        detail: absent(),
      }, ["error"]),
    ),
  ]),
  ArtifactOutcomeType: enumOf(["completed", "error", "maxSteps", "maxBudget", "canceled"]),
  ArtifactPlanStep: object({
    id: text(),
    status: ref(() => CHECKS.PlanStepStatus),
    title: text(),
  }, ["id", "status", "title"]),
  ArtifactProblem: object({
    detail: text(),
    docUrl: text(),
    retryAfterSeconds: integer(),
    retryable: flag(),
    type: ref(() => CHECKS.ArtifactProblemType),
  }, ["type"]),
  ArtifactProblemType: enumOf(["internalError", "runLost", "agentStuck", "rateLimited", "invalidApiKey", "timeout", "providerUnavailable", "providerRejected", "deniedByUser", "toolFailed"]),
  ArtifactQuestion: object({
    fields: array(ref(() => CHECKS.ArtifactQuestionField)),
    prompt: text(),
  }, ["fields", "prompt"]),
  ArtifactQuestionField: object({
    header: text(),
    label: text(),
    multiple: flag(),
    name: text(),
    options: array(ref(() => CHECKS.ArtifactQuestionOption)),
    required: flag(),
    type: ref(() => CHECKS.QuestionFieldType),
  }, ["label", "name", "type"]),
  ArtifactQuestionOption: object({
    description: text(),
    label: text(),
    preview: text(),
  }, ["label"]),
  ArtifactRun: object({
    createdAt: text(),
    finishedAt: text(),
    id: text(),
    limits: ref(() => CHECKS.ArtifactRunLimits),
    messageMark: integer(),
    metrics: ref(() => CHECKS.ArtifactRunMetrics),
    model: text(),
    outcome: ref(() => CHECKS.ArtifactOutcome),
    provider: text(),
    sessionId: text(),
    spawnedByItemId: text(),
    updatedAt: text(),
  }, ["createdAt", "finishedAt", "id", "messageMark", "metrics", "outcome", "sessionId", "updatedAt"]),
  ArtifactRunLimits: object({
    maxBudgetUsd: numeric(),
    maxSteps: integer(),
  }, []),
  ArtifactRunMetrics: object({
    activeDurationMs: integer(),
    steps: integer(),
    usage: ref(() => CHECKS.ArtifactUsage),
  }, ["activeDurationMs", "steps"]),
  ArtifactSession: object({
    createdAt: text(),
    cwd: text(),
    favorite: flag(),
    id: text(),
    model: text(),
    title: text(),
    updatedAt: text(),
  }, ["createdAt", "cwd", "id", "model", "title", "updatedAt"]),
  ArtifactToolInvocation: object({
    arguments: record(anything()),
    name: text(),
    result: anything(),
  }, ["arguments", "name"]),
  ArtifactToolResult: object({
    body: text(),
    createdAt: text(),
    id: text(),
    itemId: text(),
    preview: text(),
    toolName: text(),
  }, ["body", "createdAt", "id", "itemId", "preview", "toolName"]),
  ArtifactUsage: object({
    byModel: record(ref(() => CHECKS.ArtifactModelUsage)),
    cacheReadTokens: integer(),
    cacheWriteTokens: integer(),
    costUsd: numeric(),
    inputTokens: integer(),
    outputTokens: integer(),
    reasoningTokens: integer(),
  }, []),
  CancelRunRequest: object({
    reason: text(),
    runId: allOf([text(), minLength(1)]),
  }, ["runId"]),
  ClientCapabilities: object({
    events: array(ref(() => CHECKS.StreamEventType)),
    excludedEvents: array(ref(() => CHECKS.StreamEventType)),
    features: record(ref(() => CHECKS.FeaturePreference)),
    interruptTypes: array(ref(() => CHECKS.InterruptType)),
  }, ["events"]),
  ClientInfo: object({
    name: text(),
    version: text(),
  }, ["name", "version"]),
  CodebaseHit: object({
    endLine: integer(),
    path: text(),
    score: numeric(),
    snippet: text(),
    startLine: integer(),
  }, ["endLine", "path", "score", "snippet", "startLine"]),
  CodebaseReindexRequest: object({
    cwd: text(),
  }, []),
  CodebaseReindexResponse: object({
    operationId: text(),
  }, ["operationId"]),
  CodebaseSearchRequest: object({
    cwd: text(),
    limit: integer(),
    query: allOf([text(), minLength(1)]),
  }, ["query"]),
  CodebaseSearchResult: object({
    hits: array(ref(() => CHECKS.CodebaseHit)),
  }, ["hits"]),
  CodebaseState: enumOf(["none", "indexing", "ready", "error"]),
  CodebaseStatus: object({
    chunkCount: integer(),
    fileCount: integer(),
    indexedAt: text(),
    modelId: text(),
    operationId: text(),
    state: ref(() => CHECKS.CodebaseState),
    truncated: flag(),
  }, ["chunkCount", "fileCount", "state"]),
  CodebaseStatusRequest: object({
    cwd: text(),
  }, []),
  ConfigureMCPServerRequest: object({
    args: array(text()),
    authorization: text(),
    autoApproveTools: array(text()),
    command: text(),
    description: text(),
    dir: text(),
    disabledTools: array(text()),
    enabled: flag(),
    env: record(text()),
    headers: record(text()),
    name: allOf([text(), minLength(1)]),
    timeoutSeconds: integer(),
    type: ref(() => CHECKS.McpTransport),
    url: text(),
  }, ["enabled", "name", "type"]),
  ConfigureProviderRequest: object({
    apiKey: text(),
    baseUrl: text(),
    provider: allOf([text(), minLength(1)]),
  }, ["provider"]),
  ContentBlock: allOf([
    object({
      data: text(),
      mime: text(),
      text: text(),
      type: ref(() => CHECKS.ContentBlockType),
    }, []),
    oneOf([
      fields({
        data: absent(),
        mime: absent(),
        type: literal("text"),
      }, ["text", "type"]),
      fields({
        text: absent(),
        type: literal("image"),
      }, ["data", "mime", "type"]),
    ]),
  ]),
  ContentBlockType: enumOf(["text", "image"]),
  CreateScheduleRequest: object({
    cron: text(),
    cwd: text(),
    model: text(),
    prompt: text(),
    provider: text(),
    title: text(),
  }, ["cron", "prompt"]),
  CreateSessionRequest: object({
    cwd: text(),
    title: text(),
  }, []),
  DeleteScheduleRequest: object({
    id: allOf([text(), minLength(1)]),
  }, ["id"]),
  DeleteSessionRequest: object({
    sessionId: allOf([text(), minLength(1)]),
  }, ["sessionId"]),
  Diff: object({
    files: array(ref(() => CHECKS.FileDiff)),
    patch: text(),
    truncated: flag(),
  }, []),
  DiffFormat: enumOf(["rows", "raw"]),
  DiffMode: enumOf(["worktree", "base"]),
  DiffRow: allOf([
    object({
      code: text(),
      leftLine: integer(),
      rightLine: integer(),
      text: text(),
      type: ref(() => CHECKS.DiffRowType),
    }, []),
    oneOf([
      fields({
        code: absent(),
        leftLine: absent(),
        rightLine: absent(),
        type: literal("hunk"),
      }, ["text", "type"]),
      fields({
        text: absent(),
        type: literal("context"),
      }, ["code", "leftLine", "rightLine", "type"]),
      fields({
        leftLine: absent(),
        text: absent(),
        type: literal("added"),
      }, ["code", "rightLine", "type"]),
      fields({
        rightLine: absent(),
        text: absent(),
        type: literal("deleted"),
      }, ["code", "leftLine", "type"]),
    ]),
  ]),
  DiffRowType: enumOf(["hunk", "context", "added", "deleted"]),
  DiscoverResponse: object({
    capabilities: ref(() => CHECKS.ServerCapabilities),
    protocol: ref(() => CHECKS.ProtocolRange),
    serverInfo: ref(() => CHECKS.ServerInfo),
  }, ["capabilities", "protocol", "serverInfo"]),
  DroppedRun: object({
    run: ref(() => CHECKS.RunRef),
    userInput: array(ref(() => CHECKS.ContentBlock)),
  }, ["run"]),
  EmbeddingRole: object({
    model: text(),
    provider: text(),
  }, []),
  ErrorChannel: enumOf(["rpc", "run", "tool"]),
  ExportFormat: enumOf(["md", "json"]),
  ExportSessionRequest: object({
    format: ref(() => CHECKS.ExportFormat),
    sessionId: allOf([text(), minLength(1)]),
  }, ["sessionId"]),
  ExportSessionResponse: object({
    artifact: ref(() => CHECKS.SessionArtifact),
    format: ref(() => CHECKS.ExportFormat),
    markdown: text(),
  }, ["format"]),
  FeatureCapability: object({
    enabled: flag(),
    stability: ref(() => CHECKS.Stability),
  }, ["enabled", "stability"]),
  FeaturePreference: object({
    enabled: flag(),
  }, ["enabled"]),
  FeedbackRating: enumOf(["positive", "negative"]),
  FeedbackRequest: object({
    itemId: text(),
    rating: ref(() => CHECKS.FeedbackRating),
    runId: text(),
    sessionId: text(),
    text: text(),
  }, []),
  FieldError: object({
    detail: text(),
    field: text(),
  }, ["detail", "field"]),
  FileContent: object({
    content: text(),
    encoding: text(),
    endLine: integer(),
    path: text(),
    startLine: integer(),
    totalLines: integer(),
    truncated: flag(),
  }, ["content", "encoding", "path", "totalLines"]),
  FileDiff: object({
    added: integer(),
    binary: flag(),
    path: text(),
    previousPath: text(),
    removed: integer(),
    rows: array(ref(() => CHECKS.DiffRow)),
    status: ref(() => CHECKS.FileStatus),
  }, ["path", "rows", "status"]),
  FileEdit: object({
    diff: array(ref(() => CHECKS.DiffRow)),
    path: text(),
    status: ref(() => CHECKS.FileStatus),
  }, ["path", "status"]),
  FileEntry: object({
    modifiedAt: text(),
    name: text(),
    path: text(),
    sizeBytes: integer(),
    type: ref(() => CHECKS.FileEntryType),
  }, ["modifiedAt", "name", "path", "type"]),
  FileEntryType: enumOf(["file", "dir", "symlink"]),
  FileHead: object({
    lines: array(ref(() => CHECKS.FileLine)),
    path: text(),
  }, ["lines", "path"]),
  FileLine: object({
    lineNumber: integer(),
    text: text(),
  }, ["lineNumber", "text"]),
  FileStatus: enumOf(["added", "modified", "deleted", "renamed", "untracked"]),
  ForgetApprovalRuleRequest: object({
    id: text(),
  }, ["id"]),
  ForkSessionRequest: object({
    fromRunId: text(),
    sessionId: allOf([text(), minLength(1)]),
    title: text(),
  }, ["sessionId"]),
  GenerationParams: object({
    maxTokens: integer(),
    stop: array(text()),
    temperature: numeric(),
    topP: numeric(),
  }, []),
  GetDiffRequest: object({
    cwd: text(),
    format: ref(() => CHECKS.DiffFormat),
    limit: integer(),
    mode: ref(() => CHECKS.DiffMode),
    path: text(),
  }, []),
  GetFileHeadRequest: object({
    cwd: text(),
    lines: integer(),
    path: allOf([text(), minLength(1)]),
  }, ["path"]),
  GetMemoryRequest: object({
    cwd: text(),
    scope: ref(() => CHECKS.MemoryScope),
  }, ["scope"]),
  GetSessionRequest: object({
    sessionId: allOf([text(), minLength(1)]),
  }, ["sessionId"]),
  Goal: object({
    budget: ref(() => CHECKS.GoalBudget),
    createdAt: text(),
    model: text(),
    objective: text(),
    provider: text(),
    reason: text(),
    sessionId: text(),
    status: ref(() => CHECKS.GoalStatus),
    updatedAt: text(),
    used: ref(() => CHECKS.GoalUsage),
  }, ["budget", "createdAt", "objective", "sessionId", "status", "updatedAt", "used"]),
  GoalBudget: object({
    maxCostUsd: numeric(),
    maxSteps: integer(),
    maxTurns: integer(),
  }, []),
  GoalRequest: object({
    sessionId: allOf([text(), minLength(1)]),
  }, ["sessionId"]),
  GoalStatus: enumOf(["active", "paused", "blocked"]),
  GoalUsage: object({
    costUsd: numeric(),
    steps: integer(),
    turns: integer(),
  }, ["costUsd", "steps", "turns"]),
  GrepMatch: object({
    lineNumber: integer(),
    path: text(),
    text: text(),
  }, ["lineNumber", "path", "text"]),
  GrepRequest: object({
    cwd: text(),
    limit: integer(),
    path: text(),
    query: allOf([text(), minLength(1)]),
  }, ["query"]),
  GrepResult: object({
    matches: array(ref(() => CHECKS.GrepMatch)),
    total: integer(),
  }, ["matches", "total"]),
  HookEvent: enumOf(["PreToolUse", "PostToolUse", "UserPromptSubmit", "SessionStart", "SubagentStart", "SubagentStop", "PreCompact", "Stop", "Notification"]),
  HookInfo: object({
    active: flag(),
    command: text(),
    event: ref(() => CHECKS.HookEvent),
    inject: text(),
    matcher: text(),
    scope: ref(() => CHECKS.HookScope),
    source: text(),
    timeoutMs: integer(),
  }, ["active", "event", "scope", "source"]),
  HookScope: enumOf(["global", "project"]),
  HooksListResult: object({
    hooks: array(ref(() => CHECKS.HookInfo)),
    projectRoot: text(),
    projectTrusted: flag(),
  }, ["hooks", "projectTrusted"]),
  ImportSessionRequest: allOf([
    object({
      artifact: ref(() => CHECKS.SessionArtifact),
    }, ["artifact"]),
    fields({
      artifact: fields({
        session: fields({
          id: minLength(1),
        }, []),
      }, []),
    }, []),
  ]),
  ImportSessionResponse: object({
    session: ref(() => CHECKS.Session),
  }, ["session"]),
  Interrupt: allOf([
    object({
      itemId: text(),
      payload: ref(() => CHECKS.InterruptPayload),
      type: ref(() => CHECKS.InterruptType),
    }, []),
    oneOf([
      fields({
        payload: fields({
          question: absent(),
        }, ["tool"]),
        type: literal("approval"),
      }, ["itemId", "payload", "type"]),
      fields({
        payload: fields({
          reason: absent(),
          rememberable: absent(),
          risk: absent(),
          tool: absent(),
        }, ["question"]),
        type: literal("question"),
      }, ["itemId", "payload", "type"]),
      fields({
        payload: fields({
          question: absent(),
          reason: absent(),
          rememberable: absent(),
          risk: absent(),
        }, ["tool"]),
        type: literal("toolResult"),
      }, ["itemId", "payload", "type"]),
    ]),
  ]),
  InterruptPayload: object({
    question: ref(() => CHECKS.Question),
    reason: text(),
    rememberable: flag(),
    risk: ref(() => CHECKS.ApprovalRisk),
    tool: ref(() => CHECKS.ToolInvocation),
  }, []),
  InterruptResponse: object({
    itemId: text(),
    response: ref(() => CHECKS.InterruptResponseValue),
  }, ["itemId", "response"]),
  InterruptResponseType: enumOf(["approval", "answer", "toolResult"]),
  InterruptResponseValue: allOf([
    object({
      answers: record(array(text())),
      decision: ref(() => CHECKS.ApprovalDecision),
      editedArgs: record(anything()),
      error: ref(() => CHECKS.ProblemData),
      reason: text(),
      remember: ref(() => CHECKS.RememberScope),
      result: anything(),
      type: ref(() => CHECKS.InterruptResponseType),
    }, []),
    oneOf([
      fields({
        answers: absent(),
        error: absent(),
        result: absent(),
        type: literal("approval"),
      }, ["decision", "type"]),
      fields({
        decision: absent(),
        editedArgs: absent(),
        error: absent(),
        reason: absent(),
        remember: absent(),
        result: absent(),
        type: literal("answer"),
      }, ["answers", "type"]),
      fields({
        answers: absent(),
        decision: absent(),
        editedArgs: absent(),
        reason: absent(),
        remember: absent(),
        type: literal("toolResult"),
      }, ["type"]),
    ]),
  ]),
  InterruptType: enumOf(["approval", "question", "toolResult"]),
  InvokeToolRequest: object({
    arguments: record(anything()),
    cwd: text(),
    name: allOf([text(), minLength(1)]),
  }, ["arguments", "name"]),
  Item: allOf([
    object({
      content: array(ref(() => CHECKS.ContentBlock)),
      createdAt: text(),
      droppedMessages: integer(),
      error: ref(() => CHECKS.ProblemData),
      id: text(),
      question: ref(() => CHECKS.Question),
      redacted: flag(),
      runId: text(),
      safetyClass: ref(() => CHECKS.SafetyClass),
      status: ref(() => CHECKS.ItemStatus),
      steps: array(ref(() => CHECKS.PlanStep)),
      summary: text(),
      text: text(),
      tool: ref(() => CHECKS.ToolInvocation),
      type: ref(() => CHECKS.ItemType),
    }, []),
    oneOf([
      fields({
        droppedMessages: absent(),
        error: absent(),
        question: absent(),
        redacted: absent(),
        safetyClass: absent(),
        steps: absent(),
        summary: absent(),
        text: absent(),
        tool: absent(),
        type: literal("userMessage"),
      }, ["createdAt", "id", "runId", "status", "type"]),
      fields({
        droppedMessages: absent(),
        error: absent(),
        question: absent(),
        redacted: absent(),
        safetyClass: absent(),
        steps: absent(),
        summary: absent(),
        text: absent(),
        tool: absent(),
        type: literal("agentMessage"),
      }, ["createdAt", "id", "runId", "status", "type"]),
      fields({
        content: absent(),
        droppedMessages: absent(),
        error: absent(),
        question: absent(),
        safetyClass: absent(),
        steps: absent(),
        summary: absent(),
        tool: absent(),
        type: literal("reasoning"),
      }, ["createdAt", "id", "runId", "status", "type"]),
      fields({
        content: absent(),
        droppedMessages: absent(),
        error: absent(),
        question: absent(),
        redacted: absent(),
        safetyClass: absent(),
        summary: absent(),
        text: absent(),
        tool: absent(),
        type: literal("plan"),
      }, ["createdAt", "id", "runId", "status", "type"]),
      fields({
        content: absent(),
        droppedMessages: absent(),
        error: absent(),
        redacted: absent(),
        safetyClass: absent(),
        steps: absent(),
        summary: absent(),
        text: absent(),
        tool: absent(),
        type: literal("question"),
      }, ["createdAt", "id", "runId", "status", "type"]),
      fields({
        content: absent(),
        droppedMessages: absent(),
        question: absent(),
        redacted: absent(),
        steps: absent(),
        summary: absent(),
        text: absent(),
        type: literal("toolCall"),
      }, ["createdAt", "id", "runId", "status", "type"]),
      fields({
        content: absent(),
        error: absent(),
        question: absent(),
        redacted: absent(),
        safetyClass: absent(),
        steps: absent(),
        text: absent(),
        tool: absent(),
        type: literal("compaction"),
      }, ["createdAt", "id", "runId", "status", "type"]),
    ]),
  ]),
  ItemDelta: allOf([
    object({
      argumentsTextDelta: text(),
      index: integer(),
      steps: array(ref(() => CHECKS.PlanStep)),
      text: text(),
      type: ref(() => CHECKS.ItemDeltaType),
    }, []),
    oneOf([
      fields({
        argumentsTextDelta: absent(),
        steps: absent(),
        type: literal("content"),
      }, ["text", "type"]),
      fields({
        argumentsTextDelta: absent(),
        index: absent(),
        steps: absent(),
        type: literal("reasoning"),
      }, ["text", "type"]),
      fields({
        index: absent(),
        steps: absent(),
        text: absent(),
        type: literal("toolArguments"),
      }, ["argumentsTextDelta", "type"]),
      fields({
        argumentsTextDelta: absent(),
        index: absent(),
        steps: absent(),
        type: literal("toolOutput"),
      }, ["text", "type"]),
      fields({
        argumentsTextDelta: absent(),
        index: absent(),
        text: absent(),
        type: literal("plan"),
      }, ["steps", "type"]),
    ]),
  ]),
  ItemDeltaType: enumOf(["content", "reasoning", "toolArguments", "toolOutput", "plan"]),
  ItemStatus: enumOf(["running", "completed", "incomplete"]),
  ItemType: enumOf(["userMessage", "agentMessage", "reasoning", "plan", "question", "toolCall", "compaction"]),
  ListApprovalRulesRequest: object({
    sessionId: text(),
  }, ["sessionId"]),
  ListApprovalRulesResult: object({
    rules: array(ref(() => CHECKS.ApprovalRule)),
  }, ["rules"]),
  ListFilesRequest: object({
    cursor: text(),
    cwd: text(),
    glob: text(),
    includeIgnored: flag(),
    limit: integer(),
    path: text(),
    recursive: flag(),
  }, []),
  ListHooksRequest: object({
    cwd: text(),
  }, []),
  ListItemsRequest: object({
    cursor: text(),
    limit: integer(),
    sessionId: allOf([text(), minLength(1)]),
  }, ["sessionId"]),
  ListItemsResponse: object({
    data: array(ref(() => CHECKS.Item)),
    nextCursor: text(),
    runs: array(ref(() => CHECKS.RunRef)),
  }, ["data", "runs"]),
  ListModelsRequest: object({
    cursor: text(),
    limit: integer(),
    provider: text(),
  }, []),
  ListOpenInterruptsRequest: object({
    cursor: text(),
    limit: integer(),
    sessionId: text(),
  }, []),
  ListRunsRequest: object({
    cursor: text(),
    limit: integer(),
    sessionId: text(),
  }, []),
  MCPListToolsRequest: object({
    cursor: text(),
    limit: integer(),
    server: text(),
  }, []),
  MCPServerRequest: object({
    server: allOf([text(), minLength(1)]),
  }, ["server"]),
  ManagedSkill: object({
    description: text(),
    lifecycle: ref(() => CHECKS.SkillLifecycle),
    name: text(),
  }, ["lifecycle", "name"]),
  McpAuthStatus: enumOf(["none", "bearerToken", "oauth", "notLoggedIn"]),
  McpServer: object({
    authStatus: ref(() => CHECKS.McpAuthStatus),
    description: text(),
    error: ref(() => CHECKS.ProblemData),
    name: text(),
    status: ref(() => CHECKS.McpStatus),
    toolCount: integer(),
  }, ["name", "status"]),
  McpServerConfig: object({
    args: array(text()),
    authorizationMasked: text(),
    autoApproveTools: array(text()),
    command: text(),
    description: text(),
    dir: text(),
    disabledTools: array(text()),
    enabled: flag(),
    env: record(text()),
    headers: record(text()),
    name: text(),
    timeoutSeconds: integer(),
    type: ref(() => CHECKS.McpTransport),
    url: text(),
  }, ["enabled", "name", "type"]),
  McpStatus: enumOf(["connecting", "connected", "disconnected", "failed", "needsAuth"]),
  McpTestResult: object({
    error: ref(() => CHECKS.ProblemData),
    ok: flag(),
  }, ["ok"]),
  McpTool: object({
    description: text(),
    inputSchema: record(anything()),
    name: text(),
    server: text(),
  }, ["name", "server"]),
  McpTransport: enumOf(["stdio", "streamableHttp"]),
  MemoryEntry: object({
    content: text(),
    path: text(),
    scope: ref(() => CHECKS.MemoryScope),
    updatedAt: text(),
  }, ["content", "path", "scope"]),
  MemoryScope: enumOf(["cwd", "projectRoot", "home"]),
  Modality: enumOf(["text", "image", "audio", "video", "pdf"]),
  Model: object({
    capabilities: ref(() => CHECKS.ModelCapabilities),
    contextWindow: integer(),
    deprecated: flag(),
    displayName: text(),
    id: text(),
    knowledgeCutoff: text(),
    maxInputTokens: integer(),
    maxOutputTokens: integer(),
    pricing: ref(() => CHECKS.ModelPricing),
    provider: text(),
  }, ["id", "provider"]),
  ModelCapabilities: object({
    inputModalities: array(ref(() => CHECKS.Modality)),
    multimodal: flag(),
    outputModalities: array(ref(() => CHECKS.Modality)),
    reasoning: flag(),
    reasoningDefaultLevel: text(),
    reasoningLevels: array(text()),
    structuredOutput: flag(),
    toolUse: flag(),
  }, []),
  ModelPricing: object({
    cacheReadUsdPerMillionTokens: numeric(),
    cacheWriteUsdPerMillionTokens: numeric(),
    inputUsdPerMillionTokens: numeric(),
    outputUsdPerMillionTokens: numeric(),
  }, []),
  ModelUsage: object({
    cacheReadTokens: integer(),
    cacheWriteTokens: integer(),
    costUsd: numeric(),
    inputTokens: integer(),
    outputTokens: integer(),
    reasoningTokens: integer(),
  }, []),
  OpenInterrupt: allOf([
    object({
      createdAt: text(),
      interrupts: array(ref(() => CHECKS.Interrupt)),
      runId: text(),
      sessionId: text(),
    }, ["createdAt", "interrupts", "runId", "sessionId"]),
    fields({}, ["createdAt", "interrupts", "runId", "sessionId"]),
  ]),
  PageOfAgentDoc: object({
    data: array(ref(() => CHECKS.AgentDoc)),
    nextCursor: text(),
  }, ["data"]),
  PageOfFileEntry: object({
    data: array(ref(() => CHECKS.FileEntry)),
    nextCursor: text(),
  }, ["data"]),
  PageOfManagedSkill: object({
    data: array(ref(() => CHECKS.ManagedSkill)),
    nextCursor: text(),
  }, ["data"]),
  PageOfMcpServer: object({
    data: array(ref(() => CHECKS.McpServer)),
    nextCursor: text(),
  }, ["data"]),
  PageOfMcpServerConfig: object({
    data: array(ref(() => CHECKS.McpServerConfig)),
    nextCursor: text(),
  }, ["data"]),
  PageOfMcpTool: object({
    data: array(ref(() => CHECKS.McpTool)),
    nextCursor: text(),
  }, ["data"]),
  PageOfMemoryEntry: object({
    data: array(ref(() => CHECKS.MemoryEntry)),
    nextCursor: text(),
  }, ["data"]),
  PageOfModel: object({
    data: array(ref(() => CHECKS.Model)),
    nextCursor: text(),
  }, ["data"]),
  PageOfOpenInterrupt: object({
    data: array(ref(() => CHECKS.OpenInterrupt)),
    nextCursor: text(),
  }, ["data"]),
  PageOfProject: object({
    data: array(ref(() => CHECKS.Project)),
    nextCursor: text(),
  }, ["data"]),
  PageOfProvider: object({
    data: array(ref(() => CHECKS.Provider)),
    nextCursor: text(),
  }, ["data"]),
  PageOfRecipe: object({
    data: array(ref(() => CHECKS.Recipe)),
    nextCursor: text(),
  }, ["data"]),
  PageOfRunRef: object({
    data: array(ref(() => CHECKS.RunRef)),
    nextCursor: text(),
  }, ["data"]),
  PageOfSchedule: object({
    data: array(ref(() => CHECKS.Schedule)),
    nextCursor: text(),
  }, ["data"]),
  PageOfSession: object({
    data: array(ref(() => CHECKS.Session)),
    nextCursor: text(),
  }, ["data"]),
  PageOfSkill: object({
    data: array(ref(() => CHECKS.Skill)),
    nextCursor: text(),
  }, ["data"]),
  PageOfSkillDraft: object({
    data: array(ref(() => CHECKS.SkillDraft)),
    nextCursor: text(),
  }, ["data"]),
  PageOfToolSpec: object({
    data: array(ref(() => CHECKS.ToolSpec)),
    nextCursor: text(),
  }, ["data"]),
  PageOfWorkspaceFileChange: object({
    data: array(ref(() => CHECKS.WorkspaceFileChange)),
    nextCursor: text(),
  }, ["data"]),
  PageQuery: object({
    cursor: text(),
    limit: integer(),
  }, []),
  PlanStep: object({
    id: text(),
    status: ref(() => CHECKS.PlanStepStatus),
    title: text(),
  }, ["id", "status", "title"]),
  PlanStepStatus: enumOf(["pending", "running", "completed", "failed"]),
  ProblemData: object({
    channel: ref(() => CHECKS.ErrorChannel),
    detail: text(),
    docUrl: text(),
    errors: array(ref(() => CHECKS.FieldError)),
    retryAfterSeconds: integer(),
    retryable: flag(),
    type: text(),
  }, ["type"]),
  Project: object({
    branch: text(),
    cwd: text(),
    cwdMissing: flag(),
    lastActiveAt: text(),
    name: text(),
    projectRoot: text(),
    sessionCount: integer(),
  }, ["cwd", "name", "sessionCount"]),
  ProtocolRange: object({
    current: text(),
    minSupported: text(),
  }, ["current", "minSupported"]),
  Provider: object({
    apiKeyMasked: text(),
    baseUrl: text(),
    defaultEmbeddingModel: text(),
    embeddingCapable: flag(),
    id: text(),
    keySource: ref(() => CHECKS.ProviderKeySource),
    requiresBaseUrl: flag(),
  }, ["apiKeyMasked", "id"]),
  ProviderKeySource: enumOf(["stored", "env"]),
  ProviderTestResult: object({
    error: ref(() => CHECKS.ProblemData),
    ok: flag(),
  }, ["ok"]),
  Question: object({
    fields: array(ref(() => CHECKS.QuestionField)),
    prompt: text(),
  }, ["fields", "prompt"]),
  QuestionField: allOf([
    object({
      header: text(),
      label: text(),
      multiple: flag(),
      name: text(),
      options: array(ref(() => CHECKS.QuestionOption)),
      required: flag(),
      type: ref(() => CHECKS.QuestionFieldType),
    }, []),
    oneOf([
      fields({
        multiple: absent(),
        options: absent(),
        type: literal("text"),
      }, ["label", "name", "type"]),
      fields({
        type: literal("choice"),
      }, ["label", "name", "options", "type"]),
    ]),
  ]),
  QuestionFieldType: enumOf(["text", "choice"]),
  QuestionOption: object({
    description: text(),
    label: text(),
    preview: text(),
  }, ["label"]),
  ReadFileRequest: object({
    cwd: text(),
    endLine: integer(),
    maxBytes: integer(),
    path: allOf([text(), minLength(1)]),
    startLine: integer(),
  }, ["path"]),
  Recipe: object({
    argumentHint: text(),
    body: text(),
    description: text(),
    name: text(),
    scope: ref(() => CHECKS.RecipeScope),
    source: text(),
  }, ["body", "name", "scope", "source"]),
  RecipeScope: enumOf(["project", "global"]),
  RememberScope: object({
    scope: ref(() => CHECKS.RememberScopeKind),
  }, ["scope"]),
  RememberScopeKind: enumOf(["session", "project", "global"]),
  RemoveMCPServerRequest: object({
    name: allOf([text(), minLength(1)]),
  }, ["name"]),
  RequestMeta: object({
    clientCapabilities: ref(() => CHECKS.ClientCapabilities),
    clientInfo: ref(() => CHECKS.ClientInfo),
    protocolVersion: text(),
  }, []),
  RestoreType: enumOf(["history", "files", "both"]),
  ResumeRunRequest: object({
    responses: array(ref(() => CHECKS.InterruptResponse)),
    runId: allOf([text(), minLength(1)]),
  }, ["responses", "runId"]),
  RollbackSessionRequest: object({
    restoreType: ref(() => CHECKS.RestoreType),
    sessionId: allOf([text(), minLength(1)]),
    toRunId: text(),
  }, ["sessionId"]),
  RollbackSessionResponse: object({
    droppedRuns: array(ref(() => CHECKS.DroppedRun)),
    session: ref(() => CHECKS.Session),
  }, ["droppedRuns", "session"]),
  RunEvent: object({
    event: ref(() => CHECKS.StreamEvent),
    eventId: text(),
    runId: text(),
    segmentId: text(),
    timestamp: text(),
  }, ["event", "eventId", "runId", "segmentId", "timestamp"]),
  RunLimits: object({
    maxBudgetUsd: numeric(),
    maxSteps: integer(),
  }, []),
  RunMetrics: object({
    activeDurationMs: integer(),
    steps: integer(),
    usage: ref(() => CHECKS.Usage),
  }, ["activeDurationMs", "steps"]),
  RunOutcome: allOf([
    object({
      detail: text(),
      error: ref(() => CHECKS.ProblemData),
      type: ref(() => CHECKS.RunOutcomeType),
    }, []),
    oneOf([
      fields({
        detail: absent(),
        error: absent(),
        type: literal("completed"),
      }, ["type"]),
      fields({
        detail: absent(),
        type: literal("error"),
      }, ["error", "type"]),
      fields({
        error: absent(),
        type: literal("maxSteps"),
      }, ["type"]),
      fields({
        error: absent(),
        type: literal("maxBudget"),
      }, ["type"]),
      fields({
        error: absent(),
        type: literal("canceled"),
      }, ["type"]),
    ]),
    ifThen(
      fields({
        type: literal("error"),
      }, ["type"]),
      fields({
        detail: absent(),
      }, ["error"]),
    ),
  ]),
  RunOutcomeType: enumOf(["completed", "error", "maxSteps", "maxBudget", "canceled"]),
  RunProgress: object({
    activity: text(),
    contextTokens: integer(),
    step: integer(),
    usage: ref(() => CHECKS.Usage),
  }, []),
  RunRef: allOf([
    object({
      createdAt: text(),
      finishedAt: text(),
      id: text(),
      limits: ref(() => CHECKS.RunLimits),
      metrics: ref(() => CHECKS.RunMetrics),
      model: text(),
      outcome: ref(() => CHECKS.RunOutcome),
      provider: text(),
      sessionId: text(),
      spawnedByItemId: text(),
      status: ref(() => CHECKS.RunStatus),
    }, ["id", "metrics", "sessionId"]),
    ifThen(
      fields({
        status: literal("finished"),
      }, ["status"]),
      fields({}, ["finishedAt", "outcome"]),
    ),
    ifThen(
      fields({
        status: literal("running"),
      }, ["status"]),
      fields({
        finishedAt: absent(),
        outcome: absent(),
      }, []),
    ),
    ifThen(
      fields({
        status: literal("waiting"),
      }, ["status"]),
      fields({
        finishedAt: absent(),
        outcome: absent(),
      }, []),
    ),
  ]),
  RunScheduleNowRequest: object({
    id: allOf([text(), minLength(1)]),
  }, ["id"]),
  RunScheduleNowResponse: object({
    runId: text(),
    sessionId: text(),
  }, ["runId", "sessionId"]),
  RunStatus: enumOf(["running", "waiting", "finished"]),
  RuntimeLimits: object({
    maxConcurrentRuns: integer(),
  }, []),
  SafetyClass: enumOf(["safe", "write", "exec", "network"]),
  Schedule: object({
    createdAt: text(),
    cron: text(),
    cwd: text(),
    enabled: flag(),
    id: text(),
    lastRunAt: text(),
    model: text(),
    nextRunAt: text(),
    prompt: text(),
    provider: text(),
    revision: allOf([integer(), minimum(0)]),
    title: text(),
  }, ["createdAt", "cron", "enabled", "id", "prompt", "revision", "title"]),
  SearchHit: object({
    lineNumber: integer(),
    path: text(),
    snippet: text(),
  }, ["path"]),
  SegmentOutcome: allOf([
    object({
      detail: text(),
      error: ref(() => CHECKS.ProblemData),
      interrupts: array(ref(() => CHECKS.Interrupt)),
      type: ref(() => CHECKS.SegmentOutcomeType),
    }, []),
    oneOf([
      fields({
        detail: absent(),
        error: absent(),
        type: literal("interrupt"),
      }, ["interrupts", "type"]),
      fields({
        detail: absent(),
        error: absent(),
        interrupts: absent(),
        type: literal("suspended"),
      }, ["type"]),
      fields({
        detail: absent(),
        error: absent(),
        interrupts: absent(),
        type: literal("completed"),
      }, ["type"]),
      fields({
        detail: absent(),
        interrupts: absent(),
        type: literal("error"),
      }, ["error", "type"]),
      fields({
        error: absent(),
        interrupts: absent(),
        type: literal("maxSteps"),
      }, ["type"]),
      fields({
        error: absent(),
        interrupts: absent(),
        type: literal("maxBudget"),
      }, ["type"]),
      fields({
        error: absent(),
        interrupts: absent(),
        type: literal("canceled"),
      }, ["type"]),
    ]),
    ifThen(
      fields({
        type: literal("error"),
      }, ["type"]),
      fields({
        detail: absent(),
      }, ["error"]),
    ),
    ifThen(
      fields({
        type: literal("interrupt"),
      }, ["type"]),
      fields({
        detail: absent(),
        error: absent(),
      }, ["interrupts"]),
    ),
    ifThen(
      fields({
        type: literal("suspended"),
      }, ["type"]),
      fields({
        detail: absent(),
        error: absent(),
        interrupts: absent(),
      }, []),
    ),
  ]),
  SegmentOutcomeType: enumOf(["interrupt", "suspended", "completed", "error", "maxSteps", "maxBudget", "canceled"]),
  ServerCapabilities: object({
    events: array(ref(() => CHECKS.StreamEventType)),
    features: record(ref(() => CHECKS.FeatureCapability)),
    limits: ref(() => CHECKS.RuntimeLimits),
    streamingMethods: array(text()),
  }, ["events", "features", "limits", "streamingMethods"]),
  ServerInfo: object({
    cwd: text(),
    home: text(),
    name: text(),
    version: text(),
  }, ["cwd", "home", "name", "version"]),
  Session: object({
    createdAt: text(),
    cwd: text(),
    cwdMissing: flag(),
    favorite: flag(),
    id: text(),
    model: text(),
    projectRoot: text(),
    revision: allOf([integer(), minimum(0)]),
    status: ref(() => CHECKS.SessionStatus),
    title: text(),
    updatedAt: text(),
  }, ["createdAt", "cwd", "id", "model", "revision", "status", "title", "updatedAt"]),
  SessionArtifact: object({
    items: array(ref(() => CHECKS.ArtifactItem)),
    messages: array(anything()),
    runs: array(ref(() => CHECKS.ArtifactRun)),
    session: ref(() => CHECKS.ArtifactSession),
    toolResults: array(ref(() => CHECKS.ArtifactToolResult)),
    version: integer(),
  }, ["items", "messages", "runs", "session", "toolResults", "version"]),
  SessionStatus: enumOf(["running", "waiting", "idle"]),
  SessionUsageRequest: object({
    sessionId: allOf([text(), minLength(1)]),
  }, ["sessionId"]),
  SetApprovalModeRequest: object({
    mode: ref(() => CHECKS.ApprovalMode),
  }, ["mode"]),
  SetHookTrustRequest: object({
    projectRoot: allOf([text(), minLength(1)]),
    trusted: flag(),
  }, ["projectRoot", "trusted"]),
  SetMCPEnabledRequest: object({
    enabled: flag(),
    name: allOf([text(), minLength(1)]),
  }, ["enabled", "name"]),
  Skill: object({
    description: text(),
    name: text(),
    source: ref(() => CHECKS.SkillSource),
  }, ["name"]),
  SkillDraft: object({
    createdBy: text(),
    description: text(),
    name: text(),
    revision: text(),
    sourceSession: text(),
  }, ["name", "revision"]),
  SkillDraftRef: object({
    name: text(),
    revision: text(),
  }, ["name", "revision"]),
  SkillLifecycle: enumOf(["active", "archived"]),
  SkillNameRequest: object({
    name: allOf([text(), minLength(1)]),
  }, ["name"]),
  SkillSource: enumOf(["project", "global"]),
  Stability: enumOf(["stable", "experimental"]),
  StartGoalRequest: object({
    budget: ref(() => CHECKS.GoalBudget),
    model: text(),
    objective: allOf([text(), minLength(1)]),
    provider: text(),
    sessionId: allOf([text(), minLength(1)]),
  }, ["objective", "sessionId"]),
  StartRunRequest: object({
    input: array(ref(() => CHECKS.ContentBlock)),
    maxBudgetUsd: numeric(),
    maxSteps: integer(),
    model: text(),
    params: ref(() => CHECKS.GenerationParams),
    provider: text(),
    sessionId: text(),
  }, ["input", "sessionId"]),
  StartRunResponse: object({
    runId: text(),
    segmentId: text(),
    userItemId: text(),
  }, ["runId", "segmentId"]),
  SteerRunRequest: object({
    message: allOf([text(), minLength(1)]),
    runId: allOf([text(), minLength(1)]),
  }, ["message", "runId"]),
  StreamEvent: allOf([
    object({
      delta: ref(() => CHECKS.ItemDelta),
      durable: flag(),
      item: ref(() => CHECKS.Item),
      itemId: text(),
      metrics: ref(() => CHECKS.RunMetrics),
      name: text(),
      outcome: ref(() => CHECKS.SegmentOutcome),
      payload: anything(),
      progress: ref(() => CHECKS.RunProgress),
      run: ref(() => CHECKS.RunRef),
      state: record(anything()),
      type: ref(() => CHECKS.StreamEventType),
    }, []),
    oneOf([
      fields({
        delta: absent(),
        durable: absent(),
        item: absent(),
        itemId: absent(),
        metrics: absent(),
        name: absent(),
        outcome: absent(),
        payload: absent(),
        progress: absent(),
        state: absent(),
        type: literal("segment.started"),
      }, ["run", "type"]),
      fields({
        delta: absent(),
        durable: absent(),
        item: absent(),
        itemId: absent(),
        metrics: absent(),
        name: absent(),
        outcome: absent(),
        payload: absent(),
        run: absent(),
        state: absent(),
        type: literal("segment.progress"),
      }, ["progress", "type"]),
      fields({
        delta: absent(),
        durable: absent(),
        item: absent(),
        itemId: absent(),
        name: absent(),
        payload: absent(),
        progress: absent(),
        run: absent(),
        state: absent(),
        type: literal("segment.finished"),
      }, ["metrics", "outcome", "type"]),
      fields({
        delta: absent(),
        durable: absent(),
        itemId: absent(),
        metrics: absent(),
        name: absent(),
        outcome: absent(),
        payload: absent(),
        progress: absent(),
        run: absent(),
        state: absent(),
        type: literal("item.started"),
      }, ["item", "type"]),
      fields({
        durable: absent(),
        item: absent(),
        metrics: absent(),
        name: absent(),
        outcome: absent(),
        payload: absent(),
        progress: absent(),
        run: absent(),
        state: absent(),
        type: literal("item.delta"),
      }, ["delta", "itemId", "type"]),
      fields({
        delta: absent(),
        durable: absent(),
        itemId: absent(),
        metrics: absent(),
        name: absent(),
        outcome: absent(),
        payload: absent(),
        progress: absent(),
        run: absent(),
        state: absent(),
        type: literal("item.completed"),
      }, ["item", "type"]),
      fields({
        delta: absent(),
        durable: absent(),
        item: absent(),
        itemId: absent(),
        metrics: absent(),
        name: absent(),
        outcome: absent(),
        payload: absent(),
        progress: absent(),
        run: absent(),
        type: literal("state.snapshot"),
      }, ["state", "type"]),
      fields({
        delta: absent(),
        item: absent(),
        itemId: absent(),
        metrics: absent(),
        outcome: absent(),
        progress: absent(),
        run: absent(),
        state: absent(),
        type: literal("custom"),
      }, ["name", "type"]),
    ]),
  ]),
  StreamEventType: enumOf(["segment.started", "segment.progress", "segment.finished", "item.started", "item.delta", "item.completed", "state.snapshot", "custom"]),
  SubscribeRunRequest: object({
    runId: allOf([text(), minLength(1)]),
  }, ["runId"]),
  TestProviderRequest: object({
    provider: allOf([text(), minLength(1)]),
  }, ["provider"]),
  TodoSnapshot: object({
    blockedReason: text(),
    id: text(),
    nextAction: text(),
    status: ref(() => CHECKS.TodoStatus),
    text: text(),
  }, ["id", "status", "text"]),
  TodoStatus: enumOf(["pending", "in_progress", "completed"]),
  ToolInvocation: object({
    arguments: record(anything()),
    name: text(),
    result: anything(),
  }, ["arguments", "name"]),
  ToolSpec: object({
    description: text(),
    name: text(),
    parameters: record(anything()),
    safetyClass: ref(() => CHECKS.SafetyClass),
  }, ["name"]),
  UpdateMemoryRequest: object({
    content: text(),
    cwd: text(),
    scope: ref(() => CHECKS.MemoryScope),
  }, ["content", "scope"]),
  UpdateScheduleRequest: object({
    cron: text(),
    cwd: text(),
    enabled: flag(),
    expectedRevision: allOf([integer(), minimum(1)]),
    id: allOf([text(), minLength(1)]),
    model: text(),
    prompt: text(),
    provider: text(),
    title: text(),
  }, ["expectedRevision", "id"]),
  UpdateSessionRequest: object({
    cwd: text(),
    expectedRevision: allOf([integer(), minimum(1)]),
    favorite: flag(),
    model: text(),
    sessionId: allOf([text(), minLength(1)]),
    title: text(),
  }, ["expectedRevision", "sessionId"]),
  Usage: object({
    byModel: record(ref(() => CHECKS.ModelUsage)),
    cacheReadTokens: integer(),
    cacheWriteTokens: integer(),
    costUsd: numeric(),
    inputTokens: integer(),
    outputTokens: integer(),
    reasoningTokens: integer(),
  }, []),
  UsageBucket: object({
    cacheReadTokens: integer(),
    cacheWriteTokens: integer(),
    costUsd: numeric(),
    inputTokens: integer(),
    key: text(),
    outputTokens: integer(),
    reasoningTokens: integer(),
    runs: integer(),
  }, ["key"]),
  UsageSummary: object({
    byDay: array(ref(() => CHECKS.UsageBucket)),
    byModel: array(ref(() => CHECKS.UsageBucket)),
    byProvider: array(ref(() => CHECKS.UsageBucket)),
    runs: integer(),
    sessions: integer(),
    total: ref(() => CHECKS.ModelUsage),
  }, ["total"]),
  UsageSummaryRequest: object({
    sinceDays: integer(),
  }, []),
  UtilityRole: object({
    model: text(),
    provider: text(),
  }, []),
  WatchSpec: object({
    cwd: text(),
    path: text(),
    watchId: text(),
  }, ["watchId"]),
  WebSearchResult: object({
    faviconUrl: text(),
    snippet: text(),
    title: text(),
    url: text(),
  }, ["url"]),
  WorkspaceEvent: allOf([
    object({
      cwd: text(),
      error: ref(() => CHECKS.ProblemData),
      paths: array(text()),
      scheduleId: text(),
      sequence: allOf([integer(), minimum(0)]),
      server: text(),
      status: ref(() => CHECKS.McpStatus),
      toolCount: integer(),
      type: ref(() => CHECKS.WorkspaceEventType),
      watchId: text(),
    }, []),
    oneOf([
      fields({
        error: absent(),
        scheduleId: absent(),
        server: absent(),
        status: absent(),
        toolCount: absent(),
        type: literal("files.changed"),
      }, ["paths", "sequence", "type"]),
      fields({
        cwd: absent(),
        error: absent(),
        paths: absent(),
        scheduleId: absent(),
        server: absent(),
        status: absent(),
        toolCount: absent(),
        type: literal("skills.changed"),
        watchId: absent(),
      }, ["sequence", "type"]),
      fields({
        cwd: absent(),
        paths: absent(),
        scheduleId: absent(),
        type: literal("mcp.serverChanged"),
        watchId: absent(),
      }, ["sequence", "server", "type"]),
      fields({
        cwd: absent(),
        error: absent(),
        paths: absent(),
        server: absent(),
        status: absent(),
        toolCount: absent(),
        type: literal("schedules.fired"),
        watchId: absent(),
      }, ["scheduleId", "sequence", "type"]),
      fields({
        cwd: absent(),
        error: absent(),
        paths: absent(),
        scheduleId: absent(),
        server: absent(),
        status: absent(),
        toolCount: absent(),
        type: literal("resync"),
        watchId: absent(),
      }, ["sequence", "type"]),
    ]),
  ]),
  WorkspaceEventType: enumOf(["files.changed", "skills.changed", "mcp.serverChanged", "schedules.fired", "resync"]),
  WorkspaceFileChange: object({
    added: integer(),
    binary: flag(),
    path: text(),
    previousPath: text(),
    removed: integer(),
    status: ref(() => CHECKS.FileStatus),
  }, ["path", "status"]),
  WorkspaceListQuery: object({
    cursor: text(),
    cwd: text(),
    limit: integer(),
  }, []),
  WorkspaceSubscribeRequest: object({
    watches: array(ref(() => CHECKS.WatchSpec)),
  }, []),
  WorkspaceSubscribeResponse: object({}, []),
};

// The shape each state.snapshot key carries.
const STATE_PAYLOADS: Readonly<Record<string, WireCheck>> = {
  todos: array(ref(() => CHECKS.TodoSnapshot)),
};

/**
 * validateStatePayload checks one state.snapshot key's value against the shape
 * declared for it.
 *
 * A key this build does not know is not a violation: the envelope is open by design,
 * so a newer runtime may carry one, and refusing it would be a client deciding what
 * the protocol may grow.
 */
export function validateStatePayload(key: string, value: unknown): WireViolation[] {
  const check = STATE_PAYLOADS[key];
  if (!check) return [];
  const out: WireViolation[] = [];
  check(value, key, out);
  return out;
}

/**
 * validateWire reports every way a value fails the published shape, and an empty
 * list when it satisfies it.
 *
 * Paths are rooted at the type's own name, so a report reads
 * `RunEvent.event.outcome.type`.
 */
export function validateWire(type: WireTypeName, value: unknown): WireViolation[] {
  const out: WireViolation[] = [];
  CHECKS[type](value, type, out);
  return out;
}
