// Code generated by cmd/contractgen. DO NOT EDIT.
//
// The method surface of the Lyra Runtime Protocol: which methods exist, what each
// one carries, and what has to be negotiated before one will run.
//
// The SDK in methods.ts composes these with transport concerns. Every protocol
// fact in this file is read from the Contract Registry.

import type {
  AgentMemoryAddRequest,
  AgentMemoryItem,
  AgentMemoryItemRequest,
  AgentMemoryList,
  AgentMemoryListRequest,
  AgentMemoryReviewRequest,
  AgentMemoryUpdateRequest,
  ApprovalModeResult,
  CancelRunRequest,
  CancelRunResponse,
  CodebaseReindexRequest,
  CodebaseReindexResponse,
  CodebaseSearchRequest,
  CodebaseSearchResult,
  CodebaseStatus,
  CodebaseStatusRequest,
  CreateMCPAuthorizationAttemptRequest,
  CreateScheduleRequest,
  CreateSessionRequest,
  DeleteScheduleRequest,
  DeleteSessionRequest,
  Diff,
  DiscoverResponse,
  EmbeddingRole,
  ExportSessionRequest,
  ExportSessionResponse,
  FeedbackRequest,
  FileContent,
  FileHead,
  ForgetApprovalRuleRequest,
  ForkSessionRequest,
  GetDiffRequest,
  GetFileHeadRequest,
  GetMemoryRequest,
  GetRunRequest,
  GetSessionRequest,
  GetTodosRequest,
  Goal,
  GoalRequest,
  GrepRequest,
  GrepResult,
  HooksListResult,
  ImportSessionRequest,
  ImportSessionResponse,
  InvokeToolRequest,
  ListApprovalRulesRequest,
  ListApprovalRulesResult,
  ListFilesRequest,
  ListHooksRequest,
  ListInterruptsRequest,
  ListItemsRequest,
  ListItemsResponse,
  ListModelsRequest,
  ListRunsRequest,
  MCPAuthorizationAttemptRequest,
  MCPListToolsRequest,
  MCPServerCandidate,
  MCPServerRequest,
  McpAuthorizationAttempt,
  McpServer,
  McpTestResult,
  MemoryEntry,
  PageOfAgentDoc,
  PageOfFileEntry,
  PageOfManagedSkill,
  PageOfMcpServer,
  PageOfMcpTool,
  PageOfMemoryEntry,
  PageOfModel,
  PageOfPendingInterruptSet,
  PageOfProvider,
  PageOfRecipe,
  PageOfRunRef,
  PageOfSchedule,
  PageOfSession,
  PageOfSkill,
  PageOfSkillDraft,
  PageOfToolSpec,
  PageOfWorkspaceFileChange,
  PageOfWorkspaceSummary,
  PageQuery,
  Provider,
  ProviderTestResult,
  ReadFileRequest,
  ResolveWorkspaceRequest,
  ResumeRunRequest,
  ResumeRunResponse,
  RollbackSessionRequest,
  RollbackSessionResponse,
  RunRef,
  RunScheduleNowRequest,
  RunScheduleNowResponse,
  RuntimeSubscribeRequest,
  RuntimeSubscribeResponse,
  Schedule,
  Session,
  SessionUsageRequest,
  SetApprovalModeRequest,
  SetHookTrustRequest,
  SkillDraftRef,
  SkillNameRequest,
  StartGoalRequest,
  StartRunRequest,
  StartRunResponse,
  StateSnapshot,
  SteerRunRequest,
  SubscribeRunRequest,
  SubscribeRunResponse,
  TestProviderRequest,
  UpdateMCPServerRequest,
  UpdateMemoryRequest,
  UpdateProviderRequest,
  UpdateScheduleRequest,
  UpdateSessionRequest,
  Usage,
  UsageSummary,
  UsageSummaryRequest,
  UtilityRole,
  WorkspaceInfo,
  WorkspaceListQuery,
} from "./wire.generated";

// Every capability key discovery may advertise (API.md §9). Private: it exists to
// derive the union, and a published array with no reader would be a second table.
const FEATURES = [
  "reasoning",
  "multimodal",
  "compaction",
  "todos",
  "goals",
  "agentMemory",
  "memory",
  "skills",
  "mcp",
  "schedules",
  "codebase",
  "git",
  "checkpoints",
  "fileWatch",
  "lsp",
  "sessionExport",
  "relocate",
  "subagents",
  "clientTools",
] as const;

/** One capability key discovery may advertise. */
export type WireFeature = (typeof FEATURES)[number];

// Every method the runtime routes, in registration order.
const METHOD_NAMES = [
  "runtime.discover",
  "sessions.list",
  "sessions.get",
  "sessions.create",
  "sessions.update",
  "sessions.delete",
  "sessions.fork",
  "sessions.rollback",
  "sessions.export",
  "sessions.import",
  "runs.start",
  "runs.resume",
  "runs.subscribe",
  "runs.cancel",
  "runs.steer",
  "runs.get",
  "runs.list",
  "interrupts.list",
  "todos.get",
  "items.list",
  "workspaces.resolve",
  "workspaces.list",
  "workspace.changes.list",
  "workspace.diff.get",
  "workspace.files.head",
  "workspace.files.search",
  "workspace.files.list",
  "workspace.files.read",
  "runtime.subscribe",
  "skills.discovered.list",
  "skills.library.list",
  "skills.library.archive",
  "skills.library.restore",
  "skills.drafts.list",
  "skills.drafts.promote",
  "skills.drafts.reject",
  "recipes.list",
  "agentDocs.list",
  "mcp.servers.list",
  "mcp.servers.create",
  "mcp.servers.update",
  "mcp.servers.delete",
  "mcp.servers.test",
  "mcp.tools.list",
  "mcp.servers.reconnect",
  "mcp.authorizationAttempts.create",
  "mcp.authorizationAttempts.get",
  "hooks.list",
  "hooks.setTrust",
  "approval.getMode",
  "approval.setMode",
  "approval.listRules",
  "approval.forgetRule",
  "schedules.list",
  "schedules.create",
  "schedules.update",
  "schedules.delete",
  "schedules.runNow",
  "goals.start",
  "goals.get",
  "goals.stop",
  "goals.resume",
  "codebase.search",
  "codebase.status",
  "codebase.reindex",
  "providers.list",
  "providers.update",
  "providers.test",
  "models.list",
  "models.getUtilityRole",
  "models.setUtilityRole",
  "models.getEmbeddingRole",
  "models.setEmbeddingRole",
  "tools.list",
  "tools.invoke",
  "usage.session",
  "usage.summary",
  "memory.list",
  "memory.get",
  "memory.update",
  "agentMemory.list",
  "agentMemory.review",
  "agentMemory.update",
  "agentMemory.delete",
  "agentMemory.add",
  "feedback.create",
] as const;

/** One method the runtime routes. */
export type WireMethodName = (typeof METHOD_NAMES)[number];

// Every method whose HTTP response remains open as an event stream.
export const WIRE_STREAMING_METHOD_NAMES = [
  "runs.start",
  "runs.resume",
  "runs.subscribe",
  "runtime.subscribe",
] as const;

export type WireStreamingMethodName = (typeof WIRE_STREAMING_METHOD_NAMES)[number];

export function isWireStreamingMethodName(
  method: WireMethodName,
): method is WireStreamingMethodName {
  return (WIRE_STREAMING_METHOD_NAMES as readonly string[]).includes(method);
}

// Methods whose validated wire result becomes a value in the ergonomic SDK.
const VALUE_METHOD_NAMES = [
  "runtime.discover",
  "sessions.list",
  "sessions.get",
  "sessions.create",
  "sessions.update",
  "sessions.fork",
  "sessions.rollback",
  "sessions.export",
  "sessions.import",
  "runs.start",
  "runs.resume",
  "runs.subscribe",
  "runs.cancel",
  "runs.get",
  "runs.list",
  "interrupts.list",
  "todos.get",
  "items.list",
  "workspaces.resolve",
  "workspaces.list",
  "workspace.changes.list",
  "workspace.diff.get",
  "workspace.files.head",
  "workspace.files.search",
  "workspace.files.list",
  "workspace.files.read",
  "runtime.subscribe",
  "skills.discovered.list",
  "skills.library.list",
  "skills.drafts.list",
  "recipes.list",
  "agentDocs.list",
  "mcp.servers.list",
  "mcp.servers.create",
  "mcp.servers.update",
  "mcp.servers.test",
  "mcp.tools.list",
  "mcp.authorizationAttempts.create",
  "mcp.authorizationAttempts.get",
  "hooks.list",
  "approval.getMode",
  "approval.setMode",
  "approval.listRules",
  "schedules.list",
  "schedules.create",
  "schedules.update",
  "schedules.runNow",
  "goals.start",
  "goals.get",
  "goals.stop",
  "goals.resume",
  "codebase.search",
  "codebase.status",
  "codebase.reindex",
  "providers.list",
  "providers.update",
  "providers.test",
  "models.list",
  "models.getUtilityRole",
  "models.setUtilityRole",
  "models.getEmbeddingRole",
  "models.setEmbeddingRole",
  "tools.list",
  "tools.invoke",
  "usage.session",
  "usage.summary",
  "memory.list",
  "memory.get",
  "agentMemory.list",
  "agentMemory.update",
  "agentMemory.add",
] as const;

type WireValueMethodName = (typeof VALUE_METHOD_NAMES)[number];

export function wireMethodReturnsValue(
  method: WireMethodName,
): method is WireValueMethodName {
  return (VALUE_METHOD_NAMES as readonly string[]).includes(method);
}

export type WireOperationKind = "query" | "command" | "subscription";
export type WireResponseKind = "unary" | "stream";
export type WireIdempotencyPolicy = "none" | "replayResponse" | "replayRunStream";
export type WirePaginationKind = "none" | "cursor";

export interface WireMethodPolicy {
  operation: WireOperationKind;
  response: WireResponseKind;
  idempotency: WireIdempotencyPolicy;
  pagination: WirePaginationKind;
}

export const WIRE_METHOD_POLICY = {
  "runtime.discover": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "sessions.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "cursor",
  },
  "sessions.get": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "sessions.create": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "sessions.update": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "sessions.delete": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "sessions.fork": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "sessions.rollback": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "sessions.export": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "sessions.import": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "runs.start": {
    operation: "command",
    response: "stream",
    idempotency: "replayRunStream",
    pagination: "none",
  },
  "runs.resume": {
    operation: "command",
    response: "stream",
    idempotency: "replayRunStream",
    pagination: "none",
  },
  "runs.subscribe": {
    operation: "subscription",
    response: "stream",
    idempotency: "none",
    pagination: "none",
  },
  "runs.cancel": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "runs.steer": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "runs.get": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "runs.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "cursor",
  },
  "interrupts.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "cursor",
  },
  "todos.get": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "items.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "cursor",
  },
  "workspaces.resolve": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "workspaces.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "cursor",
  },
  "workspace.changes.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "cursor",
  },
  "workspace.diff.get": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "workspace.files.head": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "workspace.files.search": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "workspace.files.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "cursor",
  },
  "workspace.files.read": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "runtime.subscribe": {
    operation: "subscription",
    response: "stream",
    idempotency: "none",
    pagination: "none",
  },
  "skills.discovered.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "cursor",
  },
  "skills.library.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "cursor",
  },
  "skills.library.archive": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "skills.library.restore": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "skills.drafts.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "cursor",
  },
  "skills.drafts.promote": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "skills.drafts.reject": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "recipes.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "cursor",
  },
  "agentDocs.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "cursor",
  },
  "mcp.servers.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "cursor",
  },
  "mcp.servers.create": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "mcp.servers.update": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "mcp.servers.delete": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "mcp.servers.test": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "mcp.tools.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "cursor",
  },
  "mcp.servers.reconnect": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "mcp.authorizationAttempts.create": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "mcp.authorizationAttempts.get": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "hooks.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "hooks.setTrust": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "approval.getMode": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "approval.setMode": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "approval.listRules": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "approval.forgetRule": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "schedules.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "cursor",
  },
  "schedules.create": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "schedules.update": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "schedules.delete": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "schedules.runNow": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "goals.start": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "goals.get": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "goals.stop": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "goals.resume": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "codebase.search": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "codebase.status": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "codebase.reindex": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "providers.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "cursor",
  },
  "providers.update": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "providers.test": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "models.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "cursor",
  },
  "models.getUtilityRole": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "models.setUtilityRole": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "models.getEmbeddingRole": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "models.setEmbeddingRole": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "tools.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "cursor",
  },
  "tools.invoke": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "usage.session": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "usage.summary": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "memory.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "cursor",
  },
  "memory.get": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "memory.update": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "agentMemory.list": {
    operation: "query",
    response: "unary",
    idempotency: "none",
    pagination: "none",
  },
  "agentMemory.review": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "agentMemory.update": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "agentMemory.delete": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "agentMemory.add": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
  "feedback.create": {
    operation: "command",
    response: "unary",
    idempotency: "replayResponse",
    pagination: "none",
  },
} as const satisfies { readonly [M in WireMethodName]: WireMethodPolicy };

/** True only for calls whose first response the runtime durably replays. */
export type WireMutationMethodName = {
  [M in WireMethodName]: (typeof WIRE_METHOD_POLICY)[M]["operation"] extends "command"
    ? M
    : never;
}[WireMethodName];

export function wireMethodRequiresIdempotency(method: WireMethodName): boolean {
  return WIRE_METHOD_POLICY[method].operation === "command";
}

/** Every cursor-paginated method, derived from the method policy above. */
export type WirePaginatedMethodName = {
  [M in WireMethodName]: (typeof WIRE_METHOD_POLICY)[M]["pagination"] extends "cursor"
    ? M
    : never;
}[WireMethodName];

export function wireMethodIsPaginated(
  method: WireMethodName,
): method is WirePaginatedMethodName {
  return WIRE_METHOD_POLICY[method].pagination === "cursor";
}

/** One condition on the request that decides whether a rule applies. */
export interface WireCapabilityCondition {
  field: string;
  operator: "present" | "equals";
  value?: string;
}

/**
 * What a method needs negotiated. An absent `when` gates the whole method; a
 * condition gates only the requests that match it.
 */
export interface WireCapabilityRule {
  when?: readonly WireCapabilityCondition[];
  requires: readonly WireFeature[];
}

export const WIRE_CAPABILITY_POLICY: {
  readonly [M in WireMethodName]?: readonly WireCapabilityRule[];
} = {
  "sessions.update": [
    { when: [{ field: "workspace", operator: "present" }], requires: ["relocate"] },
  ],
  "sessions.rollback": [
    { when: [{ field: "restoreType", operator: "equals", value: "files" }], requires: ["checkpoints"] },
    { when: [{ field: "restoreType", operator: "equals", value: "both" }], requires: ["checkpoints"] },
  ],
  "sessions.export": [
    { requires: ["sessionExport"] },
  ],
  "sessions.import": [
    { requires: ["sessionExport"] },
  ],
  "runs.list": [
    { when: [{ field: "includeDescendants", operator: "present" }], requires: ["subagents"] },
  ],
  "todos.get": [
    { requires: ["todos"] },
  ],
  "items.list": [
    { when: [{ field: "scope.includeDescendants", operator: "present" }], requires: ["subagents"] },
  ],
  "workspace.changes.list": [
    { requires: ["git"] },
  ],
  "workspace.diff.get": [
    { requires: ["git"] },
  ],
  "runtime.subscribe": [
    { when: [{ field: "watches", operator: "present" }], requires: ["fileWatch"] },
  ],
  "skills.discovered.list": [
    { requires: ["skills"] },
  ],
  "skills.library.list": [
    { requires: ["skills"] },
  ],
  "skills.library.archive": [
    { requires: ["skills"] },
  ],
  "skills.library.restore": [
    { requires: ["skills"] },
  ],
  "skills.drafts.list": [
    { requires: ["skills"] },
  ],
  "skills.drafts.promote": [
    { requires: ["skills"] },
  ],
  "skills.drafts.reject": [
    { requires: ["skills"] },
  ],
  "mcp.servers.list": [
    { requires: ["mcp"] },
  ],
  "mcp.servers.create": [
    { requires: ["mcp"] },
  ],
  "mcp.servers.update": [
    { requires: ["mcp"] },
  ],
  "mcp.servers.delete": [
    { requires: ["mcp"] },
  ],
  "mcp.servers.test": [
    { requires: ["mcp"] },
  ],
  "mcp.tools.list": [
    { requires: ["mcp"] },
  ],
  "mcp.servers.reconnect": [
    { requires: ["mcp"] },
  ],
  "mcp.authorizationAttempts.create": [
    { requires: ["mcp"] },
  ],
  "mcp.authorizationAttempts.get": [
    { requires: ["mcp"] },
  ],
  "schedules.list": [
    { requires: ["schedules"] },
  ],
  "schedules.create": [
    { requires: ["schedules"] },
  ],
  "schedules.update": [
    { requires: ["schedules"] },
  ],
  "schedules.delete": [
    { requires: ["schedules"] },
  ],
  "schedules.runNow": [
    { requires: ["schedules"] },
  ],
  "goals.start": [
    { requires: ["goals"] },
  ],
  "goals.get": [
    { requires: ["goals"] },
  ],
  "goals.stop": [
    { requires: ["goals"] },
  ],
  "goals.resume": [
    { requires: ["goals"] },
  ],
  "codebase.search": [
    { requires: ["codebase"] },
  ],
  "codebase.status": [
    { requires: ["codebase"] },
  ],
  "codebase.reindex": [
    { requires: ["codebase"] },
  ],
  "memory.list": [
    { requires: ["memory"] },
  ],
  "memory.get": [
    { requires: ["memory"] },
  ],
  "memory.update": [
    { requires: ["memory"] },
  ],
  "agentMemory.list": [
    { requires: ["agentMemory"] },
  ],
  "agentMemory.review": [
    { requires: ["agentMemory"] },
  ],
  "agentMemory.update": [
    { requires: ["agentMemory"] },
  ],
  "agentMemory.delete": [
    { requires: ["agentMemory"] },
  ],
  "agentMemory.add": [
    { requires: ["agentMemory"] },
  ],
};

/** The frames each method carries. */
export interface WireShapes {
  "runtime.discover": { params: Record<string, never>; result: DiscoverResponse };
  "sessions.list": { params: PageQuery; result: PageOfSession };
  "sessions.get": { params: GetSessionRequest; result: Session };
  "sessions.create": { params: CreateSessionRequest; result: Session };
  "sessions.update": { params: UpdateSessionRequest; result: Session };
  "sessions.delete": { params: DeleteSessionRequest };
  "sessions.fork": { params: ForkSessionRequest; result: Session };
  "sessions.rollback": { params: RollbackSessionRequest; result: RollbackSessionResponse };
  "sessions.export": { params: ExportSessionRequest; result: ExportSessionResponse };
  "sessions.import": { params: ImportSessionRequest; result: ImportSessionResponse };
  "runs.start": { params: StartRunRequest; result: StartRunResponse };
  "runs.resume": { params: ResumeRunRequest; result: ResumeRunResponse };
  "runs.subscribe": { params: SubscribeRunRequest; result: SubscribeRunResponse };
  "runs.cancel": { params: CancelRunRequest; result: CancelRunResponse };
  "runs.steer": { params: SteerRunRequest };
  "runs.get": { params: GetRunRequest; result: RunRef };
  "runs.list": { params: ListRunsRequest; result: PageOfRunRef };
  "interrupts.list": { params: ListInterruptsRequest; result: PageOfPendingInterruptSet };
  "todos.get": { params: GetTodosRequest; result: StateSnapshot };
  "items.list": { params: ListItemsRequest; result: ListItemsResponse };
  "workspaces.resolve": { params: ResolveWorkspaceRequest; result: WorkspaceInfo };
  "workspaces.list": { params: PageQuery; result: PageOfWorkspaceSummary };
  "workspace.changes.list": { params: WorkspaceListQuery; result: PageOfWorkspaceFileChange };
  "workspace.diff.get": { params: GetDiffRequest; result: Diff };
  "workspace.files.head": { params: GetFileHeadRequest; result: FileHead };
  "workspace.files.search": { params: GrepRequest; result: GrepResult };
  "workspace.files.list": { params: ListFilesRequest; result: PageOfFileEntry };
  "workspace.files.read": { params: ReadFileRequest; result: FileContent };
  "runtime.subscribe": { params: RuntimeSubscribeRequest; result: RuntimeSubscribeResponse };
  "skills.discovered.list": { params: WorkspaceListQuery; result: PageOfSkill };
  "skills.library.list": { params: PageQuery; result: PageOfManagedSkill };
  "skills.library.archive": { params: SkillNameRequest };
  "skills.library.restore": { params: SkillNameRequest };
  "skills.drafts.list": { params: PageQuery; result: PageOfSkillDraft };
  "skills.drafts.promote": { params: SkillDraftRef };
  "skills.drafts.reject": { params: SkillDraftRef };
  "recipes.list": { params: WorkspaceListQuery; result: PageOfRecipe };
  "agentDocs.list": { params: WorkspaceListQuery; result: PageOfAgentDoc };
  "mcp.servers.list": { params: PageQuery; result: PageOfMcpServer };
  "mcp.servers.create": { params: MCPServerCandidate; result: McpServer };
  "mcp.servers.update": { params: UpdateMCPServerRequest; result: McpServer };
  "mcp.servers.delete": { params: MCPServerRequest };
  "mcp.servers.test": { params: MCPServerCandidate; result: McpTestResult };
  "mcp.tools.list": { params: MCPListToolsRequest; result: PageOfMcpTool };
  "mcp.servers.reconnect": { params: MCPServerRequest };
  "mcp.authorizationAttempts.create": { params: CreateMCPAuthorizationAttemptRequest; result: McpAuthorizationAttempt };
  "mcp.authorizationAttempts.get": { params: MCPAuthorizationAttemptRequest; result: McpAuthorizationAttempt };
  "hooks.list": { params: ListHooksRequest; result: HooksListResult };
  "hooks.setTrust": { params: SetHookTrustRequest };
  "approval.getMode": { params: Record<string, never>; result: ApprovalModeResult };
  "approval.setMode": { params: SetApprovalModeRequest; result: ApprovalModeResult };
  "approval.listRules": { params: ListApprovalRulesRequest; result: ListApprovalRulesResult };
  "approval.forgetRule": { params: ForgetApprovalRuleRequest };
  "schedules.list": { params: PageQuery; result: PageOfSchedule };
  "schedules.create": { params: CreateScheduleRequest; result: Schedule };
  "schedules.update": { params: UpdateScheduleRequest; result: Schedule };
  "schedules.delete": { params: DeleteScheduleRequest };
  "schedules.runNow": { params: RunScheduleNowRequest; result: RunScheduleNowResponse };
  "goals.start": { params: StartGoalRequest; result: Goal };
  "goals.get": { params: GoalRequest; result: Goal | null };
  "goals.stop": { params: GoalRequest; result: Goal };
  "goals.resume": { params: GoalRequest; result: Goal };
  "codebase.search": { params: CodebaseSearchRequest; result: CodebaseSearchResult };
  "codebase.status": { params: CodebaseStatusRequest; result: CodebaseStatus };
  "codebase.reindex": { params: CodebaseReindexRequest; result: CodebaseReindexResponse };
  "providers.list": { params: PageQuery; result: PageOfProvider };
  "providers.update": { params: UpdateProviderRequest; result: Provider };
  "providers.test": { params: TestProviderRequest; result: ProviderTestResult };
  "models.list": { params: ListModelsRequest; result: PageOfModel };
  "models.getUtilityRole": { params: Record<string, never>; result: UtilityRole };
  "models.setUtilityRole": { params: UtilityRole; result: UtilityRole };
  "models.getEmbeddingRole": { params: Record<string, never>; result: EmbeddingRole };
  "models.setEmbeddingRole": { params: EmbeddingRole; result: EmbeddingRole };
  "tools.list": { params: PageQuery; result: PageOfToolSpec };
  "tools.invoke": { params: InvokeToolRequest; result: unknown };
  "usage.session": { params: SessionUsageRequest; result: Usage };
  "usage.summary": { params: UsageSummaryRequest; result: UsageSummary };
  "memory.list": { params: WorkspaceListQuery; result: PageOfMemoryEntry };
  "memory.get": { params: GetMemoryRequest; result: MemoryEntry };
  "memory.update": { params: UpdateMemoryRequest };
  "agentMemory.list": { params: AgentMemoryListRequest; result: AgentMemoryList };
  "agentMemory.review": { params: AgentMemoryReviewRequest };
  "agentMemory.update": { params: AgentMemoryUpdateRequest; result: AgentMemoryItem };
  "agentMemory.delete": { params: AgentMemoryItemRequest };
  "agentMemory.add": { params: AgentMemoryAddRequest; result: AgentMemoryItem };
  "feedback.create": { params: FeedbackRequest };
}

export type WireParams<M extends WireMethodName> = WireShapes[M]["params"];

/** A method with no result answers with an empty success. */
export type WireResult<M extends WireMethodName> =
  WireShapes[M] extends { result: infer R } ? R : void;
