package model

// ResponseMetadata represents metadata associated with the AI model's response.
// This marker interface provides additional context and insights into the overall
// response, such as total computation time, request ID, or other relevant details
// that enhance understanding and management of AI model responses.
type ResponseMetadata interface {
}

// Response represents the response received from an AI model. It provides
// methods to access the main result or a list of results generated by the AI model,
// along with the response metadata. It serves as a standardized way to encapsulate
// and manage the output from AI models, ensuring easy retrieval and processing
// of the generated information.
//
// R is the type of the result that must implement the Result interface.
// M is the type of metadata that must implement ResponseMetadata.
type Response[R any, M ResponseMetadata] interface {
	// Result returns the primary result generated by the AI model.
	Result() R

	// Results returns the list of all results generated by the AI model.
	Results() []R

	// Metadata returns the response metadata associated with the AI model's response.
	Metadata() M
}
